import type { DefRecurso, Opcion } from "./tipos";

/** Inventario: productos por empresa + catálogos de apoyo (categorías, marcas de repuestos). */

export const CONDICIONES: readonly Opcion[] = [
  { valor: "nuevo", etiqueta: "Nuevo" },
  { valor: "usado", etiqueta: "Usado" },
  { valor: "reconstruido", etiqueta: "Reconstruido" },
];

export const ORIGENES: readonly Opcion[] = [
  { valor: "original", etiqueta: "Original de agencia" },
  { valor: "oem", etiqueta: "OEM" },
  { valor: "alternativo", etiqueta: "Alternativo" },
];

export const UNIDADES: readonly Opcion[] = [
  { valor: "unidad", etiqueta: "Unidad" },
  { valor: "par", etiqueta: "Par" },
  { valor: "juego", etiqueta: "Juego" },
  { valor: "kit", etiqueta: "Kit" },
  { valor: "litro", etiqueta: "Litro" },
  { valor: "cuarto", etiqueta: "Cuarto" },
  { valor: "galon", etiqueta: "Galón" },
  { valor: "metro", etiqueta: "Metro" },
  { valor: "caja", etiqueta: "Caja" },
  { valor: "servicio", etiqueta: "Servicio" },
];

const SI_NO: readonly Opcion[] = [
  { valor: "true", etiqueta: "Sí" },
  { valor: "false", etiqueta: "No" },
];

const CATEGORIAS_ACTIVAS = {
  recurso: "categorias",
  valor: "id",
  etiqueta: "ruta",
  fijo: { columna: "activa", valor: true },
} as const;

export const productos: DefRecurso = {
  id: "productos",
  nombre: "producto",
  nombrePlural: "Productos",
  vista: "v_productos",
  tabla: "productos",
  clave: "id",
  ambito: "empresa",
  escritura: "empresa",
  titulo: "nombre",
  ventana: { w: 980, h: 760 },
  orden: [{ columna: "nombre", dir: "asc" }],
  columnasInternas: ["id_categoria", "id_marca_producto", "bajo_minimo", "descripcion", "notas", "codigo_barras"],
  columnas: [
    { clave: "imagen", etiqueta: "Foto", tipo: "texto", ancho: 58, formato: "imagen", ordenable: false, filtro: false },
    { clave: "codigo", etiqueta: "Código", tipo: "texto", ancho: 120, buscable: true, formato: "codigo" },
    { clave: "nombre", etiqueta: "Nombre", tipo: "texto", ancho: 280, buscable: true },
    {
      clave: "categoria_ruta",
      etiqueta: "Categoría",
      tipo: "texto",
      ancho: 230,
      buscable: true,
      filtro: { tipo: "opciones", fuente: { recurso: "categorias", valor: "ruta", etiqueta: "ruta" } },
    },
    {
      clave: "marca",
      etiqueta: "Marca",
      tipo: "texto",
      ancho: 140,
      buscable: true,
      filtro: { tipo: "opciones", fuente: { recurso: "marcas_productos", valor: "nombre", etiqueta: "nombre" } },
    },
    { clave: "oem", etiqueta: "OEM", tipo: "texto", ancho: 140, buscable: true, formato: "codigo" },
    { clave: "numero_parte", etiqueta: "N.º de parte", tipo: "texto", ancho: 140, buscable: true, formato: "codigo", oculta: true },
    { clave: "referencias", etiqueta: "Equivalencias", tipo: "texto", ancho: 180, buscable: true, formato: "codigo", oculta: true },
    { clave: "existencia", etiqueta: "Existencia", tipo: "decimal", ancho: 120, alerta: "bajo_minimo" },
    { clave: "existencia_minima", etiqueta: "Mínimo", tipo: "decimal", ancho: 100, oculta: true },
    { clave: "costo", etiqueta: "Costo", tipo: "decimal", ancho: 120, formato: "moneda", oculta: true },
    { clave: "precio", etiqueta: "Precio", tipo: "decimal", ancho: 120, formato: "moneda" },
    { clave: "precio_final", etiqueta: "Con ISV", tipo: "decimal", ancho: 120, formato: "moneda" },
    { clave: "utilidad", etiqueta: "Utilidad", tipo: "decimal", ancho: 120, formato: "moneda", oculta: true },
    { clave: "margen", etiqueta: "Margen", tipo: "decimal", ancho: 100, formato: "porcentaje" },
    { clave: "compatibilidades", etiqueta: "Vehículos", tipo: "entero", ancho: 110, vacio: "General" },
    { clave: "ubicacion", etiqueta: "Ubicación", tipo: "texto", ancho: 120, formato: "codigo", oculta: true },
    {
      clave: "condicion",
      etiqueta: "Condición",
      tipo: "texto",
      ancho: 120,
      opciones: CONDICIONES,
      filtro: { tipo: "opciones", opciones: CONDICIONES },
      oculta: true,
    },
    { clave: "unidad", etiqueta: "Unidad", tipo: "texto", ancho: 100, opciones: UNIDADES, oculta: true },
    { clave: "activo", etiqueta: "Activo", tipo: "booleano", ancho: 90, opciones: SI_NO, oculta: true },
    { clave: "visible_catalogo", etiqueta: "En catálogo", tipo: "booleano", ancho: 110, opciones: SI_NO, oculta: true },
    { clave: "actualizado_en", etiqueta: "Actualizado", tipo: "fecha", ancho: 130, oculta: true },
  ],
  campos: [
    // Identificación
    {
      nombre: "nombre",
      etiqueta: "Nombre",
      tipo: "texto",
      requerido: true,
      maxLargo: 160,
      placeholder: "Pastillas de freno delanteras cerámicas",
      ancho: "completo",
      seccion: "Identificación",
    },
    {
      nombre: "id_categoria",
      etiqueta: "Categoría",
      tipo: "relacion",
      requerido: true,
      relacion: CATEGORIAS_ACTIVAS,
      ayuda: "Escribí «pastillas», «candelas», «filtro»…",
    },
    {
      nombre: "id_marca_producto",
      etiqueta: "Marca",
      tipo: "relacion",
      relacion: { recurso: "marcas_productos", valor: "id", etiqueta: "nombre", fijo: { columna: "activa", valor: true } },
      ayuda: "¿No está? Agregala en Inventario › Marcas.",
    },
    {
      nombre: "codigo",
      etiqueta: "Código interno",
      tipo: "texto",
      mayusculas: true,
      maxLargo: 40,
      placeholder: "Automático",
      ayuda: "Vacío = se genera (P-000123).",
    },
    { nombre: "oem", etiqueta: "Número OEM", tipo: "texto", mayusculas: true, maxLargo: 60, placeholder: "04465-02220" },
    { nombre: "numero_parte", etiqueta: "N.º de parte de la marca", tipo: "texto", mayusculas: true, maxLargo: 60, placeholder: "0986AB1234" },
    { nombre: "codigo_barras", etiqueta: "Código de barras", tipo: "texto", maxLargo: 60 },
    {
      nombre: "referencias",
      etiqueta: "Equivalencias",
      tipo: "texto",
      mayusculas: true,
      maxLargo: 400,
      placeholder: "D1210, 7925-D1210",
      ayuda: "Otros números que sirven para buscarlo, separados por coma.",
      ancho: "completo",
    },
    // Precio
    {
      nombre: "costo",
      etiqueta: "Costo",
      tipo: "decimal",
      requerido: true,
      min: 0,
      prefijo: "L",
      placeholder: "0.00",
      porDefecto: 0,
      ayuda: "Sin ISV.",
      seccion: "Precio",
    },
    {
      nombre: "precio",
      etiqueta: "Precio de venta",
      tipo: "decimal",
      requerido: true,
      min: 0,
      prefijo: "L",
      placeholder: "0.00",
      porDefecto: 0,
      ayuda: "Sin ISV. En la factura se suma el 15 %.",
    },
    {
      nombre: "precio_final",
      etiqueta: "Precio con ISV",
      tipo: "calculado",
      calculo: { tipo: "conImpuesto", base: "precio", tasa: 0.15, exento: "exento" },
      formato: "moneda",
    },
    {
      nombre: "utilidad",
      etiqueta: "Utilidad",
      tipo: "calculado",
      calculo: { tipo: "resta", a: "precio", b: "costo" },
      formato: "moneda",
    },
    {
      nombre: "margen",
      etiqueta: "Margen",
      tipo: "calculado",
      calculo: { tipo: "margen", precio: "precio", costo: "costo" },
      formato: "porcentaje",
    },
    { nombre: "exento", etiqueta: "Exento de ISV", tipo: "booleano", ayuda: "Casi todos los repuestos pagan ISV." },
    // Inventario
    {
      nombre: "existencia",
      etiqueta: "Existencia",
      tipo: "decimal",
      min: -99999,
      placeholder: "0",
      porDefecto: 0,
      ayuda: "Cada cambio queda en el kardex.",
      seccion: "Inventario",
    },
    {
      nombre: "existencia_minima",
      etiqueta: "Mínimo antes de alertar",
      tipo: "decimal",
      min: 0,
      placeholder: "0",
      porDefecto: 0,
    },
    {
      nombre: "unidad",
      etiqueta: "Unidad",
      tipo: "opciones",
      requerido: true,
      opciones: UNIDADES,
      porDefecto: "unidad",
    },
    { nombre: "ubicacion", etiqueta: "Ubicación", tipo: "texto", mayusculas: true, maxLargo: 40, placeholder: "ESTANTE A3" },
    {
      nombre: "condicion",
      etiqueta: "Condición",
      tipo: "opciones",
      requerido: true,
      presentacion: "tarjetas",
      opciones: CONDICIONES,
      porDefecto: "nuevo",
      ancho: "completo",
    },
    {
      nombre: "origen",
      etiqueta: "Origen",
      tipo: "opciones",
      presentacion: "tarjetas",
      opciones: ORIGENES,
      ancho: "completo",
      ayuda: "Original = de agencia · OEM = del fabricante original sin logo · Alternativo = otra marca.",
    },
    { nombre: "garantia_dias", etiqueta: "Garantía", tipo: "entero", min: 0, max: 3650, sufijo: "días", placeholder: "30" },
    {
      nombre: "controla_inventario",
      etiqueta: "Lleva inventario",
      tipo: "booleano",
      porDefecto: true,
      ayuda: "No para servicios (mano de obra).",
    },
    // Catálogo
    {
      nombre: "visible_catalogo",
      etiqueta: "Visible en el catálogo web",
      tipo: "booleano",
      porDefecto: true,
      seccion: "Catálogo y notas",
    },
    { nombre: "activo", etiqueta: "Activo", tipo: "booleano", porDefecto: true, ayuda: "Desactivalo en vez de borrarlo." },
    {
      nombre: "descripcion",
      etiqueta: "Descripción",
      tipo: "textoLargo",
      maxLargo: 1000,
      placeholder: "Lo que ve el cliente en el catálogo.",
      ancho: "completo",
    },
    { nombre: "notas", etiqueta: "Notas internas", tipo: "textoLargo", maxLargo: 1000, ancho: "completo" },
  ],
  mensajes: {
    duplicado: "Ya hay un producto con ese código interno.",
    enUso: "No se puede eliminar: el producto ya tiene ventas. Desactivalo.",
  },
};

export const movimientos: DefRecurso = {
  id: "movimientos",
  nombre: "movimiento",
  nombrePlural: "Kardex",
  vista: "v_movimientos_inventario",
  tabla: "movimientos_inventario",
  clave: "id",
  ambito: "empresa",
  escritura: "ninguna",
  acciones: { crear: false, editar: false, eliminar: false },
  titulo: "producto",
  orden: [{ columna: "creado_en", dir: "desc" }],
  columnas: [
    { clave: "creado_en", etiqueta: "Fecha", tipo: "fecha", ancho: 130 },
    { clave: "codigo", etiqueta: "Código", tipo: "texto", ancho: 120, buscable: true, formato: "codigo" },
    { clave: "producto", etiqueta: "Producto", tipo: "texto", ancho: 260, buscable: true },
    {
      clave: "tipo",
      etiqueta: "Movimiento",
      tipo: "texto",
      ancho: 130,
      opciones: [
        { valor: "inicial", etiqueta: "Inicial" },
        { valor: "ajuste", etiqueta: "Ajuste" },
        { valor: "venta", etiqueta: "Venta" },
        { valor: "anulacion", etiqueta: "Anulación" },
        { valor: "compra", etiqueta: "Compra" },
        { valor: "devolucion", etiqueta: "Devolución" },
      ],
      filtro: {
        tipo: "opciones",
        opciones: [
          { valor: "inicial", etiqueta: "Inicial" },
          { valor: "ajuste", etiqueta: "Ajuste" },
          { valor: "venta", etiqueta: "Venta" },
          { valor: "anulacion", etiqueta: "Anulación" },
        ],
      },
    },
    { clave: "cantidad", etiqueta: "Cantidad", tipo: "decimal", ancho: 110 },
    { clave: "existencia", etiqueta: "Queda", tipo: "decimal", ancho: 100 },
    { clave: "referencia", etiqueta: "Documento", tipo: "texto", ancho: 190, buscable: true, formato: "codigo" },
    { clave: "usuario", etiqueta: "Usuario", tipo: "texto", ancho: 170 },
  ],
  campos: [],
};

export const marcasProductos: DefRecurso = {
  id: "marcas_productos",
  nombre: "marca",
  nombrePlural: "Marcas de repuestos",
  genero: "f",
  vista: "v_marcas_productos",
  tabla: "marcas_productos",
  clave: "id",
  ambito: "compartido",
  escritura: "empresa",
  titulo: "nombre",
  orden: [{ columna: "nombre", dir: "asc" }],
  columnas: [
    { clave: "nombre", etiqueta: "Marca", tipo: "texto", ancho: 240, buscable: true },
    { clave: "pais", etiqueta: "País", tipo: "texto", ancho: 160, buscable: true },
    {
      clave: "global",
      etiqueta: "Origen",
      tipo: "booleano",
      ancho: 150,
      opciones: [
        { valor: "true", etiqueta: "Catálogo general" },
        { valor: "false", etiqueta: "Propia" },
      ],
    },
    { clave: "productos", etiqueta: "Productos", tipo: "entero", ancho: 120, formato: "miles" },
    { clave: "activa", etiqueta: "Activa", tipo: "booleano", ancho: 100, opciones: SI_NO },
  ],
  campos: [
    { nombre: "nombre", etiqueta: "Marca", tipo: "texto", requerido: true, mayusculas: true, maxLargo: 60, placeholder: "BOSCH" },
    { nombre: "pais", etiqueta: "País", tipo: "texto", maxLargo: 60, placeholder: "Alemania" },
    { nombre: "activa", etiqueta: "Activa", tipo: "booleano", porDefecto: true },
  ],
  mensajes: {
    duplicado: "Esa marca ya existe.",
    enUso: "No se puede eliminar: hay productos con esta marca. Desactivala.",
  },
};

export const categorias: DefRecurso = {
  id: "categorias",
  nombre: "categoría",
  nombrePlural: "Categorías",
  genero: "f",
  vista: "v_categorias",
  tabla: "categorias",
  clave: "id",
  escritura: "admin_plataforma",
  titulo: "nombre",
  orden: [{ columna: "orden_arbol", dir: "asc" }],
  columnasInternas: ["id_padre", "orden_arbol"],
  columnas: [
    { clave: "ruta", etiqueta: "Categoría", tipo: "texto", ancho: 340, buscable: true },
    { clave: "nivel", etiqueta: "Nivel", tipo: "entero", ancho: 80 },
    { clave: "sinonimos", etiqueta: "Sinónimos", tipo: "texto", ancho: 320, buscable: true },
    { clave: "subcategorias", etiqueta: "Subcategorías", tipo: "entero", ancho: 130 },
    { clave: "relacionadas", etiqueta: "Relacionadas", tipo: "entero", ancho: 120 },
    {
      clave: "es_servicio",
      etiqueta: "Tipo",
      tipo: "booleano",
      ancho: 120,
      opciones: [
        { valor: "true", etiqueta: "Servicio" },
        { valor: "false", etiqueta: "Producto" },
      ],
    },
    { clave: "orden", etiqueta: "Orden", tipo: "entero", ancho: 80, oculta: true },
    { clave: "slug", etiqueta: "Clave", tipo: "texto", ancho: 180, formato: "codigo", oculta: true },
    { clave: "activa", etiqueta: "Activa", tipo: "booleano", ancho: 90, opciones: SI_NO },
  ],
  campos: [
    {
      nombre: "id_padre",
      etiqueta: "Dentro de",
      tipo: "relacion",
      relacion: { recurso: "categorias", valor: "id", etiqueta: "ruta" },
      ayuda: "Vacío = categoría principal. Máximo 3 niveles.",
      ancho: "completo",
    },
    { nombre: "nombre", etiqueta: "Nombre", tipo: "texto", requerido: true, maxLargo: 80, placeholder: "Pastillas de freno" },
    { nombre: "orden", etiqueta: "Orden", tipo: "entero", min: 0, max: 9999, porDefecto: 0 },
    {
      nombre: "sinonimos",
      etiqueta: "Sinónimos de mostrador",
      tipo: "textoLargo",
      maxLargo: 400,
      placeholder: "fricciones, balatas, pads",
      ayuda: "Cómo le dicen en la calle. Alimenta la búsqueda.",
      ancho: "completo",
    },
    { nombre: "descripcion", etiqueta: "Descripción", tipo: "textoLargo", maxLargo: 400, ancho: "completo" },
    { nombre: "activa", etiqueta: "Activa", tipo: "booleano", porDefecto: true },
  ],
  mensajes: {
    duplicado: "Ya existe una categoría con esa clave.",
    enUso: "No se puede eliminar: tiene subcategorías o productos.",
  },
};

export const categoriasRelacionadas: DefRecurso = {
  id: "categorias_relacionadas",
  nombre: "relación",
  nombrePlural: "Complementos",
  genero: "f",
  vista: "v_categorias_relacionadas",
  tabla: "categorias_relacionadas",
  clave: "id",
  escritura: "admin_plataforma",
  acciones: { editar: true },
  titulo: ["categoria", "relacionada"],
  orden: [{ columna: "categoria", dir: "asc" }],
  columnasInternas: ["id_categoria", "id_relacionada"],
  columnas: [
    { clave: "categoria", etiqueta: "Si busca…", tipo: "texto", ancho: 320, buscable: true },
    { clave: "relacionada", etiqueta: "…recomendar", tipo: "texto", ancho: 320, buscable: true },
    { clave: "motivo", etiqueta: "Motivo", tipo: "texto", ancho: 240, buscable: true },
  ],
  campos: [
    {
      nombre: "id_categoria",
      etiqueta: "Si busca",
      tipo: "relacion",
      requerido: true,
      soloAlCrear: true,
      relacion: { recurso: "categorias", valor: "id", etiqueta: "ruta" },
      ancho: "completo",
    },
    {
      nombre: "id_relacionada",
      etiqueta: "Recomendar",
      tipo: "relacion",
      requerido: true,
      soloAlCrear: true,
      relacion: { recurso: "categorias", valor: "id", etiqueta: "ruta" },
      ancho: "completo",
      ayuda: "La relación funciona en los dos sentidos.",
    },
    { nombre: "motivo", etiqueta: "Motivo", tipo: "texto", maxLargo: 120, placeholder: "Cambio de aceite", ancho: "completo" },
  ],
  mensajes: {
    duplicado: "Esas categorías ya están relacionadas.",
  },
};
