-- =============================================================================
-- 0004 · Productos: categorías, marcas de repuestos, inventario, imágenes,
--        compatibilidad con vehículos y búsqueda
-- -----------------------------------------------------------------------------
-- ESTADO: YA APLICADA (2026-09-28)
-- Idempotente y atómica. Requiere 0000–0003.
--
-- Qué crea:
--   · Extensiones pg_trgm y unaccent (esquema extensions) + wp_normalizar().
--   · categorias               Árbol global (máx. 3 niveles) con sinónimos de
--                              mostrador («candelas» = bujías). Semilla incluida.
--   · categorias_relacionadas  Pares simétricos para recomendar complementos
--                              (aceite de motor ↔ filtro de aceite). Semilla.
--   · marcas_productos         Marcas de repuestos: globales (semilla) + propias
--                              de cada empresa.
--   · productos                Por empresa: códigos, categoría, marca, OEM,
--                              costo, precio (sin ISV), utilidad y margen
--                              calculados, existencia y mínimo, ubicación…
--   · movimientos_inventario   Kardex automático: todo cambio de existencia deja
--                              un movimiento (trigger).
--   · productos_imagenes       Fotos en el bucket público «productos» (Storage).
--   · productos_compatibilidades  Producto ↔ marca / modelo / año / especificación.
--   · asignar_compatibilidades(), copiar_compatibilidades()
--   · buscar_productos()       Búsqueda de mostrador y catálogo: texto, códigos,
--                              vehículo, productos generales y complementos.
--   · buscar_vehiculos()       «corolla 05» → TOYOTA COROLLA 2005.
--   · Vistas v_categorias, v_categorias_relacionadas, v_marcas_productos,
--     v_productos, v_movimientos_inventario, v_productos_compatibilidades.
-- =============================================================================

begin;

set local search_path = public, extensions;

-- -----------------------------------------------------------------------------
-- 0. Extensiones y utilidades de texto
-- -----------------------------------------------------------------------------

create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

-- Minúsculas y sin tildes: base de toda comparación de búsqueda.
create or replace function public.wp_normalizar(valor text)
returns text
language sql
immutable
parallel safe
set search_path = public, extensions
as $$
  select lower(unaccent('unaccent'::regdictionary, coalesce(valor, '')));
$$;

-- Forma «de oído» para tolerar faltas comunes de mostrador: ll→y, v→b,
-- z/ce/ci→s, h muda, que/qui→ke/ki. Se aplica igual al texto guardado y a lo
-- que se busca («pastiyas» encuentra «pastillas», «balinera» y «valinera»).
create or replace function public.wp_fonetico(valor text)
returns text
language sql
immutable
parallel safe
set search_path = public, extensions
as $f$
  select regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
           public.wp_normalizar(valor),
           'll', 'y', 'g'),
           'v', 'b', 'g'),
           'z|c(?=[ei])', 's', 'g'),
           '(^|[^c])h', '\1', 'g'),
           'qu(?=[ei])', 'k', 'g');
$f$;

-- Códigos comparables: solo letras y números («04465-02220» → «0446502220»).
create or replace function public.wp_codigo(valor text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select lower(regexp_replace(coalesce(valor, ''), '[^0-9A-Za-z]', '', 'g'));
$$;

create or replace function pg_temp.agregar_restriccion(tabla regclass, nombre text, definicion text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = tabla and conname = nombre) then
    execute format('alter table %s add constraint %I %s', tabla, nombre, definicion);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Categorías (globales, árbol)
-- -----------------------------------------------------------------------------

create table if not exists public.categorias (
  id integer generated by default as identity primary key,
  id_padre integer references public.categorias (id) on delete restrict,
  slug text not null,
  nombre text not null,
  descripcion text,
  sinonimos text,
  es_servicio boolean not null default false,
  orden smallint not null default 0,
  activa boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint categorias_slug_key unique (slug)
);

create index if not exists categorias_id_padre_idx on public.categorias (id_padre);

select pg_temp.agregar_restriccion('public.categorias', 'categorias_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 80)$$);
select pg_temp.agregar_restriccion('public.categorias', 'categorias_slug_check',
  $$check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) <= 80)$$);
select pg_temp.agregar_restriccion('public.categorias', 'categorias_padre_check',
  $$check (id_padre is null or id_padre <> id)$$);

-- Normaliza, genera el slug, hereda «es servicio» y evita ciclos / más de 3 niveles.
create or replace function public.tg_categorias_arbol()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_nivel integer := 1;
  v_actual integer := new.id_padre;
  v_base text;
  v_n integer := 1;
begin
  new.nombre := regexp_replace(btrim(new.nombre), '\s+', ' ', 'g');
  new.descripcion := nullif(btrim(new.descripcion), '');
  new.sinonimos := nullif(regexp_replace(lower(btrim(new.sinonimos)), '\s*,\s*', ', ', 'g'), '');

  if new.slug is null or btrim(new.slug) = '' then
    v_base := btrim(regexp_replace(public.wp_normalizar(new.nombre), '[^a-z0-9]+', '-', 'g'), '-');
    v_base := left(coalesce(nullif(v_base, ''), 'categoria'), 70);
    new.slug := v_base;
    while exists (select 1 from public.categorias where slug = new.slug and id is distinct from new.id) loop
      v_n := v_n + 1;
      new.slug := v_base || '-' || v_n;
    end loop;
  end if;

  while v_actual is not null loop
    if v_actual = new.id then
      raise exception 'Una categoría no puede estar dentro de sí misma.';
    end if;
    v_nivel := v_nivel + 1;
    if v_nivel > 3 then
      raise exception 'El árbol de categorías admite como máximo 3 niveles.';
    end if;
    select c.id_padre into v_actual from public.categorias c where c.id = v_actual;
  end loop;

  if new.id_padre is not null then
    select c.es_servicio into new.es_servicio from public.categorias c where c.id = new.id_padre;
  end if;
  return new;
end;
$$;

create or replace trigger a_arbol
  before insert or update on public.categorias
  for each row execute function public.tg_categorias_arbol();

-- Ruta legible y texto de búsqueda de una categoría (incluye ancestros y sinónimos).
create or replace function public.categoria_texto(p_categoria integer)
returns text
language sql
stable
set search_path = ''
as $$
  with recursive sube as (
    select id, id_padre, nombre, sinonimos, 1 as paso from public.categorias where id = p_categoria
    union all
    select c.id, c.id_padre, c.nombre, c.sinonimos, s.paso + 1
      from public.categorias c join sube s on c.id = s.id_padre
  )
  select string_agg(concat_ws(' ', nombre, sinonimos), ' ' order by paso) from sube;
$$;

-- Ids de una categoría y todas sus descendientes.
create or replace function public.categorias_subarbol(p_categoria integer)
returns setof integer
language sql
stable
set search_path = ''
as $$
  with recursive baja as (
    select id from public.categorias where id = p_categoria
    union all
    select c.id from public.categorias c join baja b on c.id_padre = b.id
  )
  select id from baja;
$$;

-- -----------------------------------------------------------------------------
-- 2. Categorías relacionadas (simétricas)
-- -----------------------------------------------------------------------------

create table if not exists public.categorias_relacionadas (
  id integer generated by default as identity primary key,
  id_categoria integer not null references public.categorias (id) on delete cascade,
  id_relacionada integer not null references public.categorias (id) on delete cascade,
  motivo text,
  creado_en timestamptz not null default now(),
  constraint categorias_relacionadas_key unique (id_categoria, id_relacionada)
);

create index if not exists categorias_relacionadas_id_relacionada_idx
  on public.categorias_relacionadas (id_relacionada);

select pg_temp.agregar_restriccion('public.categorias_relacionadas', 'categorias_relacionadas_distintas_check',
  $$check (id_categoria <> id_relacionada)$$);

-- Mantiene el par inverso: A ↔ B.
create or replace function public.tg_categorias_relacionadas_simetria()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.categorias_relacionadas (id_categoria, id_relacionada, motivo)
    values (new.id_relacionada, new.id_categoria, new.motivo)
    on conflict (id_categoria, id_relacionada) do nothing;
    return new;
  elsif tg_op = 'UPDATE' then
    update public.categorias_relacionadas
       set motivo = new.motivo
     where id_categoria = new.id_relacionada and id_relacionada = new.id_categoria
       and motivo is distinct from new.motivo;
    return new;
  else
    delete from public.categorias_relacionadas
     where id_categoria = old.id_relacionada and id_relacionada = old.id_categoria;
    return old;
  end if;
end;
$$;

create or replace trigger z_simetria
  after insert or update or delete on public.categorias_relacionadas
  for each row execute function public.tg_categorias_relacionadas_simetria();

-- -----------------------------------------------------------------------------
-- 3. Marcas de repuestos (globales + propias de cada empresa)
-- -----------------------------------------------------------------------------

create table if not exists public.marcas_productos (
  id integer generated by default as identity primary key,
  id_empresa uuid references public.empresas (id) on delete cascade,
  nombre text not null,
  pais text,
  activa boolean not null default true,
  creado_en timestamptz not null default now()
);

create index if not exists marcas_productos_id_empresa_idx on public.marcas_productos (id_empresa);
create unique index if not exists marcas_productos_nombre_key
  on public.marcas_productos (coalesce(id_empresa, '00000000-0000-0000-0000-000000000000'::uuid), nombre);

select pg_temp.agregar_restriccion('public.marcas_productos', 'marcas_productos_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 60)$$);

create or replace function public.tg_marcas_productos()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.nombre := public.limpiar_texto(new.nombre);
  new.pais := nullif(btrim(new.pais), '');
  if tg_op = 'UPDATE' and new.id_empresa is distinct from old.id_empresa then
    raise exception 'No se puede cambiar la empresa de una marca.';
  end if;
  if new.id_empresa is not null and exists (
    select 1 from public.marcas_productos where id_empresa is null and nombre = new.nombre
  ) then
    raise exception 'Esa marca ya existe en el catálogo general.';
  end if;
  return new;
end;
$$;

create or replace trigger a_normalizar
  before insert or update on public.marcas_productos
  for each row execute function public.tg_marcas_productos();

-- -----------------------------------------------------------------------------
-- 4. Productos
-- -----------------------------------------------------------------------------

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  codigo text not null,
  nombre text not null,
  descripcion text,
  id_categoria integer not null references public.categorias (id),
  id_marca_producto integer references public.marcas_productos (id) on delete set null,
  oem text,
  numero_parte text,
  codigo_barras text,
  referencias text,
  condicion text not null default 'nuevo',
  origen text,
  unidad text not null default 'unidad',
  costo numeric(14, 2) not null default 0,
  precio numeric(14, 2) not null default 0,
  exento boolean not null default false,
  utilidad numeric(14, 2) generated always as (precio - costo) stored,
  margen numeric(7, 2) generated always as (
    case when precio > 0 then round((precio - costo) / precio * 100, 2) end
  ) stored,
  controla_inventario boolean not null default true,
  existencia numeric(12, 2) not null default 0,
  existencia_minima numeric(12, 2) not null default 0,
  ubicacion text,
  garantia_dias integer,
  visible_catalogo boolean not null default true,
  activo boolean not null default true,
  notas text,
  texto_busqueda text not null default '',
  codigos text not null default '',
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  actualizado_en timestamptz not null default now(),
  constraint productos_codigo_key unique (id_empresa, codigo)
);

create index if not exists productos_id_categoria_idx on public.productos (id_categoria);
create index if not exists productos_id_marca_producto_idx on public.productos (id_marca_producto);
create index if not exists productos_creado_por_idx on public.productos (creado_por);
create index if not exists productos_empresa_activo_idx on public.productos (id_empresa, activo);
create index if not exists productos_texto_trgm_idx on public.productos using gin (texto_busqueda gin_trgm_ops);
create index if not exists productos_codigos_trgm_idx on public.productos using gin (codigos gin_trgm_ops);

select pg_temp.agregar_restriccion('public.productos', 'productos_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 160)$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_codigo_check',
  $$check (btrim(codigo) <> '' and char_length(codigo) <= 40)$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_condicion_check',
  $$check (condicion in ('nuevo', 'usado', 'reconstruido'))$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_origen_check',
  $$check (origen is null or origen in ('original', 'oem', 'alternativo'))$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_unidad_check',
  $$check (unidad in ('unidad', 'par', 'juego', 'kit', 'litro', 'galon', 'cuarto', 'metro', 'caja', 'servicio'))$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_montos_check',
  $$check (costo >= 0 and precio >= 0 and existencia_minima >= 0)$$);
select pg_temp.agregar_restriccion('public.productos', 'productos_garantia_check',
  $$check (garantia_dias is null or garantia_dias between 0 and 3650)$$);

-- Normaliza, genera el código si viene vacío y arma el texto de búsqueda.
create or replace function public.tg_productos_preparar()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_servicio boolean;
  v_marca text;
  v_ref text;
  v_codigos text[] := '{}';
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un producto.';
  end if;

  new.nombre := regexp_replace(btrim(new.nombre), '\s+', ' ', 'g');
  new.codigo := upper(btrim(coalesce(new.codigo, '')));
  if new.codigo = '' then
    new.codigo := 'P-' || lpad(new.id::text, 6, '0');
  end if;
  new.descripcion := nullif(btrim(new.descripcion), '');
  new.oem := nullif(upper(btrim(new.oem)), '');
  new.numero_parte := nullif(upper(btrim(new.numero_parte)), '');
  new.codigo_barras := nullif(btrim(new.codigo_barras), '');
  new.referencias := nullif(upper(btrim(new.referencias)), '');
  new.ubicacion := nullif(upper(btrim(new.ubicacion)), '');
  new.notas := nullif(btrim(new.notas), '');

  select c.es_servicio into v_servicio from public.categorias c where c.id = new.id_categoria;
  if coalesce(v_servicio, false) then
    new.controla_inventario := false;
    new.unidad := 'servicio';
  end if;
  if not new.controla_inventario then
    new.existencia := 0;
    new.existencia_minima := 0;
  end if;

  select m.nombre into v_marca from public.marcas_productos m where m.id = new.id_marca_producto;

  v_codigos := array[
    public.wp_codigo(new.codigo), public.wp_codigo(new.oem),
    public.wp_codigo(new.numero_parte), public.wp_codigo(new.codigo_barras)
  ];
  foreach v_ref in array regexp_split_to_array(coalesce(new.referencias, ''), '[,;/\s]+') loop
    v_codigos := v_codigos || public.wp_codigo(v_ref);
  end loop;
  new.codigos := ' ' || array_to_string(array(select distinct c from unnest(v_codigos) c where c <> ''), ' ') || ' ';

  new.texto_busqueda := public.wp_fonetico(concat_ws(' ',
    new.nombre, new.descripcion, v_marca, public.categoria_texto(new.id_categoria),
    new.codigo, new.oem, new.numero_parte, new.referencias,
    case new.condicion when 'usado' then 'usado' when 'reconstruido' then 'reconstruido' end
  )) || new.codigos;

  new.actualizado_en := now();
  return new;
end;
$$;

create or replace trigger a_preparar
  before insert or update on public.productos
  for each row execute function public.tg_productos_preparar();

-- Si cambia el nombre o los sinónimos de una categoría o marca, se rehace el
-- texto de búsqueda de sus productos (de todas las empresas).
create or replace function public.tg_refrescar_busqueda_productos()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_name = 'categorias' then
    update public.productos set texto_busqueda = texto_busqueda
     where id_categoria in (select public.categorias_subarbol(new.id));
  else
    update public.productos set texto_busqueda = texto_busqueda
     where id_marca_producto = new.id;
  end if;
  return null;
end;
$$;

create or replace trigger z_refrescar_productos
  after update of nombre, sinonimos, id_padre on public.categorias
  for each row
  when (old.nombre is distinct from new.nombre or old.sinonimos is distinct from new.sinonimos
        or old.id_padre is distinct from new.id_padre)
  execute function public.tg_refrescar_busqueda_productos();

create or replace trigger z_refrescar_productos
  after update of nombre on public.marcas_productos
  for each row
  when (old.nombre is distinct from new.nombre)
  execute function public.tg_refrescar_busqueda_productos();

-- -----------------------------------------------------------------------------
-- 5. Kardex (movimientos de inventario)
-- -----------------------------------------------------------------------------

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint not null references public.productos (id) on delete cascade,
  tipo text not null,
  cantidad numeric(12, 2) not null,
  existencia numeric(12, 2) not null,
  costo numeric(14, 2),
  referencia text,
  id_usuario uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now()
);

create index if not exists movimientos_inventario_producto_idx on public.movimientos_inventario (id_producto, creado_en desc);
create index if not exists movimientos_inventario_empresa_idx on public.movimientos_inventario (id_empresa, creado_en desc);
create index if not exists movimientos_inventario_id_usuario_idx on public.movimientos_inventario (id_usuario);

select pg_temp.agregar_restriccion('public.movimientos_inventario', 'movimientos_inventario_tipo_check',
  $$check (tipo in ('inicial', 'ajuste', 'venta', 'anulacion', 'compra', 'devolucion'))$$);

-- Todo cambio de existencia deja un movimiento. Quien cambia la existencia por
-- una operación (p. ej. facturar) define antes, dentro de la transacción:
--   set_config('wp.movimiento_tipo', 'venta', true)
--   set_config('wp.movimiento_ref', '000-001-01-00000001', true)
create or replace function public.tg_productos_kardex()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_anterior numeric := case when tg_op = 'INSERT' then 0 else old.existencia end;
begin
  if new.existencia = v_anterior then
    return null;
  end if;
  insert into public.movimientos_inventario (id_empresa, id_producto, tipo, cantidad, existencia, costo, referencia)
  values (
    new.id_empresa, new.id,
    coalesce(nullif(current_setting('wp.movimiento_tipo', true), ''),
             case when tg_op = 'INSERT' then 'inicial' else 'ajuste' end),
    new.existencia - v_anterior,
    new.existencia,
    new.costo,
    nullif(current_setting('wp.movimiento_ref', true), '')
  );
  return null;
end;
$$;

create or replace trigger z_kardex
  after insert or update of existencia on public.productos
  for each row execute function public.tg_productos_kardex();

-- -----------------------------------------------------------------------------
-- 6. Imágenes de productos (Supabase Storage, bucket público «productos»)
--    Ruta: <id_empresa>/<id_producto>/<archivo>.webp
-- -----------------------------------------------------------------------------

create table if not exists public.productos_imagenes (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint not null references public.productos (id) on delete cascade,
  ruta text not null,
  ruta_miniatura text,
  ancho integer,
  alto integer,
  orden smallint not null default 0,
  creado_en timestamptz not null default now(),
  constraint productos_imagenes_ruta_key unique (ruta)
);

create index if not exists productos_imagenes_producto_idx on public.productos_imagenes (id_producto, orden);
create index if not exists productos_imagenes_id_empresa_idx on public.productos_imagenes (id_empresa);

create or replace function public.tg_productos_imagenes()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  select p.id_empresa into new.id_empresa from public.productos p where p.id = new.id_producto;
  if new.id_empresa is null then
    raise exception 'El producto no existe.';
  end if;
  if new.ruta not like new.id_empresa::text || '/' || new.id_producto::text || '/%'
     or (new.ruta_miniatura is not null
         and new.ruta_miniatura not like new.id_empresa::text || '/' || new.id_producto::text || '/%') then
    raise exception 'Ruta de imagen no válida.';
  end if;
  return new;
end;
$$;

create or replace trigger a_validar
  before insert or update on public.productos_imagenes
  for each row execute function public.tg_productos_imagenes();

-- Empresa dueña de un archivo según su carpeta (null si la ruta no es válida).
create or replace function public.empresa_de_ruta(p_ruta text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select case
    when split_part(p_ruta, '/', 1) ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      then split_part(p_ruta, '/', 1)::uuid
  end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('productos', 'productos', true, 5242880,
        array['image/webp', 'image/jpeg', 'image/png', 'image/avif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists wp_productos_lectura on storage.objects;
create policy wp_productos_lectura on storage.objects
  for select to authenticated
  using (bucket_id = 'productos' and public.es_miembro(public.empresa_de_ruta(name)));

drop policy if exists wp_productos_subir on storage.objects;
create policy wp_productos_subir on storage.objects
  for insert to authenticated
  with check (bucket_id = 'productos'
              and public.tiene_rol(public.empresa_de_ruta(name), array['dueno', 'admin']));

drop policy if exists wp_productos_cambiar on storage.objects;
create policy wp_productos_cambiar on storage.objects
  for update to authenticated
  using (bucket_id = 'productos' and public.tiene_rol(public.empresa_de_ruta(name), array['dueno', 'admin']))
  with check (bucket_id = 'productos' and public.tiene_rol(public.empresa_de_ruta(name), array['dueno', 'admin']));

drop policy if exists wp_productos_borrar on storage.objects;
create policy wp_productos_borrar on storage.objects
  for delete to authenticated
  using (bucket_id = 'productos' and public.tiene_rol(public.empresa_de_ruta(name), array['dueno', 'admin']));

-- -----------------------------------------------------------------------------
-- 7. Compatibilidad producto ↔ vehículo
--    Se guarda el nivel más específico elegido y el trigger completa los
--    ancestros: una fila de año lleva marca, modelo y año; una de marca, solo
--    la marca. Así «le queda a este vehículo» es una comparación directa.
-- -----------------------------------------------------------------------------

create table if not exists public.productos_compatibilidades (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint not null references public.productos (id) on delete cascade,
  id_marca integer not null references public.marcas (id) on delete cascade,
  id_modelo integer references public.modelos (id) on delete cascade,
  id_modelo_anio integer references public.modelos_anios (id) on delete cascade,
  id_especificacion integer references public.especificaciones (id) on delete cascade,
  nivel smallint generated always as (
    case
      when id_especificacion is not null then 4
      when id_modelo_anio is not null then 3
      when id_modelo is not null then 2
      else 1
    end
  ) stored,
  nota text,
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  constraint productos_compatibilidades_key
    unique nulls not distinct (id_producto, id_marca, id_modelo, id_modelo_anio, id_especificacion)
);

create index if not exists productos_compat_vehiculo_idx
  on public.productos_compatibilidades (id_empresa, id_marca, id_modelo, id_modelo_anio);
create index if not exists productos_compat_id_modelo_idx on public.productos_compatibilidades (id_modelo);
create index if not exists productos_compat_id_modelo_anio_idx on public.productos_compatibilidades (id_modelo_anio);
create index if not exists productos_compat_id_especificacion_idx on public.productos_compatibilidades (id_especificacion);
create index if not exists productos_compat_creado_por_idx on public.productos_compatibilidades (creado_por);

create or replace function public.tg_compatibilidades_completar()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.id_especificacion is not null then
    select e.id_modelo_anio into new.id_modelo_anio from public.especificaciones e where e.id = new.id_especificacion;
  end if;
  if new.id_modelo_anio is not null then
    select ya.id_modelo into new.id_modelo from public.modelos_anios ya where ya.id = new.id_modelo_anio;
  end if;
  if new.id_modelo is not null then
    select mo.id_marca into new.id_marca from public.modelos mo where mo.id = new.id_modelo;
  end if;
  select p.id_empresa into new.id_empresa from public.productos p where p.id = new.id_producto;
  new.nota := nullif(btrim(new.nota), '');
  return new;
end;
$$;

create or replace trigger a_completar
  before insert or update on public.productos_compatibilidades
  for each row execute function public.tg_compatibilidades_completar();

-- Quita filas cubiertas por otra más general del mismo producto
-- (si el producto sirve para todo COROLLA, sobran las filas de COROLLA 2005).
create or replace function public.compactar_compatibilidades(p_producto bigint)
returns integer
language sql
set search_path = ''
as $$
  with borradas as (
    delete from public.productos_compatibilidades c
     where c.id_producto = p_producto
       and exists (
         select 1 from public.productos_compatibilidades g
          where g.id_producto = c.id_producto
            and g.nivel < c.nivel
            and g.id_marca = c.id_marca
            and (g.id_modelo is null or g.id_modelo = c.id_modelo)
            and (g.id_modelo_anio is null or g.id_modelo_anio = c.id_modelo_anio)
       )
    returning 1
  )
  select count(*)::integer from borradas;
$$;

-- Asigna o quita en bloque. p_nivel: marca | modelo | anio | especificacion.
-- Devuelve cuántas filas cambiaron. Respeta RLS (dueño/admin de la empresa).
create or replace function public.asignar_compatibilidades(
  p_producto bigint,
  p_nivel text,
  p_ids integer[],
  p_asignar boolean default true
)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  v_n integer := 0;
begin
  if p_nivel not in ('marca', 'modelo', 'anio', 'especificacion') then
    raise exception 'Nivel de compatibilidad no válido.';
  end if;
  if coalesce(cardinality(p_ids), 0) = 0 then
    return 0;
  end if;
  if cardinality(p_ids) > 2000 then
    raise exception 'Demasiados vehículos en una sola operación.';
  end if;

  if p_asignar then
    insert into public.productos_compatibilidades (id_producto, id_marca, id_modelo, id_modelo_anio, id_especificacion)
    select p_producto,
           case when p_nivel = 'marca' then x end,
           case when p_nivel = 'modelo' then x end,
           case when p_nivel = 'anio' then x end,
           case when p_nivel = 'especificacion' then x end
      from unnest(p_ids) as x
    on conflict do nothing;
    get diagnostics v_n = row_count;
    perform public.compactar_compatibilidades(p_producto);
  else
    delete from public.productos_compatibilidades
     where id_producto = p_producto
       and case p_nivel
             when 'marca' then nivel = 1 and id_marca = any (p_ids)
             when 'modelo' then nivel = 2 and id_modelo = any (p_ids)
             when 'anio' then nivel = 3 and id_modelo_anio = any (p_ids)
             else nivel = 4 and id_especificacion = any (p_ids)
           end;
    get diagnostics v_n = row_count;
  end if;
  return v_n;
end;
$$;

-- Copia la compatibilidad de otro producto de la misma empresa.
create or replace function public.copiar_compatibilidades(p_origen bigint, p_destino bigint)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  v_n integer;
begin
  if (select id_empresa from public.productos where id = p_origen)
     is distinct from (select id_empresa from public.productos where id = p_destino) then
    raise exception 'Solo se puede copiar entre productos de la misma empresa.';
  end if;
  insert into public.productos_compatibilidades (id_producto, id_marca, id_modelo, id_modelo_anio, id_especificacion, nota)
  select p_destino, id_marca, id_modelo, id_modelo_anio, id_especificacion, nota
    from public.productos_compatibilidades
   where id_producto = p_origen
  on conflict do nothing;
  get diagnostics v_n = row_count;
  perform public.compactar_compatibilidades(p_destino);
  return v_n;
end;
$$;

-- -----------------------------------------------------------------------------
-- 8. Permisos y RLS
-- -----------------------------------------------------------------------------

revoke all on public.categorias, public.categorias_relacionadas, public.marcas_productos,
              public.productos, public.movimientos_inventario, public.productos_imagenes,
              public.productos_compatibilidades
  from anon, authenticated;

grant select on public.categorias, public.categorias_relacionadas to anon, authenticated;
grant insert, update, delete on public.categorias, public.categorias_relacionadas to authenticated;
grant select, insert, delete on public.marcas_productos to authenticated;
grant update (nombre, pais, activa) on public.marcas_productos to authenticated;
grant select, insert, delete on public.productos to authenticated;
grant update (codigo, nombre, descripcion, id_categoria, id_marca_producto, oem, numero_parte,
              codigo_barras, referencias, condicion, origen, unidad, costo, precio, exento,
              controla_inventario, existencia, existencia_minima, ubicacion, garantia_dias,
              visible_catalogo, activo, notas)
  on public.productos to authenticated;
grant select on public.movimientos_inventario to authenticated;
grant select, insert, delete on public.productos_imagenes to authenticated;
grant update (orden) on public.productos_imagenes to authenticated;
grant select, insert, delete on public.productos_compatibilidades to authenticated;
grant update (nota) on public.productos_compatibilidades to authenticated;

alter table public.categorias enable row level security;
alter table public.categorias_relacionadas enable row level security;
alter table public.marcas_productos enable row level security;
alter table public.productos enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.productos_imagenes enable row level security;
alter table public.productos_compatibilidades enable row level security;

do $$
declare
  tabla text;
begin
  foreach tabla in array array['categorias', 'categorias_relacionadas'] loop
    execute format('drop policy if exists catalogo_lectura_publica on public.%I', tabla);
    execute format('create policy catalogo_lectura_publica on public.%I for select to anon, authenticated using (true)', tabla);
    execute format('drop policy if exists catalogo_escritura_admin on public.%I', tabla);
    execute format(
      'create policy catalogo_escritura_admin on public.%I for all to authenticated
         using (public.es_admin_plataforma()) with check (public.es_admin_plataforma())', tabla);
  end loop;

  -- Tablas por empresa: leen los miembros, escriben dueño y administradores.
  foreach tabla in array array['productos', 'productos_imagenes', 'productos_compatibilidades'] loop
    execute format('drop policy if exists empresa_lectura on public.%I', tabla);
    execute format('create policy empresa_lectura on public.%I for select to authenticated
                      using (public.es_miembro(id_empresa))', tabla);
    execute format('drop policy if exists empresa_escritura on public.%I', tabla);
    execute format(
      'create policy empresa_escritura on public.%I for all to authenticated
         using (public.tiene_rol(id_empresa, array[''dueno'', ''admin'']))
         with check (public.tiene_rol(id_empresa, array[''dueno'', ''admin'']))', tabla);
  end loop;
end;
$$;

drop policy if exists empresa_lectura on public.movimientos_inventario;
create policy empresa_lectura on public.movimientos_inventario
  for select to authenticated using (public.es_miembro(id_empresa));

drop policy if exists marcas_productos_lectura on public.marcas_productos;
create policy marcas_productos_lectura on public.marcas_productos
  for select to authenticated
  using (id_empresa is null or public.es_miembro(id_empresa));

drop policy if exists marcas_productos_escritura on public.marcas_productos;
create policy marcas_productos_escritura on public.marcas_productos
  for all to authenticated
  using (case when id_empresa is null then public.es_admin_plataforma()
              else public.tiene_rol(id_empresa, array['dueno', 'admin']) end)
  with check (case when id_empresa is null then public.es_admin_plataforma()
                   else public.tiene_rol(id_empresa, array['dueno', 'admin']) end);

revoke all on function public.asignar_compatibilidades(bigint, text, integer[], boolean) from public, anon;
revoke all on function public.copiar_compatibilidades(bigint, bigint) from public, anon;
revoke all on function public.compactar_compatibilidades(bigint) from public, anon;
grant execute on function public.asignar_compatibilidades(bigint, text, integer[], boolean) to authenticated;
grant execute on function public.copiar_compatibilidades(bigint, bigint) to authenticated;
grant execute on function public.compactar_compatibilidades(bigint) to authenticated;

-- -----------------------------------------------------------------------------
-- 9. Vistas (tabla maestra)
-- -----------------------------------------------------------------------------

create or replace view public.v_categorias with (security_invoker = true) as
with recursive arbol as (
  select c.id, c.nombre::text as ruta, 1 as nivel,
         lpad(c.orden::text, 4, '0') || lpad(c.id::text, 6, '0') as orden_arbol
    from public.categorias c
   where c.id_padre is null
  union all
  select h.id, a.ruta || ' › ' || h.nombre, a.nivel + 1,
         a.orden_arbol || '.' || lpad(h.orden::text, 4, '0') || lpad(h.id::text, 6, '0')
    from public.categorias h
    join arbol a on a.id = h.id_padre
)
select c.id,
       c.id_padre,
       p.nombre as padre,
       c.nombre,
       a.ruta,
       a.nivel,
       a.orden_arbol,
       c.slug,
       c.descripcion,
       c.sinonimos,
       c.es_servicio,
       c.orden,
       c.activa,
       (select count(*) from public.categorias s where s.id_padre = c.id)::integer as subcategorias,
       (select count(*) from public.categorias_relacionadas r where r.id_categoria = c.id)::integer as relacionadas
  from public.categorias c
  join arbol a on a.id = c.id
  left join public.categorias p on p.id = c.id_padre;

create or replace view public.v_categorias_relacionadas with (security_invoker = true) as
select r.id,
       r.id_categoria,
       a.ruta as categoria,
       r.id_relacionada,
       b.ruta as relacionada,
       r.motivo
  from public.categorias_relacionadas r
  join public.v_categorias a on a.id = r.id_categoria
  join public.v_categorias b on b.id = r.id_relacionada;

create or replace view public.v_marcas_productos with (security_invoker = true) as
select m.id,
       m.id_empresa,
       m.nombre,
       m.pais,
       m.activa,
       (m.id_empresa is null) as global,
       (select count(*) from public.productos p where p.id_marca_producto = m.id)::integer as productos
  from public.marcas_productos m;

create or replace view public.v_productos with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.codigo,
       p.nombre,
       p.descripcion,
       p.id_categoria,
       c.nombre as categoria,
       vc.ruta as categoria_ruta,
       p.id_marca_producto,
       m.nombre as marca,
       p.oem,
       p.numero_parte,
       p.codigo_barras,
       p.referencias,
       p.condicion,
       p.origen,
       p.unidad,
       p.costo,
       p.precio,
       case when p.exento then p.precio else round(p.precio * 1.15, 2) end as precio_final,
       p.utilidad,
       p.margen,
       p.exento,
       p.controla_inventario,
       p.existencia,
       p.existencia_minima,
       (p.controla_inventario and p.existencia <= p.existencia_minima) as bajo_minimo,
       p.ubicacion,
       p.garantia_dias,
       p.visible_catalogo,
       p.activo,
       p.notas,
       (select coalesce(i.ruta_miniatura, i.ruta) from public.productos_imagenes i
         where i.id_producto = p.id order by i.orden, i.id limit 1) as imagen,
       (select count(*) from public.productos_imagenes i where i.id_producto = p.id)::integer as imagenes,
       (select count(*) from public.productos_compatibilidades k where k.id_producto = p.id)::integer as compatibilidades,
       p.creado_en,
       p.actualizado_en
  from public.productos p
  join public.categorias c on c.id = p.id_categoria
  join public.v_categorias vc on vc.id = p.id_categoria
  left join public.marcas_productos m on m.id = p.id_marca_producto;

create or replace view public.v_movimientos_inventario with (security_invoker = true) as
select mv.id,
       mv.id_empresa,
       mv.id_producto,
       p.codigo,
       p.nombre as producto,
       mv.tipo,
       mv.cantidad,
       mv.existencia,
       mv.costo,
       mv.referencia,
       u.nombre as usuario,
       mv.creado_en
  from public.movimientos_inventario mv
  join public.productos p on p.id = mv.id_producto
  left join public.usuarios u on u.id = mv.id_usuario;

create or replace view public.v_productos_compatibilidades with (security_invoker = true) as
select k.id,
       k.id_empresa,
       k.id_producto,
       k.nivel,
       k.id_marca,
       ma.marca,
       k.id_modelo,
       mo.modelo,
       k.id_modelo_anio,
       ya.anio,
       k.id_especificacion,
       case when e.id is not null then
         concat_ws(' · ', tc.carroceria, round(e.motor_cc / 1000.0, 1)::text || ' L',
                   e.motor_posicion_cilindros || e.motor_numero_cilindros::text, e.motor_numero)
       end as especificacion,
       k.nota
  from public.productos_compatibilidades k
  join public.marcas ma on ma.id = k.id_marca
  left join public.modelos mo on mo.id = k.id_modelo
  left join public.modelos_anios ya on ya.id = k.id_modelo_anio
  left join public.especificaciones e on e.id = k.id_especificacion
  left join public.tipos_carrocerias tc on tc.id = e.id_tipo_carroceria;

revoke all on public.v_categorias, public.v_categorias_relacionadas, public.v_marcas_productos,
              public.v_productos, public.v_movimientos_inventario, public.v_productos_compatibilidades
  from anon, authenticated;
grant select on public.v_categorias, public.v_categorias_relacionadas to anon, authenticated;
grant select on public.v_marcas_productos, public.v_productos, public.v_movimientos_inventario,
                public.v_productos_compatibilidades
  to authenticated;

-- -----------------------------------------------------------------------------
-- 10. Búsqueda de vehículos: «corolla 05», «hilux 2010», «nissan fron»
-- -----------------------------------------------------------------------------

create or replace function public.buscar_vehiculos(p_texto text, p_limite integer default 20)
returns table (
  id_marca integer,
  marca text,
  id_modelo integer,
  modelo text,
  id_modelo_anio integer,
  anio integer,
  anio_desde integer,
  anio_hasta integer
)
language plpgsql
stable
set search_path = public, extensions
as $$
#variable_conflict use_column
declare
  v_tokens text[] := array(
    select t from unnest(regexp_split_to_array(public.wp_normalizar(left(coalesce(p_texto, ''), 80)), '[^a-z0-9]+')) t
     where t <> ''
  );
  v_palabras text[] := '{}';
  v_anio integer;
  v_i integer;
begin
  for v_i in 1 .. coalesce(cardinality(v_tokens), 0) loop
    if v_tokens[v_i] ~ '^(19|20)[0-9]{2}$' then
      v_anio := v_tokens[v_i]::integer;
    elsif v_tokens[v_i] ~ '^[0-9]{2}$' and v_i = cardinality(v_tokens) and v_i > 1 then
      -- «corolla 05» → 2005 · «civic 98» → 1998
      v_anio := case when v_tokens[v_i]::integer >= 50 then 1900 else 2000 end + v_tokens[v_i]::integer;
    else
      v_palabras := v_palabras || v_tokens[v_i];
    end if;
  end loop;

  if cardinality(v_palabras) = 0 then
    return;
  end if;

  return query
  with candidatos as (
    select mo.id_marca, mo.marca::text as marca, mo.id as id_modelo, mo.modelo::text as modelo,
           mo.anio_desde, mo.anio_hasta, mo.anios,
           public.wp_normalizar(mo.marca || ' ' || mo.modelo) as texto,
           public.wp_codigo(mo.marca || mo.modelo) as junto,
           public.wp_normalizar(mo.modelo) as solo_modelo
      from public.v_modelos mo
  )
  select c.id_marca, c.marca, c.id_modelo, c.modelo, ya.id, ya.anio, c.anio_desde, c.anio_hasta
    from candidatos c
    left join public.modelos_anios ya on v_anio is not null and ya.id_modelo = c.id_modelo and ya.anio = v_anio
   where (v_anio is null or ya.id is not null)
     and not exists (
       select 1 from unnest(v_palabras) w
        where not (c.texto like '%' || w || '%' or c.junto like '%' || w || '%')
     )
   order by
     case
       when c.solo_modelo = array_to_string(v_palabras, ' ') then 0
       when c.solo_modelo like v_palabras[1] || '%' then 1
       when c.texto like v_palabras[1] || '%' then 2
       else 3
     end,
     c.marca, c.modelo
   limit least(greatest(coalesce(p_limite, 20), 1), 50);
end;
$$;

grant execute on function public.buscar_vehiculos(text, integer) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 11. Búsqueda de productos (mostrador y catálogo web)
--
-- · Texto: cada palabra debe aparecer (sin tildes, en nombre, marca, categoría y
--   sus sinónimos, códigos); las de 4+ letras toleran errores de dedo.
-- · Códigos: «0446502220» encuentra «04465-02220» (OEM, parte, barras, equivalencias).
-- · Vehículo (cualquier nivel): grupo «vehiculo» con el ajuste
--     motor | anio | modelo | marca  (le queda) · verificar (le queda a alguna
--     variante: confirmar año o motor); grupo «general» = productos sin
--     compatibilidad registrada (universales). Los que son de otros vehículos
--     no aparecen.
-- · Complementos: productos de categorías relacionadas con lo encontrado.
-- · Miembros ven costo y existencia; el público solo productos visibles en el
--   catálogo y si hay existencia.
-- -----------------------------------------------------------------------------

create or replace function public.buscar_productos(
  p_empresa uuid,
  p_texto text default '',
  p_id_marca integer default null,
  p_id_modelo integer default null,
  p_id_modelo_anio integer default null,
  p_id_especificacion integer default null,
  p_id_categoria integer default null,
  p_limite integer default 60
)
returns table (
  id bigint,
  codigo text,
  nombre text,
  marca text,
  id_categoria integer,
  categoria text,
  oem text,
  numero_parte text,
  condicion text,
  unidad text,
  precio numeric,
  exento boolean,
  costo numeric,
  existencia numeric,
  controla_inventario boolean,
  disponible boolean,
  ubicacion text,
  imagen text,
  grupo text,
  ajuste text,
  relevancia real,
  orden integer
)
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
#variable_conflict use_column
declare
  v_miembro boolean := public.es_miembro(p_empresa);
  v_marca integer := p_id_marca;
  v_modelo integer := p_id_modelo;
  v_anio integer := p_id_modelo_anio;
  v_esp integer := p_id_especificacion;
  v_texto text := btrim(public.wp_fonetico(left(coalesce(p_texto, ''), 120)));
  v_codigo text := public.wp_codigo(left(coalesce(p_texto, ''), 120));
  v_tokens text[];
  v_limite integer := least(greatest(coalesce(p_limite, 60), 1), 200);
  v_categorias integer[];
  v_difuso boolean := false;
begin
  if p_empresa is null then
    return;
  end if;
  if not v_miembro and not exists (select 1 from public.empresas e where e.id = p_empresa and e.activo) then
    return;
  end if;

  if v_esp is not null then
    select e.id_modelo_anio into v_anio from public.especificaciones e where e.id = v_esp;
  end if;
  if v_anio is not null then
    select ya.id_modelo into v_modelo from public.modelos_anios ya where ya.id = v_anio;
  end if;
  if v_modelo is not null then
    select mo.id_marca into v_marca from public.modelos mo where mo.id = v_modelo;
  end if;

  v_tokens := array(
    select distinct t from unnest(regexp_split_to_array(v_texto, '[^a-z0-9ñ]+')) t
     where char_length(t) >= 2 or t ~ '^[0-9]$'
     limit 8
  );
  if char_length(v_codigo) < 3 then
    v_codigo := '';
  end if;

  if p_id_categoria is not null then
    v_categorias := array(select public.categorias_subarbol(p_id_categoria));
  end if;

  -- Tolerancia a errores de dedo solo si la búsqueda exacta no encuentra nada
  -- (es la parte cara).
  if cardinality(v_tokens) > 0 then
    v_difuso := not exists (
      select 1 from public.productos p
       where p.id_empresa = p_empresa and p.activo
         and not exists (select 1 from unnest(v_tokens) t where not (p.texto_busqueda like '%' || t || '%'))
    ) and not exists (
      select 1 from public.productos p
       where v_codigo <> '' and p.id_empresa = p_empresa and p.activo and p.codigos like '%' || v_codigo || '%'
    );
  end if;

  return query
  with base as (
    select p.*
      from public.productos p
     where p.id_empresa = p_empresa
       and p.activo
       and (v_miembro or (p.visible_catalogo and (not p.controla_inventario or p.existencia > 0)))
       and (v_categorias is null or p.id_categoria = any (v_categorias))
  ),
  coincidencias as (
    select b.*,
           case
             when v_codigo <> '' and b.codigos like '% ' || v_codigo || ' %' then 100
             when v_codigo <> '' and b.codigos like '% ' || v_codigo || '%' then 60
             when v_codigo <> '' and char_length(v_codigo) >= 5 and b.codigos like '%' || v_codigo || '%' then 30
             else 0
           end as puntos_codigo,
           (select coalesce(sum(case when b.texto_busqueda like '%' || t || '%' then 1.0
                                     when v_difuso then word_similarity(t, b.texto_busqueda)
                                     else 0 end), 0)
              from unnest(v_tokens) t)::real as puntos_texto
      from base b
     where cardinality(v_tokens) = 0
        or (v_codigo <> '' and b.codigos like '%' || v_codigo || '%')
        or not exists (
          select 1 from unnest(v_tokens) t
           where not (b.texto_busqueda like '%' || t || '%'
                      or (v_difuso and char_length(t) >= 4 and t <% b.texto_busqueda))
        )
  ),
  ajustes as (
    select k.id_producto,
           max(case
                 when (k.id_modelo is null or k.id_modelo = v_modelo)
                  and (k.id_modelo_anio is null or k.id_modelo_anio = v_anio)
                  and (k.id_especificacion is null or k.id_especificacion = v_esp)
                 then k.nivel * 10
                 else k.nivel
               end) as puntos
      from public.productos_compatibilidades k
     where v_marca is not null
       and k.id_empresa = p_empresa
       and k.id_marca = v_marca
       and (v_modelo is null or k.id_modelo is null or k.id_modelo = v_modelo)
       and (v_anio is null or k.id_modelo_anio is null or k.id_modelo_anio = v_anio)
       and (v_esp is null or k.id_especificacion is null or k.id_especificacion = v_esp)
     group by k.id_producto
  ),
  clasificados as (
    select c.*,
           a.puntos as puntos_ajuste,
           case
             when v_marca is null then 'todos'
             when a.puntos is not null then 'vehiculo'
             when not exists (select 1 from public.productos_compatibilidades k where k.id_producto = c.id) then 'general'
           end as grupo_calc,
           case
             when a.puntos >= 40 then 'motor'
             when a.puntos >= 30 then 'anio'
             when a.puntos >= 20 then 'modelo'
             when a.puntos >= 10 then 'marca'
             when a.puntos is not null then 'verificar'
           end as ajuste_calc,
           (c.puntos_codigo
             + c.puntos_texto * 10
             + case when v_texto <> '' and public.wp_fonetico(c.nombre) like v_texto || '%' then 15 else 0 end
             + case when v_texto <> '' then similarity(public.wp_fonetico(c.nombre), v_texto) * 10 else 0 end
             + case when not c.controla_inventario or c.existencia > 0 then 2 else 0 end
           )::real as puntos_total
      from coincidencias c
      left join ajustes a on a.id_producto = c.id
  ),
  principal as (
    select x.*,
           row_number() over (
             order by
               case x.grupo_calc when 'vehiculo' then case when x.puntos_ajuste >= 10 then 0 else 1 end
                                 when 'todos' then 0 else 2 end,
               x.puntos_total desc,
               coalesce(x.puntos_ajuste, 0) desc,
               (not x.controla_inventario or x.existencia > 0) desc,
               x.nombre
           )::integer as posicion
      from clasificados x
     where x.grupo_calc is not null
  ),
  limitados as (
    select * from principal where posicion <= v_limite
  ),
  -- Categorías de lo encontrado + las que nombra el texto → sus relacionadas.
  categorias_base as (
    select l.id_categoria from limitados l where l.posicion <= 12
    union
    select c.id from public.categorias c
     where cardinality(v_tokens) > 0 and c.activa
       and not exists (
         select 1 from unnest(v_tokens) t
          where not (public.wp_fonetico(concat_ws(' ', c.nombre, c.sinonimos)) like '%' || t || '%')
       )
  ),
  relacionadas as (
    select distinct r.id_relacionada as id_categoria
      from public.categorias_relacionadas r
     where r.id_categoria in (select cb.id_categoria from categorias_base cb)
       and r.id_relacionada not in (select cb.id_categoria from categorias_base cb)
  ),
  complementos as (
    select b.*,
           a.puntos as puntos_ajuste,
           row_number() over (
             order by coalesce(a.puntos, 0) desc,
                      (not b.controla_inventario or b.existencia > 0) desc,
                      b.nombre
           )::integer as posicion
      from base b
      left join ajustes a on a.id_producto = b.id
     where b.id_categoria in (select rl.id_categoria from relacionadas rl)
       and b.id not in (select l.id from limitados l)
       and (v_marca is null
            or a.puntos is not null
            or not exists (select 1 from public.productos_compatibilidades k where k.id_producto = b.id))
  )
  select l.id, l.codigo, l.nombre, mp.nombre, l.id_categoria, cat.nombre, l.oem, l.numero_parte,
         l.condicion, l.unidad, l.precio, l.exento,
         case when v_miembro then l.costo end,
         case when v_miembro then l.existencia end,
         l.controla_inventario,
         (not l.controla_inventario or l.existencia > 0),
         case when v_miembro then l.ubicacion end,
         (select coalesce(i.ruta_miniatura, i.ruta) from public.productos_imagenes i
           where i.id_producto = l.id order by i.orden, i.id limit 1),
         l.grupo_calc, l.ajuste_calc, l.puntos_total, l.posicion
    from limitados l
    join public.categorias cat on cat.id = l.id_categoria
    left join public.marcas_productos mp on mp.id = l.id_marca_producto
  union all
  select cp.id, cp.codigo, cp.nombre, mp.nombre, cp.id_categoria, cat.nombre, cp.oem, cp.numero_parte,
         cp.condicion, cp.unidad, cp.precio, cp.exento,
         case when v_miembro then cp.costo end,
         case when v_miembro then cp.existencia end,
         cp.controla_inventario,
         (not cp.controla_inventario or cp.existencia > 0),
         case when v_miembro then cp.ubicacion end,
         (select coalesce(i.ruta_miniatura, i.ruta) from public.productos_imagenes i
           where i.id_producto = cp.id order by i.orden, i.id limit 1),
         'complemento',
         case
           when cp.puntos_ajuste >= 10 then 'vehiculo'
           when cp.puntos_ajuste is not null then 'verificar'
         end,
         0::real,
         10000 + cp.posicion
    from complementos cp
    join public.categorias cat on cat.id = cp.id_categoria
    left join public.marcas_productos mp on mp.id = cp.id_marca_producto
   where cp.posicion <= 8
     and (cardinality(v_tokens) > 0 or v_codigo <> '' or p_id_categoria is not null);
end;
$$;

revoke all on function public.buscar_productos(uuid, text, integer, integer, integer, integer, integer, integer) from public;
grant execute on function public.buscar_productos(uuid, text, integer, integer, integer, integer, integer, integer)
  to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 12. Semillas: árbol de categorías, relaciones y marcas de repuestos
--     (on conflict do nothing: no pisa cambios hechos después)
-- -----------------------------------------------------------------------------

create temp table semilla_categorias (
  slug text primary key,
  padre text,
  nombre text not null,
  sinonimos text,
  orden smallint not null
) on commit drop;

insert into semilla_categorias (slug, padre, nombre, sinonimos, orden) values
  -- Nivel 1 -------------------------------------------------------------------
  ('motor',               null, 'Motor', 'maquina', 10),
  ('lubricantes',         null, 'Aceites y fluidos', 'lubricantes, liquidos', 20),
  ('filtros',             null, 'Filtros', 'filtro', 30),
  ('encendido',           null, 'Encendido', 'ignicion', 40),
  ('combustible',         null, 'Combustible e inyección', 'gasolina, diesel, inyeccion', 50),
  ('enfriamiento',        null, 'Enfriamiento', 'refrigeracion, sistema de enfriamiento', 60),
  ('frenos',              null, 'Frenos', 'freno, sistema de frenos', 70),
  ('suspension',          null, 'Suspensión', 'suspencion, tren delantero', 80),
  ('direccion',           null, 'Dirección', 'timon', 90),
  ('transmision',         null, 'Transmisión y embrague', 'tren motriz, tren de manejo, caja', 100),
  ('rodamientos',         null, 'Rodamientos y sellos', 'balineras, retenedores, cojinetes', 110),
  ('electrico',           null, 'Sistema eléctrico', 'electrico, electricidad', 120),
  ('sensores',            null, 'Sensores y electrónica', 'sensor, electronica', 130),
  ('iluminacion',         null, 'Iluminación', 'luces, luz', 140),
  ('aire-acondicionado',  null, 'Aire acondicionado', 'a/c, ac, clima, climatizacion', 150),
  ('escape',              null, 'Escape y emisiones', 'emisiones', 160),
  ('carroceria',          null, 'Carrocería', 'lata, latoneria', 170),
  ('limpiaparabrisas',    null, 'Limpiaparabrisas', 'limpia parabrisas, wipers', 180),
  ('bandas-mangueras',    null, 'Bandas, mangueras y abrazaderas', 'fajas, correas', 190),
  ('llantas-rines',       null, 'Llantas y rines', 'neumaticos, ruedas', 200),
  ('ferreteria',          null, 'Tornillería y fijaciones', 'ferreteria, tornillos, tuercas', 210),
  ('quimicos',            null, 'Químicos y selladores', 'quimicos, grasa y silicon', 220),
  ('accesorios',          null, 'Accesorios', 'accesorio', 230),
  ('herramientas',        null, 'Herramientas y equipo', 'herramienta', 240),
  ('mano-obra',           null, 'Mano de obra', 'servicio, servicios, taller', 900),
  -- Motor ---------------------------------------------------------------------
  ('juntas-motor',        'motor', 'Juntas y empaques', 'empaque, empaques, junta de culata, empaque de culata, kit de empaques, gasket', 10),
  ('culatas',             'motor', 'Culatas y tapas de válvulas', 'cabeza de motor, culata, tapa de valvulas', 20),
  ('pistones-anillos',    'motor', 'Pistones, anillos y camisas', 'aros, rines de piston, camisas, piston', 30),
  ('cojinetes-motor',     'motor', 'Cojinetes de biela y bancada', 'metales, conchas, cojinetes de motor', 40),
  ('valvulas-motor',      'motor', 'Válvulas, guías y resortes', 'valvulas de admision, valvulas de escape, guias', 50),
  ('arbol-levas',         'motor', 'Árbol de levas y balancines', 'leva, taques, buzos, balancines, lifters', 60),
  ('ciguenal-volante',    'motor', 'Cigüeñal y volante', 'volante de motor, flywheel, ciguenal', 70),
  ('distribucion',        'motor', 'Distribución', 'kit de tiempo, faja de tiempo, banda de tiempo, correa de distribucion, cadena de tiempo, timing', 80),
  ('bomba-aceite',        'motor', 'Bomba de aceite y cárter', 'carter, colador de aceite', 90),
  ('soportes-motor',      'motor', 'Soportes de motor', 'bases de motor, soporte de motor, patas de motor', 100),
  ('turbos',              'motor', 'Turbos y sobrealimentación', 'turbo, turbocargador, intercooler', 110),
  ('motores-completos',   'motor', 'Motores completos y medios motores', 'motor completo, medio motor, block, bloque', 120),
  -- Aceites y fluidos ---------------------------------------------------------
  ('aceite-motor',        'lubricantes', 'Aceite de motor', 'aceite, lubricante, 20w50, 15w40, 5w30, 10w30, 5w20, 0w20, sintetico, semisintetico, mineral', 10),
  ('atf',                 'lubricantes', 'Aceite de transmisión automática (ATF)', 'atf, aceite de caja automatica, dexron, mercon, cvt', 20),
  ('aceite-caja-diferencial', 'lubricantes', 'Aceite de caja mecánica y diferencial', 'valvulina, 80w90, 75w90, 85w140, gear oil, aceite de diferencial, aceite de transmision', 30),
  ('liquido-frenos',      'lubricantes', 'Líquido de frenos', 'dot 3, dot 4, brake fluid, liquido de freno', 40),
  ('refrigerante',        'lubricantes', 'Refrigerante y anticongelante', 'coolant, anticongelante, agua de radiador', 50),
  ('aceite-hidraulico',   'lubricantes', 'Aceite hidráulico y de dirección', 'power steering, aceite de timon, hidraulico', 60),
  ('grasas',              'lubricantes', 'Grasas', 'grasa, grasa de balineras, grasa de chasis, grasa de litio', 70),
  ('aditivos',            'lubricantes', 'Aditivos y tratamientos', 'limpia inyectores, aditivo, octanaje, tratamiento, stop leak', 80),
  ('def',                 'lubricantes', 'Líquido reductor de emisiones (AdBlue)', 'adblue, def, urea', 90),
  ('agua-limpiaparabrisas', 'lubricantes', 'Líquido limpiaparabrisas y agua destilada', 'agua destilada, limpiavidrios', 100),
  -- Filtros -------------------------------------------------------------------
  ('filtro-aceite',       'filtros', 'Filtros de aceite', 'filtro de aceite, oil filter, elemento de aceite, cartucho', 10),
  ('filtro-aire',         'filtros', 'Filtros de aire de motor', 'filtro de aire, air filter', 20),
  ('filtro-cabina',       'filtros', 'Filtros de cabina', 'filtro de a/c, filtro de polen, filtro de aire acondicionado, cabin filter', 30),
  ('filtro-combustible',  'filtros', 'Filtros de combustible', 'filtro de gasolina, filtro de diesel, fuel filter', 40),
  ('filtro-transmision',  'filtros', 'Filtros de transmisión', 'filtro de caja, kit de filtro de transmision', 50),
  ('separador-agua',      'filtros', 'Separadores de agua (diésel)', 'trampa de agua, separador, racor', 60),
  -- Encendido -----------------------------------------------------------------
  ('bujias',              'encendido', 'Bujías', 'candelas, candela, spark plug, bujia', 10),
  ('bobinas',             'encendido', 'Bobinas de encendido', 'bobina, coil', 20),
  ('cables-bujia',        'encendido', 'Cables de bujía', 'cables de candela, juego de cables', 30),
  ('distribuidor',        'encendido', 'Distribuidor, tapa y rotor', 'tapa de distribuidor, rotor', 40),
  ('bujias-precalentamiento', 'encendido', 'Bujías de precalentamiento (diésel)', 'glow plug, calentadores', 50),
  -- Combustible e inyección ---------------------------------------------------
  ('inyectores',          'combustible', 'Inyectores', 'inyector, toberas, boquillas', 10),
  ('bomba-combustible',   'combustible', 'Bombas de combustible', 'bomba de gasolina, pila de gasolina, bomba electrica', 20),
  ('cuerpo-aceleracion',  'combustible', 'Cuerpos de aceleración', 'mariposa, throttle, iac', 30),
  ('carburadores',        'combustible', 'Carburadores y kits', 'carburador, kit de carburador', 40),
  ('bomba-inyeccion',     'combustible', 'Bombas de inyección diésel', 'bomba de inyeccion, bomba diesel', 50),
  ('tanque-lineas',       'combustible', 'Tanques, tapones y líneas', 'tanque de gasolina, tapon de gasolina, linea de combustible', 60),
  ('regulador-presion',   'combustible', 'Reguladores de presión', 'regulador de gasolina', 70),
  -- Enfriamiento --------------------------------------------------------------
  ('radiadores',          'enfriamiento', 'Radiadores', 'radiador', 10),
  ('bomba-agua',          'enfriamiento', 'Bombas de agua', 'bomba de agua, water pump', 20),
  ('termostatos',         'enfriamiento', 'Termostatos y tomas de agua', 'termostato, toma de agua', 30),
  ('ventiladores',        'enfriamiento', 'Electroventiladores y fan clutch', 'abanico, ventilador, fan, fan clutch, motor de abanico', 40),
  ('depositos-refrigerante', 'enfriamiento', 'Depósitos de refrigerante', 'deposito de agua, recipiente, reservorio', 50),
  ('mangueras-radiador',  'enfriamiento', 'Mangueras de radiador', 'manguera de agua, manguera superior, manguera inferior', 60),
  ('tapones-radiador',    'enfriamiento', 'Tapones de radiador', 'tapon de radiador', 70),
  -- Frenos --------------------------------------------------------------------
  ('pastillas',           'frenos', 'Pastillas de freno', 'fricciones, balatas, pads, pastilla', 10),
  ('zapatas',             'frenos', 'Zapatas de freno', 'fricciones de tambor, zapata, bandas de freno', 20),
  ('discos',              'frenos', 'Discos de freno', 'rotores, rotor, disco', 30),
  ('tambores',            'frenos', 'Tambores de freno', 'tambor', 40),
  ('calipers',            'frenos', 'Calipers y kits de reparación', 'caliper, mordaza, kit de caliper', 50),
  ('bomba-freno',         'frenos', 'Bombas de freno y booster', 'cilindro maestro, bomba de freno, hidrovac, booster, servofreno', 60),
  ('cilindros-rueda',     'frenos', 'Cilindros de rueda', 'bombin, cilindro de rueda', 70),
  ('mangueras-freno',     'frenos', 'Mangueras y cables de freno', 'manguera de freno, cable de emergencia, freno de mano', 80),
  ('abs',                 'frenos', 'Módulos y sensores ABS', 'abs, sensor abs, modulo abs', 90),
  -- Suspensión ----------------------------------------------------------------
  ('amortiguadores',      'suspension', 'Amortiguadores', 'shocks, amortiguador, strut', 10),
  ('bases-amortiguador',  'suspension', 'Bases y kits de amortiguador', 'base de amortiguador, soporte de amortiguador, strut mount, copela', 20),
  ('resortes',            'suspension', 'Resortes y muelles', 'espirales, muelles, ballestas, resorte', 30),
  ('tijeras',             'suspension', 'Tijeras y brazos de control', 'tijera, brazo de control, bandeja, horquilla', 40),
  ('rotulas',             'suspension', 'Rótulas', 'esfericas, esferica, rotula, ball joint', 50),
  ('bujes',               'suspension', 'Bujes de suspensión', 'hules, bushings, buje de tijera, gomas', 60),
  ('estabilizadora',      'suspension', 'Barra estabilizadora y links', 'linkers, bieletas, link, barra estabilizadora', 70),
  ('munones',             'suspension', 'Muñones y manguetas', 'munon, mangueta', 80),
  ('masas',               'suspension', 'Masas y cubos de rueda', 'masa, cubo, hub', 90),
  -- Dirección -----------------------------------------------------------------
  ('cremallera',          'direccion', 'Cremalleras y cajas de dirección', 'caja de direccion, cremallera', 10),
  ('bomba-direccion',     'direccion', 'Bombas de dirección hidráulica', 'bomba de timon, bomba hidraulica, power steering', 20),
  ('terminales',          'direccion', 'Terminales de dirección', 'puntas de cremallera, terminal, puntas de direccion, tie rod', 30),
  ('axiales',             'direccion', 'Axiales y barras de dirección', 'axial, rotula axial, barra de direccion', 40),
  ('polveras-direccion',  'direccion', 'Polveras de dirección', 'guardapolvo de cremallera, polvera de cremallera', 50),
  ('columna-direccion',   'direccion', 'Columnas y crucetas de dirección', 'cruceta de direccion, columna', 60),
  -- Transmisión y embrague ----------------------------------------------------
  ('embrague',            'transmision', 'Kits de embrague', 'clutch, cloch, disco de clutch, plato de presion, collarin, kit de clutch', 10),
  ('hidraulico-embrague', 'transmision', 'Bombas y cilindros de embrague', 'bomba de clutch, auxiliar de clutch, cilindro esclavo', 20),
  ('caja-automatica',     'transmision', 'Transmisión automática', 'caja automatica, solenoide, cuerpo de valvulas', 30),
  ('caja-mecanica',       'transmision', 'Transmisión mecánica', 'caja mecanica, caja de cambios, sincronizadores', 40),
  ('flechas',             'transmision', 'Flechas y juntas homocinéticas', 'flecha, homocinetica, cv, eje, palier', 50),
  ('polveras-flecha',     'transmision', 'Polveras de flecha', 'botas, guardapolvo de flecha, polvera homocinetica', 60),
  ('cardan',              'transmision', 'Cardanes y crucetas', 'cardan, cruceta, eje cardan', 70),
  ('diferencial',         'transmision', 'Diferenciales', 'corona, pinon', 80),
  ('soportes-transmision', 'transmision', 'Soportes de transmisión', 'base de caja, soporte de caja', 90),
  -- Rodamientos y sellos ------------------------------------------------------
  ('balineras-rueda',     'rodamientos', 'Balineras de rueda', 'rodamientos, cojinetes, balinera, bearing', 10),
  ('retenedores',         'rodamientos', 'Retenedores y sellos', 'sellos, retenedor, oring, seal', 20),
  ('otras-balineras',     'rodamientos', 'Otras balineras y rodamientos', 'balinera de alternador, balinera piloto, rodamiento', 30),
  -- Sistema eléctrico ---------------------------------------------------------
  ('baterias',            'electrico', 'Baterías', 'acumulador, bateria', 10),
  ('alternadores',        'electrico', 'Alternadores y reguladores', 'alternador, regulador de voltaje', 20),
  ('arranque',            'electrico', 'Motores de arranque', 'arrancador, burro de arranque, starter, marcha', 30),
  ('fusibles-reles',      'electrico', 'Fusibles y relés', 'fusible, rele, relay', 40),
  ('cables-conectores',   'electrico', 'Cables, arneses y conectores', 'arnes, conector, terminal de bateria, cable de bateria', 50),
  ('switches',            'electrico', 'Interruptores y switches', 'switch, interruptor, llave de encendido', 60),
  ('motores-electricos',  'electrico', 'Motores de vidrio y actuadores', 'motor de vidrio, alzavidrios, actuador', 70),
  ('bocinas',             'electrico', 'Bocinas', 'pito, claxon, bocina', 80),
  -- Sensores y electrónica ----------------------------------------------------
  ('sensor-oxigeno',      'sensores', 'Sensores de oxígeno', 'sonda lambda, sensor o2, sensor de oxigeno', 10),
  ('sensores-posicion',   'sensores', 'Sensores de posición (CKP, CMP, TPS)', 'ckp, cmp, tps, sensor de ciguenal, sensor de arbol de levas', 20),
  ('maf-map',             'sensores', 'Sensores MAF y MAP', 'maf, map, flujo de aire', 30),
  ('sensores-temperatura', 'sensores', 'Sensores de temperatura y presión', 'bulbo, sensor de temperatura, sensor de presion de aceite, ect', 40),
  ('computadoras',        'sensores', 'Computadoras y módulos', 'ecu, ecm, pcm, computadora, modulo', 50),
  ('otros-sensores',      'sensores', 'Otros sensores', 'sensor de detonacion, knock, sensor de velocidad, vss', 60),
  -- Iluminación ---------------------------------------------------------------
  ('bombillos',           'iluminacion', 'Bombillos', 'focos, bombillas, h4, h7, 9005, 9006, led, halogeno', 10),
  ('faros',               'iluminacion', 'Faros delanteros', 'focos delanteros, farol, faro, headlight', 20),
  ('calaveras',           'iluminacion', 'Calaveras y luces traseras', 'stop, calavera, luz trasera', 30),
  ('neblineras',          'iluminacion', 'Neblineras', 'luces de niebla, antiniebla', 40),
  ('direccionales',       'iluminacion', 'Direccionales y cuartos', 'pidevias, cuartos, direccional', 50),
  -- Aire acondicionado --------------------------------------------------------
  ('compresores-ac',      'aire-acondicionado', 'Compresores de A/C', 'compresor, compresor de aire acondicionado', 10),
  ('condensadores',       'aire-acondicionado', 'Condensadores', 'condensador', 20),
  ('evaporadores',        'aire-acondicionado', 'Evaporadores', 'evaporador', 30),
  ('valvulas-ac',         'aire-acondicionado', 'Válvulas de expansión y secadores', 'filtro deshidratador, secador, valvula de expansion, orificio', 40),
  ('gas-ac',              'aire-acondicionado', 'Gas refrigerante y aceite de A/C', 'gas, r134a, freon, r1234yf, aceite pag', 50),
  ('blower',              'aire-acondicionado', 'Motores de ventilación (blower)', 'blower, motor de ventilacion, resistencia de blower', 60),
  -- Escape y emisiones --------------------------------------------------------
  ('mofles',              'escape', 'Mofles y silenciadores', 'mofle, silenciador, resonador', 10),
  ('catalizadores',       'escape', 'Catalizadores', 'convertidor catalitico, catalizador', 20),
  ('tubos-escape',        'escape', 'Tubos, empaques y soportes de escape', 'flex, junta de escape, gomas de escape, multiple de escape', 30),
  ('egr-pcv',             'escape', 'Válvulas EGR y PCV', 'egr, pcv', 40),
  -- Carrocería ----------------------------------------------------------------
  ('bumpers',             'carroceria', 'Bumpers y parachoques', 'bomper, defensa, parachoque, facia', 10),
  ('guardafangos',        'carroceria', 'Guardafangos y loderas', 'guardafango, lodera, fender', 20),
  ('capos-tapas',         'carroceria', 'Capós, baúles y compuertas', 'capo, cofre, tapa de baul, compuerta', 30),
  ('puertas',             'carroceria', 'Puertas y manijas', 'puerta, manija, manigueta', 40),
  ('espejos',             'carroceria', 'Espejos retrovisores', 'espejo, retrovisor', 50),
  ('vidrios',             'carroceria', 'Vidrios y parabrisas', 'parabrisas, vidrio, ventana', 60),
  ('parrillas',           'carroceria', 'Parrillas', 'rejilla, parrilla, grille', 70),
  ('molduras',            'carroceria', 'Emblemas y molduras', 'emblema, moldura, logo', 80),
  ('chapas',              'carroceria', 'Cerraduras y chapas', 'chapa, cerradura, llavin', 90),
  -- Limpiaparabrisas ----------------------------------------------------------
  ('plumillas',           'limpiaparabrisas', 'Plumillas', 'escobillas, plumas, wiper, plumilla', 10),
  ('brazos-limpia',       'limpiaparabrisas', 'Brazos y motores de limpiaparabrisas', 'brazo de plumilla, motor de limpiaparabrisas', 20),
  ('bombas-limpia',       'limpiaparabrisas', 'Bombas y depósitos de limpiaparabrisas', 'bomba de agua de parabrisas, deposito de limpiaparabrisas', 30),
  -- Bandas, mangueras y abrazaderas -------------------------------------------
  ('bandas',              'bandas-mangueras', 'Bandas de accesorios', 'fajas, faja, correas, banda serpentina, faja de alternador', 10),
  ('tensores-poleas',     'bandas-mangueras', 'Tensores y poleas', 'tensor, polea, polea loca', 20),
  ('mangueras',           'bandas-mangueras', 'Mangueras', 'manguera de vacio, manguera de combustible, manguera de calefaccion', 30),
  ('abrazaderas',         'bandas-mangueras', 'Abrazaderas', 'abrazadera, clamp, cincho', 40),
  -- Llantas y rines -----------------------------------------------------------
  ('llantas',             'llantas-rines', 'Llantas', 'neumaticos, cauchos, llanta', 10),
  ('rines',               'llantas-rines', 'Rines', 'aros, rin', 20),
  ('tuercas-rueda',       'llantas-rines', 'Tuercas y birlos de rueda', 'birlos, esparragos, tuercas de rueda, pernos de rueda', 30),
  ('valvulas-parches',    'llantas-rines', 'Válvulas y parches', 'valvula de llanta, parche, tapon de llanta', 40),
  -- Tornillería ---------------------------------------------------------------
  ('tornillos',           'ferreteria', 'Tornillos y tuercas', 'pernos, tornillo, tuerca', 10),
  ('clips',               'ferreteria', 'Clips y grapas', 'grapas, clip, remaches plasticos', 20),
  ('arandelas',           'ferreteria', 'Arandelas y pasadores', 'roldanas, arandela de carter, pasador', 30),
  -- Químicos y selladores -----------------------------------------------------
  ('selladores',          'quimicos', 'Silicones y selladores', 'silicon, silicona, sellador, formador de empaques', 10),
  ('adhesivos',           'quimicos', 'Pegamentos y epóxicos', 'pegamento, epoxico, loctite', 20),
  ('limpiadores',         'quimicos', 'Limpiadores y desengrasantes', 'desengrasante, limpia carburador, limpia contactos', 30),
  ('estetica',            'quimicos', 'Cuidado estético', 'cera, shampoo, abrillantador', 40),
  -- Accesorios ----------------------------------------------------------------
  ('acc-interior',        'accesorios', 'Accesorios de interior', 'alfombras, forros, cobertores', 10),
  ('acc-exterior',        'accesorios', 'Accesorios de exterior', 'tapones de rin, estribos, micas', 20),
  ('audio-seguridad',     'accesorios', 'Audio y seguridad', 'radio, alarma, camara de reversa', 30),
  ('emergencia',          'accesorios', 'Emergencia y seguridad vial', 'triangulos, cables de puente, extintor, botiquin', 40),
  -- Herramientas y equipo -----------------------------------------------------
  ('herramienta-manual',  'herramientas', 'Herramienta manual', 'llaves, dados, desarmadores', 10),
  ('herramienta-electrica', 'herramientas', 'Herramienta eléctrica y neumática', 'pistola de impacto, taladro, compresor', 20),
  ('diagnostico',         'herramientas', 'Equipo de diagnóstico', 'escaner, multimetro', 30),
  ('equipo-taller',       'herramientas', 'Equipo de taller', 'gata, torres, elevador', 40),
  -- Mano de obra (servicios: no llevan inventario) ----------------------------
  ('mo-diagnostico',      'mano-obra', 'Diagnóstico y escaneo', 'escaneo, diagnostico', 10),
  ('mo-mantenimiento',    'mano-obra', 'Mantenimiento preventivo', 'cambio de aceite, servicio menor, servicio mayor, afinamiento', 20),
  ('mo-motor',            'mano-obra', 'Motor', 'reparacion de motor, overhaul', 30),
  ('mo-frenos',           'mano-obra', 'Frenos', 'cambio de pastillas, rectificado de discos', 40),
  ('mo-suspension',       'mano-obra', 'Suspensión y dirección', 'cambio de amortiguadores', 50),
  ('mo-alineacion',       'mano-obra', 'Alineación y balanceo', 'alineamiento, balanceo', 60),
  ('mo-transmision',      'mano-obra', 'Transmisión y embrague', 'cambio de clutch', 70),
  ('mo-electrico',        'mano-obra', 'Eléctrico y electrónica', 'electricista', 80),
  ('mo-ac',               'mano-obra', 'Aire acondicionado', 'carga de gas', 90),
  ('mo-inyeccion',        'mano-obra', 'Inyección y combustible', 'limpieza de inyectores', 100),
  ('mo-enfriamiento',     'mano-obra', 'Enfriamiento', 'limpieza de radiador', 110),
  ('mo-escape',           'mano-obra', 'Escape', 'soldadura de escape', 120),
  ('mo-carroceria',       'mano-obra', 'Carrocería y pintura', 'enderezado, pintura', 130),
  ('mo-general',          'mano-obra', 'Operaciones generales', 'mano de obra general', 140);

insert into public.categorias (slug, nombre, sinonimos, orden, es_servicio)
select s.slug, s.nombre, s.sinonimos, s.orden, s.slug = 'mano-obra'
  from semilla_categorias s
 where s.padre is null
on conflict (slug) do nothing;

insert into public.categorias (slug, id_padre, nombre, sinonimos, orden)
select s.slug, p.id, s.nombre, s.sinonimos, s.orden
  from semilla_categorias s
  join public.categorias p on p.slug = s.padre
 where s.padre is not null
on conflict (slug) do nothing;

-- Complementos: lo que se suele llevar junto (el trigger crea el par inverso).
insert into public.categorias_relacionadas (id_categoria, id_relacionada, motivo)
select a.id, b.id, r.motivo
  from (values
    ('aceite-motor', 'filtro-aceite', 'Cambio de aceite'),
    ('aceite-motor', 'filtro-aire', 'Servicio de mantenimiento'),
    ('aceite-motor', 'arandelas', 'Arandela del tapón de cárter'),
    ('aceite-motor', 'mo-mantenimiento', 'Cambio de aceite'),
    ('filtro-aceite', 'filtro-aire', 'Servicio de mantenimiento'),
    ('filtro-aceite', 'mo-mantenimiento', 'Cambio de aceite'),
    ('filtro-aire', 'filtro-cabina', 'Servicio de mantenimiento'),
    ('filtro-aire', 'maf-map', 'Admisión de aire'),
    ('filtro-cabina', 'blower', 'Ventilación de cabina'),
    ('filtro-combustible', 'inyectores', 'Sistema de combustible'),
    ('filtro-combustible', 'bomba-combustible', 'Sistema de combustible'),
    ('filtro-combustible', 'separador-agua', 'Diésel'),
    ('atf', 'filtro-transmision', 'Servicio de transmisión'),
    ('atf', 'caja-automatica', 'Servicio de transmisión'),
    ('aceite-caja-diferencial', 'caja-mecanica', 'Servicio de caja'),
    ('aceite-caja-diferencial', 'diferencial', 'Servicio de diferencial'),
    ('pastillas', 'discos', 'Frenos delanteros'),
    ('pastillas', 'liquido-frenos', 'Servicio de frenos'),
    ('pastillas', 'calipers', 'Frenos delanteros'),
    ('pastillas', 'mo-frenos', 'Instalación'),
    ('zapatas', 'tambores', 'Frenos traseros'),
    ('zapatas', 'cilindros-rueda', 'Frenos traseros'),
    ('calipers', 'mangueras-freno', 'Sistema hidráulico de frenos'),
    ('bomba-freno', 'liquido-frenos', 'Purga de frenos'),
    ('mangueras-freno', 'liquido-frenos', 'Purga de frenos'),
    ('discos', 'balineras-rueda', 'Masa delantera'),
    ('amortiguadores', 'bases-amortiguador', 'Cambio de amortiguadores'),
    ('amortiguadores', 'resortes', 'Suspensión'),
    ('amortiguadores', 'mo-suspension', 'Instalación'),
    ('tijeras', 'rotulas', 'Tren delantero'),
    ('tijeras', 'bujes', 'Tren delantero'),
    ('estabilizadora', 'bujes', 'Tren delantero'),
    ('munones', 'rotulas', 'Tren delantero'),
    ('masas', 'balineras-rueda', 'Masa de rueda'),
    ('balineras-rueda', 'retenedores', 'Masa de rueda'),
    ('terminales', 'axiales', 'Dirección'),
    ('terminales', 'mo-alineacion', 'Alinear después del cambio'),
    ('axiales', 'polveras-direccion', 'Dirección'),
    ('cremallera', 'terminales', 'Dirección'),
    ('cremallera', 'aceite-hidraulico', 'Dirección hidráulica'),
    ('bomba-direccion', 'aceite-hidraulico', 'Dirección hidráulica'),
    ('embrague', 'hidraulico-embrague', 'Cambio de clutch'),
    ('embrague', 'ciguenal-volante', 'Rectificar o cambiar volante'),
    ('embrague', 'otras-balineras', 'Balinera piloto'),
    ('embrague', 'mo-transmision', 'Instalación'),
    ('flechas', 'polveras-flecha', 'Flechas'),
    ('flechas', 'grasas', 'Flechas'),
    ('cardan', 'grasas', 'Cardán'),
    ('bujias', 'bobinas', 'Encendido'),
    ('bujias', 'cables-bujia', 'Encendido'),
    ('bujias', 'mo-mantenimiento', 'Afinamiento'),
    ('distribuidor', 'cables-bujia', 'Encendido'),
    ('distribucion', 'bomba-agua', 'Kit de tiempo con bomba de agua'),
    ('distribucion', 'tensores-poleas', 'Kit de tiempo'),
    ('distribucion', 'retenedores', 'Kit de tiempo'),
    ('juntas-motor', 'selladores', 'Armado de motor'),
    ('juntas-motor', 'refrigerante', 'Empaque de culata'),
    ('culatas', 'juntas-motor', 'Armado de motor'),
    ('pistones-anillos', 'cojinetes-motor', 'Reparación de motor'),
    ('pistones-anillos', 'juntas-motor', 'Reparación de motor'),
    ('bomba-aceite', 'juntas-motor', 'Reparación de motor'),
    ('turbos', 'aceite-motor', 'Lubricación del turbo'),
    ('radiadores', 'refrigerante', 'Enfriamiento'),
    ('radiadores', 'mangueras-radiador', 'Enfriamiento'),
    ('radiadores', 'tapones-radiador', 'Enfriamiento'),
    ('ventiladores', 'radiadores', 'Enfriamiento'),
    ('bomba-agua', 'refrigerante', 'Enfriamiento'),
    ('termostatos', 'refrigerante', 'Enfriamiento'),
    ('termostatos', 'bomba-agua', 'Enfriamiento'),
    ('termostatos', 'sensores-temperatura', 'Enfriamiento'),
    ('depositos-refrigerante', 'refrigerante', 'Enfriamiento'),
    ('mangueras-radiador', 'abrazaderas', 'Enfriamiento'),
    ('inyectores', 'aditivos', 'Limpieza de inyección'),
    ('bomba-combustible', 'regulador-presion', 'Sistema de combustible'),
    ('cuerpo-aceleracion', 'limpiadores', 'Limpieza de cuerpo de aceleración'),
    ('baterias', 'alternadores', 'Carga'),
    ('baterias', 'cables-conectores', 'Terminales de batería'),
    ('arranque', 'baterias', 'Arranque'),
    ('alternadores', 'bandas', 'Carga'),
    ('compresores-ac', 'gas-ac', 'Aire acondicionado'),
    ('compresores-ac', 'valvulas-ac', 'Aire acondicionado'),
    ('condensadores', 'gas-ac', 'Aire acondicionado'),
    ('evaporadores', 'valvulas-ac', 'Aire acondicionado'),
    ('gas-ac', 'mo-ac', 'Carga de gas'),
    ('mofles', 'tubos-escape', 'Escape'),
    ('catalizadores', 'sensor-oxigeno', 'Emisiones'),
    ('catalizadores', 'tubos-escape', 'Escape'),
    ('bandas', 'tensores-poleas', 'Bandas'),
    ('mangueras', 'abrazaderas', 'Mangueras'),
    ('plumillas', 'agua-limpiaparabrisas', 'Limpiaparabrisas'),
    ('bombas-limpia', 'agua-limpiaparabrisas', 'Limpiaparabrisas'),
    ('llantas', 'valvulas-parches', 'Llantas'),
    ('llantas', 'mo-alineacion', 'Alinear y balancear'),
    ('rines', 'tuercas-rueda', 'Ruedas'),
    ('faros', 'bombillos', 'Iluminación'),
    ('calaveras', 'bombillos', 'Iluminación'),
    ('neblineras', 'bombillos', 'Iluminación'),
    ('direccionales', 'bombillos', 'Iluminación'),
    ('soportes-motor', 'soportes-transmision', 'Soportes'),
    ('bumpers', 'guardafangos', 'Carrocería'),
    ('bumpers', 'faros', 'Frente del vehículo'),
    ('bumpers', 'molduras', 'Carrocería')
  ) as r (a, b, motivo)
  join public.categorias a on a.slug = r.a
  join public.categorias b on b.slug = r.b
on conflict (id_categoria, id_relacionada) do nothing;

insert into public.marcas_productos (id_empresa, nombre, pais)
select null, m.nombre, m.pais
  from (values
    ('555', 'Japón'), ('ACDELCO', 'Estados Unidos'), ('AISIN', 'Japón'), ('AKEBONO', 'Japón'),
    ('BECK/ARNLEY', 'Estados Unidos'), ('BOSCH', 'Alemania'), ('BREMBO', 'Italia'), ('CASTROL', 'Reino Unido'),
    ('CHAMPION', 'Estados Unidos'), ('CTR', 'Corea del Sur'), ('DAYCO', 'Estados Unidos'), ('DELPHI', 'Reino Unido'),
    ('DENSO', 'Japón'), ('DORMAN', 'Estados Unidos'), ('EXEDY', 'Japón'), ('FEBI BILSTEIN', 'Alemania'),
    ('FEL-PRO', 'Estados Unidos'), ('FRAM', 'Estados Unidos'), ('GATES', 'Estados Unidos'), ('GMB', 'Japón'),
    ('HELLA', 'Alemania'), ('HITACHI', 'Japón'), ('KOYO', 'Japón'), ('KYB', 'Japón'),
    ('LTH', 'México'), ('LUK', 'Alemania'), ('MAHLE', 'Alemania'), ('MANN-FILTER', 'Alemania'),
    ('MOBIL', 'Estados Unidos'), ('MONROE', 'Estados Unidos'), ('MOOG', 'Estados Unidos'), ('MOPAR', 'Estados Unidos'),
    ('MOTORCRAFT', 'Estados Unidos'), ('NGK', 'Japón'), ('NSK', 'Japón'), ('NTN', 'Japón'),
    ('OSRAM', 'Alemania'), ('PENNZOIL', 'Estados Unidos'), ('PHILIPS', 'Países Bajos'), ('RAYBESTOS', 'Estados Unidos'),
    ('SACHS', 'Alemania'), ('SAKURA', 'Malasia'), ('SHELL', 'Reino Unido'), ('SKF', 'Suecia'),
    ('STANDARD', 'Estados Unidos'), ('TIMKEN', 'Estados Unidos'), ('TOKICO', 'Japón'), ('TOTAL', 'Francia'),
    ('TRW', 'Alemania'), ('VALEO', 'Francia'), ('VALVOLINE', 'Estados Unidos'), ('VICTOR REINZ', 'Alemania'),
    ('WAGNER', 'Estados Unidos'), ('WIX', 'Estados Unidos'), ('YUASA', 'Japón'),
    ('ORIGINAL DE AGENCIA', null), ('SIN MARCA', null)
  ) as m (nombre, pais)
where not exists (select 1 from public.marcas_productos x where x.id_empresa is null and x.nombre = m.nombre);

-- -----------------------------------------------------------------------------
-- 13. Documentación en la base
-- -----------------------------------------------------------------------------

comment on table public.categorias is 'Árbol global de categorías de productos (máx. 3 niveles). Sinónimos de mostrador alimentan la búsqueda.';
comment on table public.categorias_relacionadas is 'Complementos: pares simétricos de categorías para recomendar productos.';
comment on table public.marcas_productos is 'Marcas de repuestos. id_empresa null = global; si no, propia de esa empresa.';
comment on table public.productos is 'Productos y servicios por empresa. precio y costo sin ISV; utilidad y margen se calculan.';
comment on column public.productos.referencias is 'Otros números de parte / equivalencias, separados por coma.';
comment on column public.productos.texto_busqueda is 'Generado por trigger: nombre, marca, categoría (con sinónimos) y códigos, en forma fonética (wp_fonetico).';
comment on table public.movimientos_inventario is 'Kardex. Lo escribe solo el trigger de productos.existencia.';
comment on table public.productos_imagenes is 'Fotos en Storage (bucket productos): <empresa>/<producto>/<archivo>.';
comment on table public.productos_compatibilidades is 'Producto ↔ vehículo en el nivel elegido; los ancestros se completan solos.';
comment on function public.buscar_productos(uuid, text, integer, integer, integer, integer, integer, integer) is
  'Búsqueda de mostrador y catálogo: texto, códigos, vehículo, generales y complementos.';

commit;
