-- =============================================================================
-- 0005 · Ventas: clientes, CAI, carritos, cotizaciones y facturas
-- -----------------------------------------------------------------------------
-- ESTADO: YA APLICADA (2026-09-28)
-- Idempotente y atómica. Requiere 0004.
--
-- Flujo: un carrito (borrador editable, con vehículo y cliente) se convierte en
-- una COTIZACIÓN (COT-000001) o en una FACTURA con CAI (000-001-01-00000001).
-- Los documentos emitidos son inmutables: se anulan, nunca se borran.
--
-- Qué crea:
--   · empresas.descuento_maximo_vendedor   Tope de descuento para vendedores.
--   · clientes                Por empresa (RTN opcional, único por empresa).
--   · cai                     Rangos autorizados por el SAR (dueño/admin).
--   · carritos, carritos_lineas
--   · documentos, documentos_lineas        Cotizaciones y facturas emitidas.
--   · correlativos            Numeración interna por empresa (cotizaciones).
--   · emitir_documento()      Carrito → cotización o factura (numeración con
--                             bloqueo, totales en la base, descuenta existencia).
--   · anular_documento()      Anula y, si era factura, devuelve la existencia.
--   · carrito_desde_documento()  Reabre una cotización/factura como carrito.
--   · Vistas v_clientes, v_cai, v_carritos, v_carritos_lineas, v_documentos,
--     v_documentos_lineas.
--
-- Reglas fiscales usadas (ver docs/negocio.md §3.5, marcadas «a verificar»):
--   · Precios sin ISV; ISV 15 % sobre lo gravado; exento aparte.
--   · Número de factura EEE-PPP-TT-NNNNNNNN, correlativo sin huecos dentro del
--     rango del CAI; no se emite fuera de rango ni después de la fecha límite.
-- =============================================================================

begin;

create or replace function pg_temp.agregar_restriccion(tabla regclass, nombre text, definicion text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = tabla and conname = nombre) then
    execute format('alter table %s add constraint %I %s', tabla, nombre, definicion);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Empresa: tope de descuento para vendedores
-- -----------------------------------------------------------------------------

alter table public.empresas add column if not exists descuento_maximo_vendedor numeric(5, 2) not null default 10;

select pg_temp.agregar_restriccion('public.empresas', 'empresas_descuento_maximo_check',
  $$check (descuento_maximo_vendedor between 0 and 100)$$);

grant update (descuento_maximo_vendedor) on public.empresas to authenticated;

-- -----------------------------------------------------------------------------
-- 2. Clientes
-- -----------------------------------------------------------------------------

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  nombre text not null,
  rtn text,
  telefono text,
  correo text,
  direccion text,
  notas text,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid()
);

create index if not exists clientes_id_empresa_idx on public.clientes (id_empresa, nombre);
create index if not exists clientes_creado_por_idx on public.clientes (creado_por);
create unique index if not exists clientes_rtn_key on public.clientes (id_empresa, rtn) where rtn is not null;

select pg_temp.agregar_restriccion('public.clientes', 'clientes_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 160)$$);
select pg_temp.agregar_restriccion('public.clientes', 'clientes_rtn_check',
  $$check (rtn is null or rtn ~ '^\d{14}$')$$);
select pg_temp.agregar_restriccion('public.clientes', 'clientes_correo_check',
  $$check (correo is null or correo ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')$$);

create or replace function public.tg_normalizar_cliente()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un cliente.';
  end if;
  new.nombre := upper(regexp_replace(btrim(new.nombre), '\s+', ' ', 'g'));
  new.rtn := nullif(regexp_replace(coalesce(new.rtn, ''), '\D', '', 'g'), '');
  new.telefono := nullif(btrim(new.telefono), '');
  new.correo := nullif(lower(btrim(new.correo)), '');
  new.direccion := nullif(btrim(new.direccion), '');
  new.notas := nullif(btrim(new.notas), '');
  return new;
end;
$$;

create or replace trigger a_normalizar
  before insert or update on public.clientes
  for each row execute function public.tg_normalizar_cliente();

-- -----------------------------------------------------------------------------
-- 3. CAI (Código de Autorización de Impresión)
-- -----------------------------------------------------------------------------

create table if not exists public.cai (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  cai text not null,
  tipo_documento text not null default '01',
  establecimiento text not null default '000',
  punto_emision text not null default '001',
  rango_inicial integer not null,
  rango_final integer not null,
  siguiente integer not null,
  fecha_limite date not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid()
);

create index if not exists cai_id_empresa_idx on public.cai (id_empresa, tipo_documento, activo);
create index if not exists cai_creado_por_idx on public.cai (creado_por);
create unique index if not exists cai_codigo_key on public.cai (id_empresa, cai);

select pg_temp.agregar_restriccion('public.cai', 'cai_formato_check',
  $$check (cai ~ '^[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{6}-[0-9A-F]{2}$')$$);
select pg_temp.agregar_restriccion('public.cai', 'cai_codigos_check',
  $$check (tipo_documento ~ '^\d{2}$' and establecimiento ~ '^\d{3}$' and punto_emision ~ '^\d{3}$')$$);
select pg_temp.agregar_restriccion('public.cai', 'cai_rango_check',
  $$check (rango_inicial >= 1 and rango_final >= rango_inicial and rango_final <= 99999999
           and siguiente between rango_inicial and rango_final + 1)$$);

create or replace function public.tg_cai()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_limpio text;
begin
  if tg_op = 'INSERT' then
    v_limpio := upper(regexp_replace(coalesce(new.cai, ''), '[^0-9A-Fa-f]', '', 'g'));
    if char_length(v_limpio) = 32 then
      new.cai := substr(v_limpio, 1, 6) || '-' || substr(v_limpio, 7, 6) || '-' || substr(v_limpio, 13, 6) || '-'
              || substr(v_limpio, 19, 6) || '-' || substr(v_limpio, 25, 6) || '-' || substr(v_limpio, 31, 2);
    else
      new.cai := upper(btrim(new.cai));
    end if;
    new.establecimiento := lpad(btrim(new.establecimiento), 3, '0');
    new.punto_emision := lpad(btrim(new.punto_emision), 3, '0');
    new.tipo_documento := lpad(btrim(new.tipo_documento), 2, '0');
    new.siguiente := coalesce(new.siguiente, new.rango_inicial);
  elsif exists (select 1 from public.documentos d where d.id_cai = old.id) and (
          new.cai <> old.cai or new.establecimiento <> old.establecimiento
          or new.punto_emision <> old.punto_emision or new.tipo_documento <> old.tipo_documento
          or new.rango_inicial <> old.rango_inicial or new.rango_final <> old.rango_final
          or new.fecha_limite <> old.fecha_limite or new.id_empresa <> old.id_empresa
          or new.siguiente < old.siguiente) then
    raise exception 'Este CAI ya tiene facturas emitidas: solo se puede activar o desactivar.';
  end if;
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- 4. Carritos
-- -----------------------------------------------------------------------------

create table if not exists public.carritos (
  id uuid primary key default gen_random_uuid(),
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  nombre text,
  id_cliente bigint references public.clientes (id) on delete set null,
  cliente_nombre text,
  cliente_rtn text,
  cliente_telefono text,
  id_marca integer references public.marcas (id) on delete set null,
  id_modelo integer references public.modelos (id) on delete set null,
  id_modelo_anio integer references public.modelos_anios (id) on delete set null,
  id_especificacion integer references public.especificaciones (id) on delete set null,
  vehiculo text,
  descuento_pct numeric(6, 3) not null default 0,
  notas text,
  estado text not null default 'abierto',
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  actualizado_en timestamptz not null default now()
);

create index if not exists carritos_empresa_estado_idx on public.carritos (id_empresa, estado, actualizado_en desc);
create index if not exists carritos_id_cliente_idx on public.carritos (id_cliente);
create index if not exists carritos_creado_por_idx on public.carritos (creado_por);
create index if not exists carritos_id_marca_idx on public.carritos (id_marca);
create index if not exists carritos_id_modelo_idx on public.carritos (id_modelo);
create index if not exists carritos_id_modelo_anio_idx on public.carritos (id_modelo_anio);
create index if not exists carritos_id_especificacion_idx on public.carritos (id_especificacion);

select pg_temp.agregar_restriccion('public.carritos', 'carritos_estado_check',
  $$check (estado in ('abierto', 'cerrado'))$$);
select pg_temp.agregar_restriccion('public.carritos', 'carritos_descuento_check',
  $$check (descuento_pct between 0 and 100)$$);
select pg_temp.agregar_restriccion('public.carritos', 'carritos_rtn_check',
  $$check (cliente_rtn is null or cliente_rtn ~ '^\d{14}$')$$);

create table if not exists public.carritos_lineas (
  id bigint generated by default as identity primary key,
  id_carrito uuid not null references public.carritos (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint references public.productos (id) on delete set null,
  codigo text,
  descripcion text not null,
  cantidad numeric(12, 2) not null default 1,
  precio numeric(14, 2) not null default 0,
  descuento_pct numeric(6, 3) not null default 0,
  exento boolean not null default false,
  orden integer not null default 0,
  creado_en timestamptz not null default now()
);

create index if not exists carritos_lineas_carrito_idx on public.carritos_lineas (id_carrito, orden);
create index if not exists carritos_lineas_id_producto_idx on public.carritos_lineas (id_producto);
create index if not exists carritos_lineas_id_empresa_idx on public.carritos_lineas (id_empresa);

select pg_temp.agregar_restriccion('public.carritos_lineas', 'carritos_lineas_montos_check',
  $$check (cantidad > 0 and precio >= 0 and descuento_pct between 0 and 100)$$);
select pg_temp.agregar_restriccion('public.carritos_lineas', 'carritos_lineas_descripcion_check',
  $$check (btrim(descripcion) <> '' and char_length(descripcion) <= 240)$$);

-- Normaliza el carrito, arma el texto del vehículo y aplica el tope de descuento.
create or replace function public.tg_carritos()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_tope numeric;
  v_cli record;
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un carrito.';
  end if;
  if tg_op = 'UPDATE' and old.estado = 'cerrado' and new.estado = 'cerrado' then
    raise exception 'Este carrito ya se cerró. Abrí uno nuevo.';
  end if;

  -- Cliente elegido: copia sus datos si no se escribieron otros.
  if new.id_cliente is not null
     and (tg_op = 'INSERT' or new.id_cliente is distinct from old.id_cliente) then
    select c.nombre, c.rtn, c.telefono into v_cli
      from public.clientes c where c.id = new.id_cliente and c.id_empresa = new.id_empresa;
    if not found then
      raise exception 'El cliente no existe.';
    end if;
    new.cliente_nombre := v_cli.nombre;
    new.cliente_rtn := v_cli.rtn;
    new.cliente_telefono := v_cli.telefono;
  end if;

  new.nombre := nullif(btrim(new.nombre), '');
  new.cliente_nombre := nullif(upper(regexp_replace(btrim(new.cliente_nombre), '\s+', ' ', 'g')), '');
  new.cliente_rtn := nullif(regexp_replace(coalesce(new.cliente_rtn, ''), '\D', '', 'g'), '');
  new.cliente_telefono := nullif(btrim(new.cliente_telefono), '');
  new.notas := nullif(btrim(new.notas), '');

  -- Vehículo: completa ancestros y arma el texto «TOYOTA COROLLA 2005 · 1.8 L».
  if new.id_especificacion is not null then
    select e.id_modelo_anio into new.id_modelo_anio from public.especificaciones e where e.id = new.id_especificacion;
  end if;
  if new.id_modelo_anio is not null then
    select ya.id_modelo into new.id_modelo from public.modelos_anios ya where ya.id = new.id_modelo_anio;
  end if;
  if new.id_modelo is not null then
    select mo.id_marca into new.id_marca from public.modelos mo where mo.id = new.id_modelo;
  end if;
  select nullif(concat_ws(' ', ma.marca, mo.modelo, ya.anio::text,
                          case when e.id is not null then '· ' || round(e.motor_cc / 1000.0, 1)::text || ' L'
                               || coalesce(' ' || e.motor_numero, '') end), '')
    into new.vehiculo
    from (select 1) x
    left join public.marcas ma on ma.id = new.id_marca
    left join public.modelos mo on mo.id = new.id_modelo
    left join public.modelos_anios ya on ya.id = new.id_modelo_anio
    left join public.especificaciones e on e.id = new.id_especificacion;

  if new.descuento_pct > 0
     and (tg_op = 'INSERT' or new.descuento_pct <> old.descuento_pct)
     and auth.uid() is not null
     and coalesce(current_setting('wp.copia_documento', true), '') <> 'si'
     and not public.tiene_rol(new.id_empresa, array['dueno', 'admin']) then
    select e.descuento_maximo_vendedor into v_tope from public.empresas e where e.id = new.id_empresa;
    if new.descuento_pct > v_tope then
      raise exception 'Tu rol permite hasta % %% de descuento.', rtrim(to_char(v_tope, 'FM990.##'), '.');
    end if;
  end if;

  new.actualizado_en := now();
  return new;
end;
$$;

create or replace trigger a_preparar
  before insert or update on public.carritos
  for each row execute function public.tg_carritos();

create or replace function public.tg_carritos_lineas()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_carrito record;
  v_tope numeric;
begin
  -- Se borró el producto (FK «set null»): la línea conserva su descripción.
  if tg_op = 'UPDATE' and new.id_producto is null and old.id_producto is not null
     and (new.cantidad, new.precio, new.descuento_pct, new.descripcion)
         is not distinct from (old.cantidad, old.precio, old.descuento_pct, old.descripcion) then
    return new;
  end if;

  select c.id_empresa, c.estado into v_carrito from public.carritos c where c.id = new.id_carrito;
  if v_carrito.estado is distinct from 'abierto' then
    raise exception 'Este carrito ya se cerró. Abrí uno nuevo.';
  end if;
  new.id_empresa := v_carrito.id_empresa;
  new.descripcion := regexp_replace(btrim(new.descripcion), '\s+', ' ', 'g');
  new.codigo := nullif(btrim(new.codigo), '');

  if new.id_producto is not null and (tg_op = 'INSERT' or new.id_producto is distinct from old.id_producto) then
    if not exists (select 1 from public.productos p where p.id = new.id_producto and p.id_empresa = new.id_empresa) then
      raise exception 'El producto no existe.';
    end if;
  end if;

  if new.descuento_pct > 0
     and (tg_op = 'INSERT' or new.descuento_pct <> old.descuento_pct)
     and auth.uid() is not null
     and coalesce(current_setting('wp.copia_documento', true), '') <> 'si'
     and not public.tiene_rol(new.id_empresa, array['dueno', 'admin']) then
    select e.descuento_maximo_vendedor into v_tope from public.empresas e where e.id = new.id_empresa;
    if new.descuento_pct > v_tope then
      raise exception 'Tu rol permite hasta % %% de descuento.', rtrim(to_char(v_tope, 'FM990.##'), '.');
    end if;
  end if;

  update public.carritos set actualizado_en = now() where id = new.id_carrito;
  return new;
end;
$$;

create or replace trigger a_preparar
  before insert or update on public.carritos_lineas
  for each row execute function public.tg_carritos_lineas();

-- -----------------------------------------------------------------------------
-- 5. Documentos emitidos (cotizaciones y facturas)
-- -----------------------------------------------------------------------------

create table if not exists public.correlativos (
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  tipo text not null,
  siguiente integer not null default 1,
  constraint correlativos_pkey primary key (id_empresa, tipo)
);

create table if not exists public.documentos (
  id uuid primary key default gen_random_uuid(),
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  tipo text not null,
  numero text not null,
  correlativo integer not null,
  fecha timestamptz not null default now(),
  vence date,
  -- CAI (solo facturas)
  id_cai bigint references public.cai (id),
  cai text,
  cai_rango text,
  cai_fecha_limite date,
  -- Emisor y comprador (copias al momento de emitir)
  emisor jsonb not null default '{}'::jsonb,
  id_cliente bigint references public.clientes (id) on delete set null,
  cliente_nombre text not null,
  cliente_rtn text,
  cliente_telefono text,
  vehiculo text,
  -- Totales (lempiras)
  subtotal numeric(14, 2) not null,
  descuento numeric(14, 2) not null,
  importe_exento numeric(14, 2) not null,
  importe_gravado numeric(14, 2) not null,
  isv numeric(14, 2) not null,
  total numeric(14, 2) not null,
  notas text,
  estado text not null default 'emitido',
  anulado_en timestamptz,
  anulado_por uuid references public.usuarios (id) on delete set null,
  motivo_anulacion text,
  id_carrito uuid references public.carritos (id) on delete set null,
  id_documento_origen uuid references public.documentos (id) on delete set null,
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now(),
  constraint documentos_numero_key unique (id_empresa, tipo, numero)
);

create index if not exists documentos_empresa_fecha_idx on public.documentos (id_empresa, fecha desc);
create index if not exists documentos_id_cai_idx on public.documentos (id_cai);
create index if not exists documentos_id_cliente_idx on public.documentos (id_cliente);
create index if not exists documentos_id_carrito_idx on public.documentos (id_carrito);
create index if not exists documentos_id_documento_origen_idx on public.documentos (id_documento_origen);
create index if not exists documentos_creado_por_idx on public.documentos (creado_por);
create index if not exists documentos_anulado_por_idx on public.documentos (anulado_por);

select pg_temp.agregar_restriccion('public.documentos', 'documentos_tipo_check',
  $$check (tipo in ('cotizacion', 'factura'))$$);
select pg_temp.agregar_restriccion('public.documentos', 'documentos_estado_check',
  $$check (estado in ('emitido', 'anulado'))$$);

create table if not exists public.documentos_lineas (
  id bigint generated by default as identity primary key,
  id_documento uuid not null references public.documentos (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  -- Un producto con ventas no se borra: se desactiva.
  id_producto bigint references public.productos (id),
  codigo text,
  descripcion text not null,
  cantidad numeric(12, 2) not null,
  precio numeric(14, 2) not null,
  descuento_pct numeric(6, 3) not null,
  descuento numeric(14, 2) not null,
  exento boolean not null,
  total numeric(14, 2) not null,
  costo numeric(14, 2),
  controla_inventario boolean not null default false,
  orden integer not null default 0
);

create index if not exists documentos_lineas_documento_idx on public.documentos_lineas (id_documento, orden);
create index if not exists documentos_lineas_id_producto_idx on public.documentos_lineas (id_producto);
create index if not exists documentos_lineas_id_empresa_idx on public.documentos_lineas (id_empresa);

create or replace trigger a_preparar
  before insert or update on public.cai
  for each row execute function public.tg_cai();

-- -----------------------------------------------------------------------------
-- 6. Emisión
-- -----------------------------------------------------------------------------

-- Emite una cotización o factura a partir de un carrito abierto.
create or replace function public.emitir_documento(p_carrito uuid, p_tipo text, p_vence date default null)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_carrito public.carritos;
  v_empresa public.empresas;
  v_cai public.cai;
  v_hoy date := (now() at time zone 'America/Tegucigalpa')::date;
  v_correlativo integer;
  v_numero text;
  v_doc uuid;
  v_linea record;
  v_subtotal numeric := 0;
  v_descuento numeric := 0;
  v_exento numeric := 0;
  v_gravado numeric := 0;
  v_isv numeric;
  v_orden integer := 0;
begin
  if p_tipo not in ('cotizacion', 'factura') then
    raise exception 'Tipo de documento no válido.';
  end if;

  select * into v_carrito from public.carritos where id = p_carrito for update;
  if not found or not public.es_miembro(v_carrito.id_empresa) then
    raise exception 'El carrito no existe.';
  end if;
  if v_carrito.estado <> 'abierto' then
    raise exception 'Este carrito ya se cerró.';
  end if;
  if not exists (select 1 from public.carritos_lineas where id_carrito = p_carrito) then
    raise exception 'El carrito está vacío.';
  end if;

  select * into v_empresa from public.empresas where id = v_carrito.id_empresa;

  if p_tipo = 'factura' then
    if v_empresa.rtn is null or v_empresa.razon_social is null then
      raise exception 'Para facturar, completá la razón social y el RTN del taller (módulo Taller).';
    end if;
    select * into v_cai
      from public.cai
     where id_empresa = v_carrito.id_empresa and tipo_documento = '01' and activo
       and siguiente <= rango_final and fecha_limite >= v_hoy
     order by fecha_limite, id
     limit 1
     for update;
    if not found then
      raise exception 'No hay un CAI vigente con números disponibles. Registrá uno en Ventas › CAI.';
    end if;
    v_correlativo := v_cai.siguiente;
    v_numero := v_cai.establecimiento || '-' || v_cai.punto_emision || '-' || v_cai.tipo_documento || '-'
                || lpad(v_correlativo::text, 8, '0');
    update public.cai set siguiente = siguiente + 1 where id = v_cai.id;
  else
    insert into public.correlativos (id_empresa, tipo) values (v_carrito.id_empresa, p_tipo)
    on conflict (id_empresa, tipo) do nothing;
    update public.correlativos set siguiente = siguiente + 1
     where id_empresa = v_carrito.id_empresa and tipo = p_tipo
    returning siguiente - 1 into v_correlativo;
    v_numero := 'COT-' || lpad(v_correlativo::text, 6, '0');
  end if;

  insert into public.documentos (
    id_empresa, tipo, numero, correlativo, vence,
    id_cai, cai, cai_rango, cai_fecha_limite, emisor,
    id_cliente, cliente_nombre, cliente_rtn, cliente_telefono, vehiculo,
    subtotal, descuento, importe_exento, importe_gravado, isv, total,
    notas, id_carrito
  ) values (
    v_carrito.id_empresa, p_tipo, v_numero, v_correlativo,
    case when p_tipo = 'cotizacion' then coalesce(p_vence, v_hoy + 15) end,
    v_cai.id, v_cai.cai,
    case when v_cai.id is not null then
      v_cai.establecimiento || '-' || v_cai.punto_emision || '-' || v_cai.tipo_documento || '-' || lpad(v_cai.rango_inicial::text, 8, '0')
      || ' al ' ||
      v_cai.establecimiento || '-' || v_cai.punto_emision || '-' || v_cai.tipo_documento || '-' || lpad(v_cai.rango_final::text, 8, '0')
    end,
    v_cai.fecha_limite,
    jsonb_build_object(
      'nombre', v_empresa.nombre, 'razon_social', v_empresa.razon_social, 'rtn', v_empresa.rtn,
      'telefono', v_empresa.telefono, 'correo', v_empresa.correo, 'direccion', v_empresa.direccion
    ),
    v_carrito.id_cliente,
    coalesce(v_carrito.cliente_nombre, 'CONSUMIDOR FINAL'),
    v_carrito.cliente_rtn, v_carrito.cliente_telefono, v_carrito.vehiculo,
    0, 0, 0, 0, 0, 0,
    v_carrito.notas, v_carrito.id
  )
  returning id into v_doc;

  -- Líneas: el descuento general se combina con el de cada línea.
  for v_linea in
    select l.*, p.costo as costo_producto, coalesce(p.controla_inventario, false) as inventariable
      from public.carritos_lineas l
      left join public.productos p on p.id = l.id_producto
     where l.id_carrito = p_carrito
     order by l.orden, l.id
  loop
    declare
      v_bruto numeric := round(v_linea.cantidad * v_linea.precio, 2);
      v_neto numeric := round(v_bruto * (1 - v_linea.descuento_pct / 100) * (1 - v_carrito.descuento_pct / 100), 2);
    begin
      v_orden := v_orden + 1;
      insert into public.documentos_lineas (
        id_documento, id_empresa, id_producto, codigo, descripcion, cantidad, precio,
        descuento_pct, descuento, exento, total, costo, controla_inventario, orden
      ) values (
        v_doc, v_carrito.id_empresa, v_linea.id_producto, v_linea.codigo, v_linea.descripcion,
        v_linea.cantidad, v_linea.precio,
        round((1 - (1 - v_linea.descuento_pct / 100) * (1 - v_carrito.descuento_pct / 100)) * 100, 3),
        v_bruto - v_neto, v_linea.exento, v_neto, v_linea.costo_producto, v_linea.inventariable, v_orden
      );
      v_subtotal := v_subtotal + v_bruto;
      v_descuento := v_descuento + (v_bruto - v_neto);
      if v_linea.exento then
        v_exento := v_exento + v_neto;
      else
        v_gravado := v_gravado + v_neto;
      end if;
    end;
  end loop;

  v_isv := round(v_gravado * 0.15, 2);
  update public.documentos
     set subtotal = v_subtotal, descuento = v_descuento, importe_exento = v_exento,
         importe_gravado = v_gravado, isv = v_isv, total = v_exento + v_gravado + v_isv
   where id = v_doc;

  -- Factura: descuenta existencias (queda en el kardex como venta).
  if p_tipo = 'factura' then
    perform set_config('wp.movimiento_tipo', 'venta', true);
    perform set_config('wp.movimiento_ref', v_numero, true);
    update public.productos p
       set existencia = p.existencia - x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.documentos_lineas
             where id_documento = v_doc and id_producto is not null and controla_inventario
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;

  update public.carritos set estado = 'cerrado', actualizado_en = now() where id = p_carrito;
  return v_doc;
end;
$$;

-- Anula un documento. Si era factura, devuelve la existencia.
create or replace function public.anular_documento(p_documento uuid, p_motivo text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_doc public.documentos;
begin
  select * into v_doc from public.documentos where id = p_documento for update;
  if not found or not public.es_miembro(v_doc.id_empresa) then
    raise exception 'El documento no existe.';
  end if;
  if not public.tiene_rol(v_doc.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden anular documentos.';
  end if;
  if v_doc.estado = 'anulado' then
    raise exception 'El documento ya está anulado.';
  end if;
  if nullif(btrim(p_motivo), '') is null then
    raise exception 'Escribí el motivo de la anulación.';
  end if;

  update public.documentos
     set estado = 'anulado', anulado_en = now(), anulado_por = auth.uid(), motivo_anulacion = btrim(p_motivo)
   where id = p_documento;

  if v_doc.tipo = 'factura' then
    perform set_config('wp.movimiento_tipo', 'anulacion', true);
    perform set_config('wp.movimiento_ref', v_doc.numero, true);
    update public.productos p
       set existencia = p.existencia + x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.documentos_lineas
             where id_documento = p_documento and id_producto is not null and controla_inventario
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;
end;
$$;

-- Nuevo carrito abierto con el cliente, vehículo y líneas de un documento
-- (convertir una cotización en factura, repetir una venta).
create or replace function public.carrito_desde_documento(p_documento uuid)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  v_doc public.documentos;
  v_carrito uuid;
  v_origen public.carritos;
begin
  select * into v_doc from public.documentos where id = p_documento;
  if not found then
    raise exception 'El documento no existe.';
  end if;
  select * into v_origen from public.carritos where id = v_doc.id_carrito;
  -- Los descuentos ya se aprobaron al emitir el documento: se copian tal cual.
  perform set_config('wp.copia_documento', 'si', true);

  insert into public.carritos (id_empresa, nombre, id_cliente, cliente_nombre, cliente_rtn, cliente_telefono,
                               id_marca, id_modelo, id_modelo_anio, id_especificacion, notas)
  values (v_doc.id_empresa, v_doc.numero, null,
          nullif(v_doc.cliente_nombre, 'CONSUMIDOR FINAL'), v_doc.cliente_rtn, v_doc.cliente_telefono,
          v_origen.id_marca, v_origen.id_modelo, v_origen.id_modelo_anio, v_origen.id_especificacion, v_doc.notas)
  returning id into v_carrito;

  update public.carritos set id_cliente = v_doc.id_cliente where id = v_carrito and v_doc.id_cliente is not null
    and exists (select 1 from public.clientes c where c.id = v_doc.id_cliente);

  insert into public.carritos_lineas (id_carrito, id_producto, codigo, descripcion, cantidad, precio, descuento_pct, exento, orden)
  select v_carrito, l.id_producto, l.codigo, l.descripcion, l.cantidad, l.precio, l.descuento_pct, l.exento, l.orden
    from public.documentos_lineas l
   where l.id_documento = p_documento
   order by l.orden;

  perform set_config('wp.copia_documento', '', true);
  return v_carrito;
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Permisos y RLS
-- -----------------------------------------------------------------------------

revoke all on public.clientes, public.cai, public.carritos, public.carritos_lineas,
              public.correlativos, public.documentos, public.documentos_lineas
  from anon, authenticated;

grant select, insert, delete on public.clientes to authenticated;
grant update (nombre, rtn, telefono, correo, direccion, notas, activo) on public.clientes to authenticated;
grant select, insert, delete on public.cai to authenticated;
grant update (cai, tipo_documento, establecimiento, punto_emision, rango_inicial, rango_final,
              siguiente, fecha_limite, activo)
  on public.cai to authenticated;
grant select, insert, delete on public.carritos to authenticated;
grant update (nombre, id_cliente, cliente_nombre, cliente_rtn, cliente_telefono, id_marca, id_modelo,
              id_modelo_anio, id_especificacion, descuento_pct, notas, actualizado_en)
  on public.carritos to authenticated;
grant select, insert, delete on public.carritos_lineas to authenticated;
grant update (cantidad, precio, descuento_pct, descripcion, orden) on public.carritos_lineas to authenticated;
grant select on public.documentos, public.documentos_lineas to authenticated;

alter table public.clientes enable row level security;
alter table public.cai enable row level security;
alter table public.carritos enable row level security;
alter table public.carritos_lineas enable row level security;
alter table public.correlativos enable row level security;
alter table public.documentos enable row level security;
alter table public.documentos_lineas enable row level security;

-- Clientes: todos los miembros los registran y editan; borran dueño/admin.
drop policy if exists empresa_lectura on public.clientes;
create policy empresa_lectura on public.clientes
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists miembros_alta on public.clientes;
create policy miembros_alta on public.clientes
  for insert to authenticated with check (public.es_miembro(id_empresa));
drop policy if exists miembros_edicion on public.clientes;
create policy miembros_edicion on public.clientes
  for update to authenticated using (public.es_miembro(id_empresa)) with check (public.es_miembro(id_empresa));
drop policy if exists admin_baja on public.clientes;
create policy admin_baja on public.clientes
  for delete to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));

-- CAI: lo ven los miembros; lo administran dueño/admin. Se borra solo sin facturas (FK).
drop policy if exists empresa_lectura on public.cai;
create policy empresa_lectura on public.cai
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists empresa_escritura on public.cai;
create policy empresa_escritura on public.cai
  for all to authenticated
  using (public.tiene_rol(id_empresa, array['dueno', 'admin']))
  with check (public.tiene_rol(id_empresa, array['dueno', 'admin']));

-- Carritos: cualquier miembro (mostrador).
drop policy if exists miembros_todo on public.carritos;
create policy miembros_todo on public.carritos
  for all to authenticated
  using (public.es_miembro(id_empresa))
  with check (public.es_miembro(id_empresa) and estado = 'abierto');
drop policy if exists miembros_todo on public.carritos_lineas;
create policy miembros_todo on public.carritos_lineas
  for all to authenticated
  using (public.es_miembro(id_empresa))
  with check (public.es_miembro(id_empresa));

-- Documentos: solo lectura; se escriben con emitir_documento() / anular_documento().
drop policy if exists empresa_lectura on public.documentos;
create policy empresa_lectura on public.documentos
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists empresa_lectura on public.documentos_lineas;
create policy empresa_lectura on public.documentos_lineas
  for select to authenticated using (public.es_miembro(id_empresa));

revoke all on function public.emitir_documento(uuid, text, date) from public, anon;
revoke all on function public.anular_documento(uuid, text) from public, anon;
revoke all on function public.carrito_desde_documento(uuid) from public, anon;
grant execute on function public.emitir_documento(uuid, text, date) to authenticated;
grant execute on function public.anular_documento(uuid, text) to authenticated;
grant execute on function public.carrito_desde_documento(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- 8. Vistas
-- -----------------------------------------------------------------------------

create or replace view public.v_clientes with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.nombre,
       c.rtn,
       c.telefono,
       c.correo,
       c.direccion,
       c.notas,
       c.activo,
       (select count(*) from public.documentos d where d.id_cliente = c.id and d.tipo = 'factura' and d.estado = 'emitido')::integer as facturas,
       (select max(d.fecha) from public.documentos d where d.id_cliente = c.id) as ultima_compra,
       c.creado_en
  from public.clientes c;

create or replace view public.v_cai with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.cai,
       c.tipo_documento,
       c.establecimiento,
       c.punto_emision,
       c.rango_inicial,
       c.rango_final,
       c.siguiente,
       greatest(c.rango_final - c.siguiente + 1, 0) as disponibles,
       round((c.siguiente - c.rango_inicial)::numeric / (c.rango_final - c.rango_inicial + 1) * 100, 1) as usado_pct,
       c.fecha_limite,
       (c.fecha_limite - (now() at time zone 'America/Tegucigalpa')::date) as dias_restantes,
       c.activo,
       (c.activo and c.siguiente <= c.rango_final
          and c.fecha_limite >= (now() at time zone 'America/Tegucigalpa')::date) as vigente,
       c.creado_en
  from public.cai c;

create or replace view public.v_carritos with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.nombre,
       c.id_cliente,
       c.cliente_nombre,
       c.cliente_rtn,
       c.cliente_telefono,
       c.id_marca,
       c.id_modelo,
       c.id_modelo_anio,
       c.id_especificacion,
       c.vehiculo,
       c.descuento_pct,
       c.notas,
       c.estado,
       coalesce(t.lineas, 0)::integer as lineas,
       coalesce(t.unidades, 0) as unidades,
       u.nombre as creado_por_nombre,
       c.creado_en,
       c.actualizado_en
  from public.carritos c
  left join public.usuarios u on u.id = c.creado_por
  left join (
    select id_carrito, count(*) as lineas, sum(cantidad) as unidades
      from public.carritos_lineas group by id_carrito
  ) t on t.id_carrito = c.id;

create or replace view public.v_carritos_lineas with (security_invoker = true) as
select l.id,
       l.id_carrito,
       l.id_empresa,
       l.id_producto,
       l.codigo,
       l.descripcion,
       l.cantidad,
       l.precio,
       l.descuento_pct,
       l.exento,
       l.orden,
       p.costo,
       p.existencia,
       p.controla_inventario,
       p.unidad,
       p.oem,
       (select coalesce(i.ruta_miniatura, i.ruta) from public.productos_imagenes i
         where i.id_producto = l.id_producto order by i.orden, i.id limit 1) as imagen
  from public.carritos_lineas l
  left join public.productos p on p.id = l.id_producto;

create or replace view public.v_documentos with (security_invoker = true) as
select d.id,
       d.id_empresa,
       d.tipo,
       d.numero,
       d.fecha,
       d.vence,
       d.cliente_nombre,
       d.cliente_rtn,
       d.vehiculo,
       d.subtotal,
       d.descuento,
       d.isv,
       d.total,
       d.estado,
       d.cai,
       u.nombre as vendedor,
       d.creado_en
  from public.documentos d
  left join public.usuarios u on u.id = d.creado_por;

create or replace view public.v_documentos_lineas with (security_invoker = true) as
select l.id, l.id_documento, l.id_empresa, l.id_producto, l.codigo, l.descripcion, l.cantidad,
       l.precio, l.descuento_pct, l.descuento, l.exento, l.total, l.orden
  from public.documentos_lineas l;

revoke all on public.v_clientes, public.v_cai, public.v_carritos, public.v_carritos_lineas,
              public.v_documentos, public.v_documentos_lineas
  from anon;
grant select on public.v_clientes, public.v_cai, public.v_carritos, public.v_carritos_lineas,
                public.v_documentos, public.v_documentos_lineas
  to authenticated;

-- -----------------------------------------------------------------------------
-- 9. Documentación en la base
-- -----------------------------------------------------------------------------

comment on column public.empresas.descuento_maximo_vendedor is 'Porcentaje máximo de descuento que puede dar un vendedor (dueño/admin sin tope).';
comment on table public.clientes is 'Clientes de la empresa. RTN opcional (14 dígitos), único por empresa.';
comment on table public.cai is 'Rangos de numeración autorizados por el SAR. siguiente = próximo correlativo.';
comment on table public.carritos is 'Borradores de venta (mostrador). Se cierran al emitir un documento.';
comment on table public.documentos is 'Cotizaciones y facturas emitidas. Inmutables: se anulan, nunca se borran.';
comment on function public.emitir_documento(uuid, text, date) is 'Carrito → cotización o factura (CAI). Calcula totales y descuenta existencia.';

commit;
