-- =============================================================================
-- 0011 · Registro de actividad (logs)
-- -----------------------------------------------------------------------------
-- Una sola tabla, `registros`, para saber qué pasó en cada momento:
--   · visita    → cada página que se abre (anónimos incluidos): IP, dispositivo,
--                 ruta, referente. La escribe el proxy de Next con la llave
--                 secreta (no pasa por RLS).
--   · sesion    → inicios de sesión, fallos y cierres, con IP y dispositivo.
--   · error     → errores del servidor (onRequestError) y del navegador.
--   · cambio    → auditoría automática: trigger en las tablas de negocio que
--                 guarda quién creó, editó (solo columnas cambiadas, antes y
--                 después) o eliminó cada fila.
-- La app pasa la IP y el dispositivo del usuario a PostgREST en los headers
-- x-cliente-ip / x-cliente-dispositivo (lib/supabase/server.ts); el trigger los
-- lee de request.headers. Un fallo al registrar NUNCA bloquea la operación.
--
-- Lectura: admin de plataforma ve todo; dueño/admin ven lo de su empresa.
-- Nadie la edita ni la borra desde la app (solo limpiar_registros()).
--
-- ESTADO: PENDIENTE
-- Idempotente y transaccional: se puede ejecutar más de una vez.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. Tabla
-- -----------------------------------------------------------------------------

create table if not exists public.registros (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  tipo text not null,
  nivel text not null default 'info',
  evento text not null,
  mensaje text,
  id_usuario uuid,
  correo text,
  id_empresa uuid,
  tabla text,
  id_registro text,
  ip inet,
  dispositivo text,
  agente text,
  pais text,
  ciudad text,
  ruta text,
  metodo text,
  referente text,
  entorno text,
  datos jsonb
);

comment on table public.registros is
  'Registro de actividad: visitas, sesiones, errores y cambios de datos. Solo se agrega; sin FKs para que sobreviva a borrados.';

do $$ begin
  if not exists (select 1 from pg_constraint
                 where conrelid = 'public.registros'::regclass and conname = 'registros_tipo_check') then
    alter table public.registros add constraint registros_tipo_check
      check (tipo in ('visita', 'sesion', 'error', 'cambio', 'accion'));
  end if;
  if not exists (select 1 from pg_constraint
                 where conrelid = 'public.registros'::regclass and conname = 'registros_nivel_check') then
    alter table public.registros add constraint registros_nivel_check
      check (nivel in ('info', 'aviso', 'error'));
  end if;
end $$;

create index if not exists registros_creado_en_idx on public.registros (creado_en desc);
create index if not exists registros_empresa_idx on public.registros (id_empresa, creado_en desc);
create index if not exists registros_tipo_idx on public.registros (tipo, creado_en desc);
create index if not exists registros_usuario_idx on public.registros (id_usuario, creado_en desc);

-- -----------------------------------------------------------------------------
-- 2. Seguridad: solo lectura, filtrada
-- -----------------------------------------------------------------------------

alter table public.registros enable row level security;

drop policy if exists registros_lectura on public.registros;
create policy registros_lectura on public.registros for select to authenticated
  using (
    (select public.es_admin_plataforma())
    or (id_empresa is not null and public.tiene_rol(id_empresa, array['dueno', 'admin']))
  );

revoke insert, update, delete, truncate on public.registros from anon, authenticated;
grant select on public.registros to authenticated;

-- -----------------------------------------------------------------------------
-- 3. Auditoría de cambios
-- -----------------------------------------------------------------------------

-- inet sin errores: un header raro no debe romper nada.
create or replace function public.ip_segura(p text)
returns inet
language plpgsql
immutable
set search_path = ''
as $$
begin
  return nullif(trim(p), '')::inet;
exception when others then
  return null;
end;
$$;

create or replace function public.registrar_cambio()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_nuevo jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  v_viejo jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  v_fila jsonb := coalesce(v_nuevo, v_viejo);
  v_cambios jsonb := '{}'::jsonb;
  v_datos jsonb;
  v_clave text;
  v_headers jsonb;
  v_empresa uuid;
begin
  begin
    if tg_op = 'UPDATE' then
      for v_clave in select jsonb_object_keys(v_nuevo) loop
        continue when v_clave in ('actualizado_en', 'modificado_en');
        if (v_nuevo -> v_clave) is distinct from (v_viejo -> v_clave) then
          v_cambios := v_cambios || jsonb_build_object(
            v_clave, jsonb_build_object('antes', v_viejo -> v_clave, 'despues', v_nuevo -> v_clave));
        end if;
      end loop;
      if v_cambios = '{}'::jsonb then
        return null;
      end if;
      v_datos := jsonb_build_object('cambios', v_cambios);
    elsif tg_op = 'INSERT' then
      v_datos := jsonb_build_object('nuevo', v_nuevo);
    else
      v_datos := jsonb_build_object('anterior', v_viejo);
    end if;

    v_headers := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
    v_empresa := case
      when tg_table_name = 'empresas' then (v_fila ->> 'id')::uuid
      else (v_fila ->> 'id_empresa')::uuid
    end;

    insert into public.registros
      (tipo, nivel, evento, id_usuario, correo, id_empresa, tabla, id_registro,
       ip, dispositivo, agente, ruta, entorno, datos)
    values (
      'cambio',
      case when tg_op = 'DELETE' then 'aviso' else 'info' end,
      tg_table_name || '.' || case tg_op when 'INSERT' then 'crear' when 'UPDATE' then 'editar' else 'eliminar' end,
      auth.uid(),
      auth.jwt() ->> 'email',
      v_empresa,
      tg_table_name,
      coalesce(v_fila ->> 'id', v_fila ->> 'id_usuario', v_fila ->> 'slug'),
      public.ip_segura(v_headers ->> 'x-cliente-ip'),
      left(v_headers ->> 'x-cliente-dispositivo', 200),
      left(coalesce(v_headers ->> 'x-cliente-agente', v_headers ->> 'user-agent'), 500),
      left(v_headers ->> 'x-cliente-ruta', 500),
      v_headers ->> 'x-cliente-entorno',
      v_datos
    );
  exception when others then
    -- Registrar es secundario: la operación de negocio sigue.
    raise warning 'registrar_cambio(%): %', tg_table_name, sqlerrm;
  end;
  return null;
end;
$$;

revoke execute on function public.registrar_cambio() from public, anon, authenticated;

-- Tablas auditadas (las que existan). Fuera a propósito: carritos y sus líneas
-- (borradores que cambian a cada tecla), líneas de documentos y correlativos
-- (se crean junto con el documento) y el kardex (ya es un historial).
do $$
declare
  v_tabla text;
begin
  foreach v_tabla in array array[
    'empresas', 'empresas_usuarios', 'invitaciones',
    'productos', 'productos_imagenes', 'productos_compatibilidades',
    'categorias', 'categorias_relacionadas', 'marcas_productos',
    'clientes', 'cai', 'documentos',
    'marcas', 'modelos', 'modelos_anios', 'tipos_carrocerias', 'especificaciones'
  ] loop
    if to_regclass('public.' || v_tabla) is not null then
      execute format(
        'create or replace trigger zz_registrar_cambio after insert or update or delete on public.%I '
        'for each row execute function public.registrar_cambio()', v_tabla);
    end if;
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 4. Vista para la tabla maestra
-- -----------------------------------------------------------------------------

-- Nombre de una empresa solo para quien puede verla (evita exponer nombres ajenos).
create or replace function public.nombre_empresa_visible(p_empresa uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select e.nombre from public.empresas e
   where e.id = p_empresa
     and (public.es_admin_plataforma() or public.es_miembro(p_empresa));
$$;

create or replace view public.v_registros
with (security_invoker = true) as
select
  r.id,
  r.creado_en,
  r.tipo,
  r.nivel,
  r.evento,
  r.mensaje,
  r.id_usuario,
  coalesce(u.nombre, r.correo) as usuario,
  r.correo,
  r.id_empresa,
  public.nombre_empresa_visible(r.id_empresa) as empresa,
  r.tabla,
  r.id_registro,
  host(r.ip) as ip,
  r.dispositivo,
  r.agente,
  nullif(concat_ws(', ', r.ciudad, r.pais), '') as ubicacion,
  r.ruta,
  r.metodo,
  r.referente,
  r.entorno,
  r.datos
from public.registros r
left join public.usuarios u on u.id = r.id_usuario;

grant select on public.v_registros to authenticated;

-- -----------------------------------------------------------------------------
-- 5. Limpieza (manual o con pg_cron)
-- -----------------------------------------------------------------------------

-- Borra visitas viejas (las más numerosas) y el resto pasado un plazo mayor.
-- Ejemplo con pg_cron (si se habilita la extensión):
--   select cron.schedule('limpiar-registros', '0 4 * * *', 'select public.limpiar_registros()');
create or replace function public.limpiar_registros(p_dias_visitas int default 180, p_dias_resto int default 730)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_borrados bigint;
begin
  if auth.uid() is not null and not public.es_admin_plataforma() then
    raise exception 'Solo el administrador de la plataforma puede limpiar el registro.';
  end if;
  delete from public.registros
   where (tipo = 'visita' and creado_en < now() - make_interval(days => greatest(p_dias_visitas, 30)))
      or (creado_en < now() - make_interval(days => greatest(p_dias_resto, 90)));
  get diagnostics v_borrados = row_count;
  return v_borrados;
end;
$$;

revoke execute on function public.limpiar_registros(int, int) from public, anon;
grant execute on function public.limpiar_registros(int, int) to authenticated;

commit;
