-- =============================================================================
-- 0013 · Sitio web público de cada empresa (catálogo + pedidos web)
-- -----------------------------------------------------------------------------
-- Cada taller puede publicar su sitio en /t/<slug>: portada, catálogo con
-- búsqueda por vehículo, ficha de producto, «Nosotros» y un carrito que llega
-- al sistema como PEDIDO WEB. El vendedor lo atiende y se vuelve un carrito del
-- mostrador (de ahí, cotización o factura como siempre).
--
--   · empresas.slug              Dirección pública (/t/<slug>), única.
--   · empresas.sitio_publicado   ¿Se ve sin sesión? (los miembros siempre ven
--                                la vista previa).
--   · empresas.sitio             Configuración (jsonb): textos de portada y
--                                Nosotros, WhatsApp, horario, destacados,
--                                mostrar precios… La normaliza la app
--                                (lib/sitio-web.ts).
--   · pedidos_web(+_lineas)      Lo que mandan los visitantes. Solo se crean con
--                                enviar_pedido_web() (anónimo, validado y con
--                                límite por IP/teléfono).
--   · Funciones públicas         sitio_publico, portada_web,
--                                buscar_catalogo_web, producto_web: solo
--                                productos visibles con existencia y SIN costo;
--                                el precio sale null si el taller lo oculta.
--   · buscar_productos()         Deja de ser anónima: el público entra por
--                                buscar_catalogo_web (que respeta «ocultar
--                                precios»).
--   · atender_pedido_web()       Pedido → carrito del mostrador.
--
-- ESTADO: YA APLICADA (confirmado 2026-10-02)
-- Idempotente y transaccional: se puede ejecutar más de una vez.
-- =============================================================================

begin;

-- Otras migraciones crean una igual en la misma sesión: se reemplaza.
drop function if exists pg_temp.agregar_restriccion(regclass, text, text);
create function pg_temp.agregar_restriccion(p_tabla regclass, p_nombre text, p_def text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = p_tabla and conname = p_nombre) then
    execute format('alter table %s add constraint %I %s', p_tabla, p_nombre, p_def);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Empresa: dirección y configuración del sitio
-- -----------------------------------------------------------------------------

alter table public.empresas add column if not exists slug text;
alter table public.empresas add column if not exists sitio_publicado boolean not null default false;
alter table public.empresas add column if not exists sitio jsonb not null default '{}'::jsonb;

create unique index if not exists empresas_slug_key on public.empresas (slug) where slug is not null;

select pg_temp.agregar_restriccion('public.empresas', 'empresas_slug_check',
  $$check (slug is null or (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) between 3 and 40))$$);
select pg_temp.agregar_restriccion('public.empresas', 'empresas_sitio_check',
  $$check (jsonb_typeof(sitio) = 'object' and pg_column_size(sitio) < 32768)$$);
select pg_temp.agregar_restriccion('public.empresas', 'empresas_sitio_publicado_check',
  $$check (not sitio_publicado or slug is not null)$$);

grant update (slug, sitio_publicado, sitio) on public.empresas to authenticated;

comment on column public.empresas.slug is 'Dirección del sitio público: /t/<slug>.';
comment on column public.empresas.sitio_publicado is 'El sitio público se ve sin sesión.';
comment on column public.empresas.sitio is 'Configuración del sitio público (lib/sitio-web.ts › ConfigSitio).';

-- -----------------------------------------------------------------------------
-- 2. Pedidos web
-- -----------------------------------------------------------------------------

create table if not exists public.pedidos_web (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  cliente_nombre text not null,
  cliente_telefono text not null,
  cliente_correo text,
  mensaje text,
  id_marca integer references public.marcas (id) on delete set null,
  id_modelo integer references public.modelos (id) on delete set null,
  id_modelo_anio integer references public.modelos_anios (id) on delete set null,
  id_especificacion integer references public.especificaciones (id) on delete set null,
  vehiculo text,
  estado text not null default 'nuevo',
  id_carrito uuid references public.carritos (id) on delete set null,
  atendido_por uuid references public.usuarios (id) on delete set null,
  atendido_en timestamptz,
  ip inet,
  creado_en timestamptz not null default now()
);

create unique index if not exists pedidos_web_numero_key on public.pedidos_web (numero);
create index if not exists pedidos_web_empresa_idx on public.pedidos_web (id_empresa, estado, creado_en desc);
create index if not exists pedidos_web_ip_idx on public.pedidos_web (ip, creado_en desc);
create index if not exists pedidos_web_telefono_idx on public.pedidos_web (cliente_telefono, creado_en desc);
create index if not exists pedidos_web_id_carrito_idx on public.pedidos_web (id_carrito);
create index if not exists pedidos_web_atendido_por_idx on public.pedidos_web (atendido_por);
create index if not exists pedidos_web_id_marca_idx on public.pedidos_web (id_marca);
create index if not exists pedidos_web_id_modelo_idx on public.pedidos_web (id_modelo);
create index if not exists pedidos_web_id_modelo_anio_idx on public.pedidos_web (id_modelo_anio);
create index if not exists pedidos_web_id_especificacion_idx on public.pedidos_web (id_especificacion);

select pg_temp.agregar_restriccion('public.pedidos_web', 'pedidos_web_estado_check',
  $$check (estado in ('nuevo', 'atendido', 'descartado'))$$);
select pg_temp.agregar_restriccion('public.pedidos_web', 'pedidos_web_textos_check',
  $$check (char_length(cliente_nombre) between 2 and 120
           and cliente_telefono ~ '^[0-9]{8,15}$'
           and (cliente_correo is null or char_length(cliente_correo) <= 120)
           and (mensaje is null or char_length(mensaje) <= 600)
           and (vehiculo is null or char_length(vehiculo) <= 200))$$);

create table if not exists public.pedidos_web_lineas (
  id bigint generated by default as identity primary key,
  id_pedido uuid not null references public.pedidos_web (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint references public.productos (id) on delete set null,
  codigo text,
  descripcion text not null,
  cantidad numeric(12, 2) not null,
  precio numeric(14, 2) not null default 0,
  exento boolean not null default false,
  orden integer not null default 0
);

create index if not exists pedidos_web_lineas_pedido_idx on public.pedidos_web_lineas (id_pedido, orden);
create index if not exists pedidos_web_lineas_id_empresa_idx on public.pedidos_web_lineas (id_empresa);
create index if not exists pedidos_web_lineas_id_producto_idx on public.pedidos_web_lineas (id_producto);

select pg_temp.agregar_restriccion('public.pedidos_web_lineas', 'pedidos_web_lineas_cantidad_check',
  $$check (cantidad > 0 and cantidad <= 999)$$);

alter table public.pedidos_web enable row level security;
alter table public.pedidos_web_lineas enable row level security;

revoke all on public.pedidos_web, public.pedidos_web_lineas from anon, authenticated;
grant select on public.pedidos_web, public.pedidos_web_lineas to authenticated;
-- Descartar un pedido; atenderlo es con atender_pedido_web().
grant update (estado) on public.pedidos_web to authenticated;

drop policy if exists miembros_leer on public.pedidos_web;
create policy miembros_leer on public.pedidos_web
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists miembros_estado on public.pedidos_web;
create policy miembros_estado on public.pedidos_web
  for update to authenticated
  using (public.es_miembro(id_empresa))
  with check (public.es_miembro(id_empresa));
drop policy if exists miembros_leer on public.pedidos_web_lineas;
create policy miembros_leer on public.pedidos_web_lineas
  for select to authenticated using (public.es_miembro(id_empresa));

create or replace view public.v_pedidos_web with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.numero,
       p.creado_en,
       p.cliente_nombre,
       p.cliente_telefono,
       p.cliente_correo,
       p.mensaje,
       p.vehiculo,
       p.estado,
       p.id_carrito,
       p.atendido_en,
       u.nombre as atendido_por,
       (select count(*) from public.pedidos_web_lineas l where l.id_pedido = p.id)::integer as lineas,
       (select coalesce(sum(round(l.cantidad * l.precio * case when l.exento then 1 else 1.15 end, 2)), 0)
          from public.pedidos_web_lineas l where l.id_pedido = p.id) as total_estimado
  from public.pedidos_web p
  left join public.usuarios u on u.id = p.atendido_por;

revoke all on public.v_pedidos_web from anon, authenticated;
grant select on public.v_pedidos_web to authenticated;

-- Auditoría (0011), si ya está.
do $$ begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public' and p.proname = 'registrar_cambio') then
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.pedidos_web '
            'for each row execute function public.registrar_cambio()';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 3. Ayudantes
-- -----------------------------------------------------------------------------

-- Empresa de un slug si el sitio se puede ver (publicado, o el usuario es miembro).
create or replace function public.empresa_sitio(p_slug text)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select e.id
    from public.empresas e
   where e.slug = lower(btrim(p_slug))
     and e.activo
     and (e.sitio_publicado or public.es_miembro(e.id));
$$;

-- ¿El taller muestra precios en su sitio?
create or replace function public.sitio_muestra_precios(p_empresa uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((e.sitio ->> 'mostrarPrecios')::boolean, true)
    from public.empresas e where e.id = p_empresa;
$$;

revoke all on function public.empresa_sitio(text), public.sitio_muestra_precios(uuid) from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- 4. Lectura pública
-- -----------------------------------------------------------------------------

-- Datos públicos de la empresa + configuración del sitio. Null si no se puede ver.
create or replace function public.sitio_publico(p_slug text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
           'id', e.id,
           'slug', e.slug,
           'nombre', e.nombre,
           'razon_social', e.razon_social,
           'telefono', e.telefono,
           'correo', e.correo,
           'direccion', e.direccion,
           'paleta', e.paleta,
           'acento', e.acento,
           'logo_ruta', e.logo_ruta,
           'fondo_ruta', e.fondo_ruta,
           'fondo_atenuar', e.fondo_atenuar,
           'sitio', e.sitio,
           'publicado', e.sitio_publicado,
           'es_miembro', public.es_miembro(e.id)
         )
    from public.empresas e
   where e.id = public.empresa_sitio(p_slug);
$$;

-- Portada: destacados (los elegidos por el taller o, si no hay, los últimos con
-- foto) y categorías con productos visibles.
create or replace function public.portada_web(p_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_empresa uuid := public.empresa_sitio(p_slug);
  v_precios boolean;
  v_elegidos bigint[];
  v_destacados jsonb;
  v_categorias jsonb;
begin
  if v_empresa is null then
    return null;
  end if;
  v_precios := public.sitio_muestra_precios(v_empresa);
  select coalesce(array_agg(d.valor::bigint), '{}')
    into v_elegidos
    from public.empresas e,
         jsonb_array_elements_text(coalesce(e.sitio -> 'destacados', '[]'::jsonb)) as d(valor)
   where e.id = v_empresa and d.valor ~ '^\d{1,18}$';

  with visibles as (
    select p.*
      from public.productos p
     where p.id_empresa = v_empresa and p.activo and p.visible_catalogo
       and (not p.controla_inventario or p.existencia > 0)
  ), elegidos as (
    select v.*, coalesce(array_position(v_elegidos, v.id), 1000) as pos
      from visibles v
     where cardinality(v_elegidos) = 0 or v.id = any (v_elegidos)
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'id', x.id, 'codigo', x.codigo, 'nombre', x.nombre,
           'marca', mp.nombre, 'categoria', c.nombre, 'condicion', x.condicion,
           'precio', case when v_precios then x.precio end, 'exento', x.exento,
           'imagen', (select coalesce(i.ruta_miniatura, i.ruta) from public.productos_imagenes i
                       where i.id_producto = x.id order by i.orden, i.id limit 1))
           order by x.pos, x.creado_en desc), '[]'::jsonb)
    into v_destacados
    from (
      select * from elegidos e
       order by e.pos,
                exists (select 1 from public.productos_imagenes i where i.id_producto = e.id) desc,
                e.creado_en desc
       limit 8
    ) x
    left join public.marcas_productos mp on mp.id = x.id_marca_producto
    join public.categorias c on c.id = x.id_categoria;

  select coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'nombre', t.nombre, 'productos', t.n)
           order by t.n desc, t.nombre), '[]'::jsonb)
    into v_categorias
    from (
      select c.id, c.nombre, count(*) as n
        from public.productos p
        join public.categorias c on c.id = p.id_categoria
       where p.id_empresa = v_empresa and p.activo and p.visible_catalogo
         and (not p.controla_inventario or p.existencia > 0)
       group by c.id, c.nombre
       order by n desc
       limit 12
    ) t;

  return jsonb_build_object('destacados', v_destacados, 'categorias', v_categorias);
end;
$$;

-- Búsqueda pública: la misma de mostrador (buscar_productos), pero solo lo
-- visible con existencia, sin costo ni ubicación, y sin precio si el taller lo oculta.
create or replace function public.buscar_catalogo_web(
  p_slug text,
  p_texto text default '',
  p_id_marca integer default null,
  p_id_modelo integer default null,
  p_id_modelo_anio integer default null,
  p_id_especificacion integer default null,
  p_id_categoria integer default null,
  p_limite integer default 48
)
returns table (
  id bigint,
  codigo text,
  nombre text,
  marca text,
  id_categoria integer,
  categoria text,
  condicion text,
  unidad text,
  precio numeric,
  exento boolean,
  imagen text,
  grupo text,
  ajuste text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_empresa uuid := public.empresa_sitio(p_slug);
  v_precios boolean;
begin
  if v_empresa is null then
    return;
  end if;
  v_precios := public.sitio_muestra_precios(v_empresa);
  return query
  select b.id, b.codigo, b.nombre, b.marca, b.id_categoria, b.categoria, b.condicion, b.unidad,
         case when v_precios then b.precio end, b.exento, b.imagen, b.grupo, b.ajuste
    from public.buscar_productos(v_empresa, p_texto, p_id_marca, p_id_modelo, p_id_modelo_anio,
                                 p_id_especificacion, p_id_categoria, least(coalesce(p_limite, 48), 96)) b
    join public.productos p on p.id = b.id
   where p.visible_catalogo and p.activo and (not p.controla_inventario or p.existencia > 0)
   order by b.orden;
end;
$$;

-- Ficha pública de un producto: datos, fotos y vehículos a los que le queda.
create or replace function public.producto_web(p_slug text, p_producto bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_empresa uuid := public.empresa_sitio(p_slug);
  v_resultado jsonb;
begin
  if v_empresa is null then
    return null;
  end if;
  select jsonb_build_object(
           'id', p.id, 'codigo', p.codigo, 'nombre', p.nombre, 'descripcion', p.descripcion,
           'marca', mp.nombre, 'id_categoria', p.id_categoria, 'categoria', c.nombre,
           'oem', p.oem, 'numero_parte', p.numero_parte, 'condicion', p.condicion,
           'unidad', p.unidad, 'garantia_dias', p.garantia_dias,
           'precio', case when public.sitio_muestra_precios(v_empresa) then p.precio end,
           'exento', p.exento,
           'imagenes', coalesce((select jsonb_agg(jsonb_build_object('ruta', i.ruta, 'miniatura', i.ruta_miniatura)
                                                  order by i.orden, i.id)
                                   from public.productos_imagenes i where i.id_producto = p.id), '[]'::jsonb),
           'vehiculos', coalesce((select jsonb_agg(v.texto order by v.texto)
                                    from (select distinct concat_ws(' ', ma.marca, mo.modelo, ya.anio::text,
                                                   case when e.id is not null then
                                                     round(e.motor_cc / 1000.0, 1)::text || ' L' end) as texto
                                            from public.productos_compatibilidades k
                                            join public.marcas ma on ma.id = k.id_marca
                                            left join public.modelos mo on mo.id = k.id_modelo
                                            left join public.modelos_anios ya on ya.id = k.id_modelo_anio
                                            left join public.especificaciones e on e.id = k.id_especificacion
                                           where k.id_producto = p.id
                                           limit 80) v), '[]'::jsonb)
         )
    into v_resultado
    from public.productos p
    join public.categorias c on c.id = p.id_categoria
    left join public.marcas_productos mp on mp.id = p.id_marca_producto
   where p.id = p_producto and p.id_empresa = v_empresa and p.activo and p.visible_catalogo
     and (not p.controla_inventario or p.existencia > 0);
  return v_resultado;
end;
$$;

-- Sitios publicados, para el sitemap.
create or replace function public.sitios_publicados()
returns table (slug text, nombre text)
language sql
stable
security definer
set search_path = ''
as $$
  select e.slug, e.nombre from public.empresas e
   where e.sitio_publicado and e.activo and e.slug is not null
   order by e.slug;
$$;

-- -----------------------------------------------------------------------------
-- 5. Enviar un pedido (anónimo)
-- -----------------------------------------------------------------------------

create or replace function public.enviar_pedido_web(
  p_slug text,
  p_cliente jsonb,
  p_vehiculo jsonb,
  p_lineas jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_empresa uuid := public.empresa_sitio(p_slug);
  v_headers jsonb := coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb;
  v_ip inet := public.ip_segura(v_headers ->> 'x-cliente-ip');
  v_nombre text := left(btrim(coalesce(p_cliente ->> 'nombre', '')), 120);
  v_telefono text := regexp_replace(coalesce(p_cliente ->> 'telefono', ''), '\D', '', 'g');
  v_correo text := nullif(left(btrim(coalesce(p_cliente ->> 'correo', '')), 120), '');
  v_mensaje text := nullif(left(btrim(coalesce(p_cliente ->> 'mensaje', '')), 600), '');
  v_marca integer;
  v_modelo integer;
  v_anio integer;
  v_esp integer;
  v_vehiculo text;
  v_pedido public.pedidos_web;
  v_linea jsonb;
  v_orden integer := 0;
  v_validas integer := 0;
begin
  if v_empresa is null then
    raise exception 'Este catálogo no está disponible.' using errcode = 'P0001';
  end if;
  if char_length(v_nombre) < 2 then
    raise exception 'Escribí tu nombre.' using errcode = 'P0001';
  end if;
  if v_telefono !~ '^[0-9]{8,15}$' then
    raise exception 'Escribí un teléfono de 8 dígitos.' using errcode = 'P0001';
  end if;
  if v_correo is not null and v_correo !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'El correo no es válido.' using errcode = 'P0001';
  end if;
  if jsonb_typeof(p_lineas) <> 'array' or jsonb_array_length(p_lineas) = 0 then
    raise exception 'Tu lista está vacía.' using errcode = 'P0001';
  end if;
  if jsonb_array_length(p_lineas) > 40 then
    raise exception 'Son demasiadas piezas para un pedido web. Llamanos.' using errcode = 'P0001';
  end if;

  -- Límite anti abuso: 6 pedidos por hora por IP y 3 cada 10 minutos por teléfono.
  if v_ip is not null and (select count(*) from public.pedidos_web
                            where ip = v_ip and creado_en > now() - interval '1 hour') >= 6 then
    raise exception 'Mandaste varios pedidos seguidos. Esperá un rato o llamanos.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.pedidos_web
       where cliente_telefono = v_telefono and creado_en > now() - interval '10 minutes') >= 3 then
    raise exception 'Ya recibimos tus pedidos. Te vamos a contactar pronto.' using errcode = 'P0001';
  end if;

  -- Vehículo: solo ids que existen y son coherentes entre sí.
  if jsonb_typeof(p_vehiculo) = 'object' then
    select ma.id into v_marca from public.marcas ma where ma.id = (p_vehiculo ->> 'id_marca')::integer;
    if v_marca is not null then
      select mo.id into v_modelo from public.modelos mo
       where mo.id = (p_vehiculo ->> 'id_modelo')::integer and mo.id_marca = v_marca;
    end if;
    if v_modelo is not null then
      select ya.id into v_anio from public.modelos_anios ya
       where ya.id = (p_vehiculo ->> 'id_modelo_anio')::integer and ya.id_modelo = v_modelo;
    end if;
    if v_anio is not null then
      select e.id into v_esp from public.especificaciones e
       where e.id = (p_vehiculo ->> 'id_especificacion')::integer and e.id_modelo_anio = v_anio;
    end if;
    select concat_ws(' ', ma.marca, mo.modelo, ya.anio::text,
                     case when e.id is not null then round(e.motor_cc / 1000.0, 1)::text || ' L' end)
      into v_vehiculo
      from public.marcas ma
      left join public.modelos mo on mo.id = v_modelo
      left join public.modelos_anios ya on ya.id = v_anio
      left join public.especificaciones e on e.id = v_esp
     where ma.id = v_marca;
  end if;

  insert into public.pedidos_web (id_empresa, cliente_nombre, cliente_telefono, cliente_correo, mensaje,
                                  id_marca, id_modelo, id_modelo_anio, id_especificacion, vehiculo, ip)
  values (v_empresa, v_nombre, v_telefono, v_correo, v_mensaje, v_marca, v_modelo, v_anio, v_esp,
          left(v_vehiculo, 200), v_ip)
  returning * into v_pedido;

  -- Las líneas toman nombre, código y precio de la base: nunca del navegador.
  for v_linea in select * from jsonb_array_elements(p_lineas) loop
    insert into public.pedidos_web_lineas (id_pedido, id_empresa, id_producto, codigo, descripcion, cantidad,
                                           precio, exento, orden)
    select v_pedido.id, v_empresa, p.id, p.codigo, p.nombre,
           least(greatest(round(coalesce((v_linea ->> 'cantidad')::numeric, 1), 0), 1), 999),
           p.precio, p.exento, v_orden
      from public.productos p
     where p.id = (v_linea ->> 'id_producto')::bigint
       and p.id_empresa = v_empresa and p.activo and p.visible_catalogo;
    if found then
      v_validas := v_validas + 1;
      v_orden := v_orden + 1;
    end if;
  end loop;

  if v_validas = 0 then
    raise exception 'Las piezas de tu lista ya no están disponibles.' using errcode = 'P0001';
  end if;

  return jsonb_build_object('id', v_pedido.id, 'numero', v_pedido.numero, 'lineas', v_validas);
exception
  when invalid_text_representation or numeric_value_out_of_range then
    raise exception 'Datos no válidos.' using errcode = 'P0001';
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Atender un pedido: se vuelve un carrito del mostrador
-- -----------------------------------------------------------------------------

create or replace function public.atender_pedido_web(p_pedido uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pedido public.pedidos_web;
  v_carrito uuid;
begin
  select * into v_pedido from public.pedidos_web where id = p_pedido for update;
  if not found or not public.es_miembro(v_pedido.id_empresa) then
    raise exception 'El pedido no existe.' using errcode = 'P0001';
  end if;

  -- Ya atendido y su carrito sigue abierto: se reabre ese.
  if v_pedido.id_carrito is not null
     and exists (select 1 from public.carritos c where c.id = v_pedido.id_carrito and c.estado = 'abierto') then
    return v_pedido.id_carrito;
  end if;

  insert into public.carritos (id_empresa, nombre, cliente_nombre, cliente_telefono,
                               id_marca, id_modelo, id_modelo_anio, id_especificacion, notas)
  values (v_pedido.id_empresa, 'Web #' || v_pedido.numero, v_pedido.cliente_nombre, v_pedido.cliente_telefono,
          v_pedido.id_marca, v_pedido.id_modelo, v_pedido.id_modelo_anio, v_pedido.id_especificacion,
          left(concat_ws(E'\n', 'Pedido web #' || v_pedido.numero, v_pedido.mensaje), 1000))
  returning id into v_carrito;

  -- Precio de hoy (el del pedido es referencia: pudo cambiar).
  insert into public.carritos_lineas (id_carrito, id_empresa, id_producto, codigo, descripcion, cantidad, precio,
                                      exento, orden)
  select v_carrito, v_pedido.id_empresa, l.id_producto, coalesce(p.codigo, l.codigo), coalesce(p.nombre, l.descripcion),
         l.cantidad, coalesce(p.precio, l.precio), coalesce(p.exento, l.exento), l.orden
    from public.pedidos_web_lineas l
    left join public.productos p on p.id = l.id_producto
   where l.id_pedido = p_pedido
   order by l.orden;

  update public.pedidos_web
     set estado = 'atendido', id_carrito = v_carrito, atendido_por = auth.uid(), atendido_en = now()
   where id = p_pedido;

  return v_carrito;
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Permisos de funciones
-- -----------------------------------------------------------------------------

revoke all on function public.sitio_publico(text), public.portada_web(text), public.sitios_publicados(),
                       public.buscar_catalogo_web(text, text, integer, integer, integer, integer, integer, integer),
                       public.producto_web(text, bigint),
                       public.enviar_pedido_web(text, jsonb, jsonb, jsonb),
                       public.atender_pedido_web(uuid)
  from public;
grant execute on function public.sitio_publico(text), public.portada_web(text), public.sitios_publicados(),
                          public.buscar_catalogo_web(text, text, integer, integer, integer, integer, integer, integer),
                          public.producto_web(text, bigint),
                          public.enviar_pedido_web(text, jsonb, jsonb, jsonb)
  to anon, authenticated;
grant execute on function public.atender_pedido_web(uuid) to authenticated;

-- El público ya no llama buscar_productos directo (devolvía el precio aunque
-- el taller lo oculte): entra por buscar_catalogo_web.
revoke execute on function public.buscar_productos(uuid, text, integer, integer, integer, integer, integer, integer)
  from anon;

commit;
