-- =============================================================================
-- 0016 · Notas de crédito y débito, devoluciones, exoneraciones y puntos de emisión
-- -----------------------------------------------------------------------------
-- ESTADO: PENDIENTE
-- Idempotente y atómica. Requiere 0005 (ventas) y 0003 (membresías). Usa 0011
-- (auditoría) si existe.
--
-- Qué crea o cambia:
--   · puntos_emision          Establecimientos (sucursales) y puntos de emisión
--                             (cajas) por empresa; uno es el predeterminado.
--                             Se crean solos desde los CAI ya registrados.
--   · cai.id_punto_emision    Cada CAI pertenece a un punto de emisión.
--   · empresas_usuarios.id_punto_emision
--                             Punto de emisión de cada persona (null = el
--                             predeterminado). Cada quien puede elegir el suyo.
--   · clientes / carritos     Datos de exoneración (constancia de registro de
--                             exonerado, orden de compra exenta, registro SAG).
--   · documentos              Tipos nota_credito y nota_debito; referencia a la
--                             factura que modifican; motivo; importe exonerado;
--                             punto de emisión; devolución con reintegro.
--   · documentos_lineas.id_linea_origen   Línea de la factura que se acredita.
--   · emitir_documento()      Numera con el CAI del punto de emisión de quien
--                             factura y aplica la exoneración.
--   · emitir_nota()           Nota de crédito (devolución, descuento, corrección)
--                             o de débito sobre una factura emitida.
--   · anular_documento()      No anula facturas con notas vigentes; al anular
--                             una devolución vuelve a sacar las existencias.
--   · Vistas v_puntos_emision, v_lineas_acreditables; columnas nuevas al final
--     de v_cai, v_miembros, v_carritos, v_documentos, v_documentos_lineas,
--     v_clientes.
--
-- Reglas fiscales (docs/negocio.md §3.5):
--   · Tipo de documento SAR: 01 factura, 06 nota de crédito, 07 nota de débito.
--   · Factura exonerada: exige RTN del cliente y la orden de compra exenta o la
--     constancia de registro de exonerado; lo gravado pasa a «importe exonerado»
--     y no lleva ISV.
--   · Una nota no puede acreditar más de lo que queda de la factura (total +
--     débitos − créditos), ni devolver más unidades de las vendidas.
-- =============================================================================

begin;

create or replace function pg_temp.restriccion_0016(tabla regclass, nombre text, definicion text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = tabla and conname = nombre) then
    execute format('alter table %s add constraint %I %s', tabla, nombre, definicion);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Puntos de emisión
-- -----------------------------------------------------------------------------

create table if not exists public.puntos_emision (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  establecimiento text not null default '000',
  sucursal text not null default 'Principal',
  direccion text,
  telefono text,
  punto_emision text not null default '001',
  nombre text not null default 'Caja principal',
  predeterminado boolean not null default false,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid()
);

create unique index if not exists puntos_emision_codigo_key
  on public.puntos_emision (id_empresa, establecimiento, punto_emision);
create unique index if not exists puntos_emision_predeterminado_key
  on public.puntos_emision (id_empresa) where predeterminado;
create index if not exists puntos_emision_creado_por_idx on public.puntos_emision (creado_por);

select pg_temp.restriccion_0016('public.puntos_emision', 'puntos_emision_codigos_check',
  $$check (establecimiento ~ '^\d{3}$' and punto_emision ~ '^\d{3}$')$$);
select pg_temp.restriccion_0016('public.puntos_emision', 'puntos_emision_textos_check',
  $$check (btrim(sucursal) <> '' and char_length(sucursal) <= 80
           and btrim(nombre) <> '' and char_length(nombre) <= 80
           and (direccion is null or char_length(direccion) <= 200)
           and (telefono is null or char_length(telefono) <= 30))$$);

create or replace function public.tg_puntos_emision()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un punto de emisión.';
  end if;
  new.establecimiento := lpad(btrim(new.establecimiento), 3, '0');
  new.punto_emision := lpad(btrim(new.punto_emision), 3, '0');
  new.sucursal := regexp_replace(btrim(new.sucursal), '\s+', ' ', 'g');
  new.nombre := regexp_replace(btrim(new.nombre), '\s+', ' ', 'g');
  new.direccion := nullif(btrim(new.direccion), '');
  new.telefono := nullif(btrim(new.telefono), '');

  if tg_op = 'UPDATE'
     and (new.establecimiento <> old.establecimiento or new.punto_emision <> old.punto_emision)
     and exists (select 1 from public.cai c where c.id_punto_emision = old.id) then
    raise exception 'Este punto ya tiene CAI registrados: sus códigos no se pueden cambiar. Creá otro punto.';
  end if;

  -- El primero de la empresa es el predeterminado; marcar uno desmarca los demás
  -- (ese update interno se marca para no volver a entrar en esta regla).
  if coalesce(current_setting('wp.desmarcando_punto', true), '') <> 'si' then
    if not exists (select 1 from public.puntos_emision p
                    where p.id_empresa = new.id_empresa and p.predeterminado and p.id <> new.id) then
      new.predeterminado := true;
    elsif new.predeterminado then
      perform set_config('wp.desmarcando_punto', 'si', true);
      update public.puntos_emision set predeterminado = false
       where id_empresa = new.id_empresa and predeterminado and id <> new.id;
      perform set_config('wp.desmarcando_punto', '', true);
    end if;
  end if;
  if new.predeterminado and not new.activo then
    raise exception 'El punto predeterminado no se puede desactivar. Marcá otro como predeterminado primero.';
  end if;
  return new;
end;
$$;

create or replace trigger a_preparar
  before insert or update on public.puntos_emision
  for each row execute function public.tg_puntos_emision();

-- -----------------------------------------------------------------------------
-- 2. CAI por punto de emisión
-- -----------------------------------------------------------------------------

alter table public.cai add column if not exists id_punto_emision bigint references public.puntos_emision (id);
create index if not exists cai_id_punto_emision_idx on public.cai (id_punto_emision);

-- Puntos a partir de los CAI ya registrados (con su nombre genérico).
insert into public.puntos_emision (id_empresa, establecimiento, punto_emision, nombre)
select distinct c.id_empresa, c.establecimiento, c.punto_emision,
       case when c.punto_emision = '001' then 'Caja principal' else 'Caja ' || ltrim(c.punto_emision, '0') end
  from public.cai c
 where c.id_punto_emision is null
on conflict (id_empresa, establecimiento, punto_emision) do nothing;

update public.cai c
   set id_punto_emision = p.id
  from public.puntos_emision p
 where c.id_punto_emision is null
   and p.id_empresa = c.id_empresa and p.establecimiento = c.establecimiento and p.punto_emision = c.punto_emision;

create or replace function public.tg_cai()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_limpio text;
  v_punto public.puntos_emision;
begin
  if tg_op = 'INSERT' then
    v_limpio := upper(regexp_replace(coalesce(new.cai, ''), '[^0-9A-Fa-f]', '', 'g'));
    if char_length(v_limpio) = 32 then
      new.cai := substr(v_limpio, 1, 6) || '-' || substr(v_limpio, 7, 6) || '-' || substr(v_limpio, 13, 6) || '-'
              || substr(v_limpio, 19, 6) || '-' || substr(v_limpio, 25, 6) || '-' || substr(v_limpio, 31, 2);
    else
      new.cai := upper(btrim(new.cai));
    end if;
    new.tipo_documento := lpad(btrim(new.tipo_documento), 2, '0');
    new.siguiente := coalesce(new.siguiente, new.rango_inicial);
  elsif exists (select 1 from public.documentos d where d.id_cai = old.id) and (
          new.cai <> old.cai or new.tipo_documento <> old.tipo_documento
          or new.id_punto_emision is distinct from old.id_punto_emision
          or new.rango_inicial <> old.rango_inicial or new.rango_final <> old.rango_final
          or new.fecha_limite <> old.fecha_limite or new.id_empresa <> old.id_empresa
          or new.siguiente < old.siguiente) then
    raise exception 'Este CAI ya tiene documentos emitidos: solo se puede activar o desactivar.';
  end if;

  -- Punto de emisión: el elegido manda; si vienen solo los códigos, se busca o se crea.
  if new.id_punto_emision is not null then
    select * into v_punto from public.puntos_emision
     where id = new.id_punto_emision and id_empresa = new.id_empresa;
    if not found then
      raise exception 'El punto de emisión no existe.';
    end if;
  else
    new.establecimiento := lpad(btrim(coalesce(new.establecimiento, '000')), 3, '0');
    new.punto_emision := lpad(btrim(coalesce(new.punto_emision, '001')), 3, '0');
    select * into v_punto from public.puntos_emision
     where id_empresa = new.id_empresa and establecimiento = new.establecimiento
       and punto_emision = new.punto_emision;
    if not found then
      insert into public.puntos_emision (id_empresa, establecimiento, punto_emision)
      values (new.id_empresa, new.establecimiento, new.punto_emision)
      returning * into v_punto;
    end if;
  end if;
  new.id_punto_emision := v_punto.id;
  new.establecimiento := v_punto.establecimiento;
  new.punto_emision := v_punto.punto_emision;
  return new;
end;
$$;

grant update (id_punto_emision) on public.cai to authenticated;

-- -----------------------------------------------------------------------------
-- 3. Punto de emisión de cada persona
-- -----------------------------------------------------------------------------

alter table public.empresas_usuarios
  add column if not exists id_punto_emision bigint references public.puntos_emision (id) on delete set null;
create index if not exists empresas_usuarios_id_punto_emision_idx on public.empresas_usuarios (id_punto_emision);

grant update (rol, activo, id_punto_emision) on public.empresas_usuarios to authenticated;

-- Igual que en 0003, pero el punto de emisión no es un cambio de rol: cada quien
-- elige el suyo y dueño/admin se lo asignan a cualquiera.
create or replace function public.tg_reglas_membresia()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
begin
  if new.id_punto_emision is not null
     and new.id_punto_emision is distinct from old.id_punto_emision
     and not exists (select 1 from public.puntos_emision p
                      where p.id = new.id_punto_emision and p.id_empresa = new.id_empresa and p.activo) then
    raise exception 'El punto de emisión no existe o está inactivo.';
  end if;

  -- Cambios hechos por el sistema (SQL/migraciones) no se restringen.
  if v_actor is null or (new.rol, new.activo) is not distinct from (old.rol, old.activo) then
    return new;
  end if;

  if old.id_usuario = v_actor then
    raise exception 'No podés cambiar tu propio rol ni desactivarte.';
  end if;

  if (old.rol = 'dueno' or new.rol = 'dueno')
     and not public.tiene_rol(old.id_empresa, array['dueno']) then
    raise exception 'Solo un dueño puede modificar a otro dueño o asignar ese rol.';
  end if;

  if old.rol = 'dueno' and old.activo and (new.rol <> 'dueno' or not new.activo)
     and not exists (
       select 1 from public.empresas_usuarios
        where id_empresa = old.id_empresa and rol = 'dueno' and activo
          and id_usuario <> old.id_usuario
     ) then
    raise exception 'La empresa debe tener al menos un dueño activo.';
  end if;

  return new;
end;
$$;

-- La política de 0003 solo deja editar a dueño/admin; cada quien puede tocar su
-- propia fila (el trigger y el permiso por columna limitan qué).
drop policy if exists empresas_usuarios_propio_punto on public.empresas_usuarios;
create policy empresas_usuarios_propio_punto on public.empresas_usuarios
  for update to authenticated
  using (id_usuario = auth.uid() and activo)
  with check (id_usuario = auth.uid() and activo);

-- Punto de emisión con el que emite quien llama: el suyo (si está activo) o el predeterminado.
create or replace function public.punto_emision_actual(p_empresa uuid)
returns public.puntos_emision
language sql
stable
security definer
set search_path = ''
as $$
  select p.*
    from public.puntos_emision p
   where p.id_empresa = p_empresa and p.activo and public.es_miembro(p_empresa)
   order by (p.id = (select eu.id_punto_emision from public.empresas_usuarios eu
                      where eu.id_empresa = p_empresa and eu.id_usuario = auth.uid())) desc nulls last,
            p.predeterminado desc, p.id
   limit 1;
$$;

revoke all on function public.punto_emision_actual(uuid) from public, anon;
grant execute on function public.punto_emision_actual(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- 4. Exoneración: clientes y carritos
-- -----------------------------------------------------------------------------

alter table public.clientes add column if not exists exonerado boolean not null default false;
alter table public.clientes add column if not exists exo_constancia text;
alter table public.clientes add column if not exists exo_registro_sag text;

select pg_temp.restriccion_0016('public.clientes', 'clientes_exoneracion_check',
  $$check ((exo_constancia is null or char_length(exo_constancia) <= 60)
           and (exo_registro_sag is null or char_length(exo_registro_sag) <= 60))$$);

grant update (exonerado, exo_constancia, exo_registro_sag) on public.clientes to authenticated;

alter table public.carritos add column if not exists exonerado boolean not null default false;
alter table public.carritos add column if not exists exo_orden_compra text;
alter table public.carritos add column if not exists exo_constancia text;
alter table public.carritos add column if not exists exo_registro_sag text;

select pg_temp.restriccion_0016('public.carritos', 'carritos_exoneracion_check',
  $$check ((exo_orden_compra is null or char_length(exo_orden_compra) <= 60)
           and (exo_constancia is null or char_length(exo_constancia) <= 60)
           and (exo_registro_sag is null or char_length(exo_registro_sag) <= 60))$$);

grant update (exonerado, exo_orden_compra, exo_constancia, exo_registro_sag) on public.carritos to authenticated;

create or replace function public.tg_normalizar_cliente()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un cliente.';
  end if;
  new.nombre := upper(regexp_replace(btrim(new.nombre), '\s+', ' ', 'g'));
  new.rtn := nullif(regexp_replace(coalesce(new.rtn, ''), '\D', '', 'g'), '');
  new.telefono := nullif(btrim(new.telefono), '');
  new.correo := nullif(lower(btrim(new.correo)), '');
  new.direccion := nullif(btrim(new.direccion), '');
  new.notas := nullif(btrim(new.notas), '');
  new.exo_constancia := nullif(upper(btrim(new.exo_constancia)), '');
  new.exo_registro_sag := nullif(upper(btrim(new.exo_registro_sag)), '');
  return new;
end;
$$;

-- 0005 + datos de exoneración del cliente elegido.
create or replace function public.tg_carritos()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_tope numeric;
  v_cli record;
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un carrito.';
  end if;
  if tg_op = 'UPDATE' and old.estado = 'cerrado' and new.estado = 'cerrado' then
    raise exception 'Este carrito ya se cerró. Abrí uno nuevo.';
  end if;

  -- Cliente elegido: copia sus datos (y su exoneración) si no se escribieron otros.
  if new.id_cliente is not null
     and (tg_op = 'INSERT' or new.id_cliente is distinct from old.id_cliente) then
    select c.nombre, c.rtn, c.telefono, c.exonerado, c.exo_constancia, c.exo_registro_sag into v_cli
      from public.clientes c where c.id = new.id_cliente and c.id_empresa = new.id_empresa;
    if not found then
      raise exception 'El cliente no existe.';
    end if;
    new.cliente_nombre := v_cli.nombre;
    new.cliente_rtn := v_cli.rtn;
    new.cliente_telefono := v_cli.telefono;
    new.exonerado := v_cli.exonerado;
    new.exo_constancia := v_cli.exo_constancia;
    new.exo_registro_sag := v_cli.exo_registro_sag;
    new.exo_orden_compra := null;
  end if;

  new.nombre := nullif(btrim(new.nombre), '');
  new.cliente_nombre := nullif(upper(regexp_replace(btrim(new.cliente_nombre), '\s+', ' ', 'g')), '');
  new.cliente_rtn := nullif(regexp_replace(coalesce(new.cliente_rtn, ''), '\D', '', 'g'), '');
  new.cliente_telefono := nullif(btrim(new.cliente_telefono), '');
  new.notas := nullif(btrim(new.notas), '');
  new.exo_orden_compra := nullif(upper(btrim(new.exo_orden_compra)), '');
  new.exo_constancia := nullif(upper(btrim(new.exo_constancia)), '');
  new.exo_registro_sag := nullif(upper(btrim(new.exo_registro_sag)), '');

  -- Vehículo: completa ancestros y arma el texto «TOYOTA COROLLA 2005 · 1.8 L».
  if new.id_especificacion is not null then
    select e.id_modelo_anio into new.id_modelo_anio from public.especificaciones e where e.id = new.id_especificacion;
  end if;
  if new.id_modelo_anio is not null then
    select ya.id_modelo into new.id_modelo from public.modelos_anios ya where ya.id = new.id_modelo_anio;
  end if;
  if new.id_modelo is not null then
    select mo.id_marca into new.id_marca from public.modelos mo where mo.id = new.id_modelo;
  end if;
  select nullif(concat_ws(' ', ma.marca, mo.modelo, ya.anio::text,
                          case when e.id is not null then '· ' || round(e.motor_cc / 1000.0, 1)::text || ' L'
                               || coalesce(' ' || e.motor_numero, '') end), '')
    into new.vehiculo
    from (select 1) x
    left join public.marcas ma on ma.id = new.id_marca
    left join public.modelos mo on mo.id = new.id_modelo
    left join public.modelos_anios ya on ya.id = new.id_modelo_anio
    left join public.especificaciones e on e.id = new.id_especificacion;

  if new.descuento_pct > 0
     and (tg_op = 'INSERT' or new.descuento_pct <> old.descuento_pct)
     and auth.uid() is not null
     and coalesce(current_setting('wp.copia_documento', true), '') <> 'si'
     and not public.tiene_rol(new.id_empresa, array['dueno', 'admin']) then
    select e.descuento_maximo_vendedor into v_tope from public.empresas e where e.id = new.id_empresa;
    if new.descuento_pct > v_tope then
      raise exception 'Tu rol permite hasta % %% de descuento.', rtrim(to_char(v_tope, 'FM990.##'), '.');
    end if;
  end if;

  new.actualizado_en := now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Documentos: notas, exoneración y punto de emisión
-- -----------------------------------------------------------------------------

alter table public.documentos add column if not exists importe_exonerado numeric(14, 2) not null default 0;
alter table public.documentos add column if not exists exoneracion jsonb;
alter table public.documentos add column if not exists id_punto_emision bigint references public.puntos_emision (id);
alter table public.documentos add column if not exists establecimiento text;
alter table public.documentos add column if not exists punto_emision text;
alter table public.documentos add column if not exists id_factura uuid references public.documentos (id);
alter table public.documentos add column if not exists factura_numero text;
alter table public.documentos add column if not exists factura_fecha timestamptz;
alter table public.documentos add column if not exists factura_cai text;
alter table public.documentos add column if not exists motivo_tipo text;
alter table public.documentos add column if not exists motivo text;
alter table public.documentos add column if not exists reintegra_inventario boolean not null default false;

create index if not exists documentos_id_punto_emision_idx on public.documentos (id_punto_emision);
create index if not exists documentos_id_factura_idx on public.documentos (id_factura);

-- Los documentos ya emitidos guardan los códigos de su CAI.
update public.documentos d
   set id_punto_emision = c.id_punto_emision, establecimiento = c.establecimiento, punto_emision = c.punto_emision
  from public.cai c
 where d.id_cai = c.id and d.id_punto_emision is null;

alter table public.documentos drop constraint if exists documentos_tipo_check;
alter table public.documentos add constraint documentos_tipo_check
  check (tipo in ('cotizacion', 'factura', 'nota_credito', 'nota_debito'));

select pg_temp.restriccion_0016('public.documentos', 'documentos_nota_check',
  $$check (tipo not in ('nota_credito', 'nota_debito')
           or (id_factura is not null and motivo_tipo is not null and motivo is not null))$$);
select pg_temp.restriccion_0016('public.documentos', 'documentos_motivo_tipo_check',
  $$check (motivo_tipo is null or motivo_tipo in ('devolucion', 'descuento', 'correccion', 'intereses', 'gastos', 'otro'))$$);

alter table public.documentos_lineas
  add column if not exists id_linea_origen bigint references public.documentos_lineas (id);
create index if not exists documentos_lineas_id_linea_origen_idx on public.documentos_lineas (id_linea_origen);

-- -----------------------------------------------------------------------------
-- 6. Numeración con CAI (factura, nota de crédito, nota de débito)
-- -----------------------------------------------------------------------------

-- Código SAR del tipo de documento.
create or replace function public.codigo_tipo_documento(p_tipo text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_tipo when 'factura' then '01' when 'nota_credito' then '06' when 'nota_debito' then '07' end;
$$;

-- Toma el siguiente número del CAI vigente del punto (con bloqueo) y devuelve
-- el CAI tal como estaba (siguiente = número usado). Solo para las funciones de emisión.
create or replace function public.tomar_numero_cai(p_punto public.puntos_emision, p_tipo text)
returns public.cai
language plpgsql
set search_path = ''
as $$
declare
  v_cai public.cai;
  v_hoy date := (now() at time zone 'America/Tegucigalpa')::date;
  v_nombre text := case p_tipo when 'factura' then 'facturas' when 'nota_credito' then 'notas de crédito'
                               else 'notas de débito' end;
begin
  if p_punto.id is null then
    raise exception 'No hay un punto de emisión activo. Registralo en Ventas › Puntos de emisión.';
  end if;
  select * into v_cai
    from public.cai
   where id_empresa = p_punto.id_empresa and id_punto_emision = p_punto.id
     and tipo_documento = public.codigo_tipo_documento(p_tipo) and activo
     and siguiente <= rango_final and fecha_limite >= v_hoy
   order by fecha_limite, id
   limit 1
   for update;
  if not found then
    raise exception 'No hay un CAI vigente de % para % (%-%). Registralo en Ventas › CAI.',
      v_nombre, p_punto.nombre, p_punto.establecimiento, p_punto.punto_emision;
  end if;
  update public.cai set siguiente = siguiente + 1 where id = v_cai.id;
  return v_cai;
end;
$$;

revoke all on function public.tomar_numero_cai(public.puntos_emision, text) from public, anon, authenticated;

create or replace function public.numero_cai(p_cai public.cai, p_correlativo integer)
returns text
language sql
immutable
set search_path = ''
as $$
  select p_cai.establecimiento || '-' || p_cai.punto_emision || '-' || p_cai.tipo_documento || '-'
         || lpad(p_correlativo::text, 8, '0');
$$;

-- Emisor tal como sale impreso: la empresa más la sucursal del punto.
create or replace function public.emisor_documento(p_empresa public.empresas, p_punto public.puntos_emision)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_strip_nulls(jsonb_build_object(
    'nombre', p_empresa.nombre, 'razon_social', p_empresa.razon_social, 'rtn', p_empresa.rtn,
    'telefono', p_empresa.telefono, 'correo', p_empresa.correo, 'direccion', p_empresa.direccion,
    'sucursal', p_punto.sucursal, 'direccion_sucursal', p_punto.direccion,
    'telefono_sucursal', p_punto.telefono, 'punto', p_punto.nombre
  ));
$$;

-- -----------------------------------------------------------------------------
-- 7. Emisión de facturas y cotizaciones (0005 + punto de emisión y exoneración)
-- -----------------------------------------------------------------------------

create or replace function public.emitir_documento(p_carrito uuid, p_tipo text, p_vence date default null)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_carrito public.carritos;
  v_empresa public.empresas;
  v_punto public.puntos_emision;
  v_cai public.cai;
  v_hoy date := (now() at time zone 'America/Tegucigalpa')::date;
  v_correlativo integer;
  v_numero text;
  v_doc uuid;
  v_linea record;
  v_subtotal numeric := 0;
  v_descuento numeric := 0;
  v_exento numeric := 0;
  v_gravado numeric := 0;
  v_exonerado numeric := 0;
  v_isv numeric;
  v_orden integer := 0;
  v_exoneracion jsonb;
begin
  if p_tipo not in ('cotizacion', 'factura') then
    raise exception 'Tipo de documento no válido.';
  end if;

  select * into v_carrito from public.carritos where id = p_carrito for update;
  if not found or not public.es_miembro(v_carrito.id_empresa) then
    raise exception 'El carrito no existe.';
  end if;
  if v_carrito.estado <> 'abierto' then
    raise exception 'Este carrito ya se cerró.';
  end if;
  if not exists (select 1 from public.carritos_lineas where id_carrito = p_carrito) then
    raise exception 'El carrito está vacío.';
  end if;

  select * into v_empresa from public.empresas where id = v_carrito.id_empresa;
  v_punto := public.punto_emision_actual(v_carrito.id_empresa);

  if v_carrito.exonerado then
    v_exoneracion := jsonb_strip_nulls(jsonb_build_object(
      'orden_compra', v_carrito.exo_orden_compra, 'constancia', v_carrito.exo_constancia,
      'registro_sag', v_carrito.exo_registro_sag));
  end if;

  if p_tipo = 'factura' then
    if v_empresa.rtn is null or v_empresa.razon_social is null then
      raise exception 'Para facturar, completá la razón social y el RTN del taller (módulo Taller).';
    end if;
    if v_carrito.exonerado then
      if v_carrito.cliente_rtn is null then
        raise exception 'Una factura exonerada lleva el RTN del cliente.';
      end if;
      if v_carrito.exo_orden_compra is null and v_carrito.exo_constancia is null then
        raise exception 'Escribí la orden de compra exenta o la constancia de registro de exonerado.';
      end if;
    end if;
    v_cai := public.tomar_numero_cai(v_punto, 'factura');
    v_correlativo := v_cai.siguiente;
    v_numero := public.numero_cai(v_cai, v_correlativo);
  else
    insert into public.correlativos (id_empresa, tipo) values (v_carrito.id_empresa, p_tipo)
    on conflict (id_empresa, tipo) do nothing;
    update public.correlativos set siguiente = siguiente + 1
     where id_empresa = v_carrito.id_empresa and tipo = p_tipo
    returning siguiente - 1 into v_correlativo;
    v_numero := 'COT-' || lpad(v_correlativo::text, 6, '0');
  end if;

  insert into public.documentos (
    id_empresa, tipo, numero, correlativo, vence,
    id_cai, cai, cai_rango, cai_fecha_limite, emisor,
    id_punto_emision, establecimiento, punto_emision,
    id_cliente, cliente_nombre, cliente_rtn, cliente_telefono, vehiculo,
    subtotal, descuento, importe_exento, importe_gravado, importe_exonerado, isv, total,
    exoneracion, notas, id_carrito
  ) values (
    v_carrito.id_empresa, p_tipo, v_numero, v_correlativo,
    case when p_tipo = 'cotizacion' then coalesce(p_vence, v_hoy + 15) end,
    v_cai.id, v_cai.cai,
    case when v_cai.id is not null then
      public.numero_cai(v_cai, v_cai.rango_inicial) || ' al ' || public.numero_cai(v_cai, v_cai.rango_final)
    end,
    v_cai.fecha_limite,
    public.emisor_documento(v_empresa, v_punto),
    v_punto.id, v_punto.establecimiento, v_punto.punto_emision,
    v_carrito.id_cliente,
    coalesce(v_carrito.cliente_nombre, 'CONSUMIDOR FINAL'),
    v_carrito.cliente_rtn, v_carrito.cliente_telefono, v_carrito.vehiculo,
    0, 0, 0, 0, 0, 0, 0,
    v_exoneracion, v_carrito.notas, v_carrito.id
  )
  returning id into v_doc;

  -- Líneas: el descuento general se combina con el de cada línea.
  for v_linea in
    select l.*, p.costo as costo_producto, coalesce(p.controla_inventario, false) as inventariable
      from public.carritos_lineas l
      left join public.productos p on p.id = l.id_producto
     where l.id_carrito = p_carrito
     order by l.orden, l.id
  loop
    declare
      v_bruto numeric := round(v_linea.cantidad * v_linea.precio, 2);
      v_neto numeric := round(v_bruto * (1 - v_linea.descuento_pct / 100) * (1 - v_carrito.descuento_pct / 100), 2);
    begin
      v_orden := v_orden + 1;
      insert into public.documentos_lineas (
        id_documento, id_empresa, id_producto, codigo, descripcion, cantidad, precio,
        descuento_pct, descuento, exento, total, costo, controla_inventario, orden
      ) values (
        v_doc, v_carrito.id_empresa, v_linea.id_producto, v_linea.codigo, v_linea.descripcion,
        v_linea.cantidad, v_linea.precio,
        round((1 - (1 - v_linea.descuento_pct / 100) * (1 - v_carrito.descuento_pct / 100)) * 100, 3),
        v_bruto - v_neto, v_linea.exento, v_neto, v_linea.costo_producto, v_linea.inventariable, v_orden
      );
      v_subtotal := v_subtotal + v_bruto;
      v_descuento := v_descuento + (v_bruto - v_neto);
      if v_linea.exento then
        v_exento := v_exento + v_neto;
      elsif v_carrito.exonerado then
        v_exonerado := v_exonerado + v_neto;
      else
        v_gravado := v_gravado + v_neto;
      end if;
    end;
  end loop;

  v_isv := round(v_gravado * 0.15, 2);
  update public.documentos
     set subtotal = v_subtotal, descuento = v_descuento, importe_exento = v_exento,
         importe_gravado = v_gravado, importe_exonerado = v_exonerado, isv = v_isv,
         total = v_exento + v_exonerado + v_gravado + v_isv
   where id = v_doc;

  -- Factura: descuenta existencias (queda en el kardex como venta).
  if p_tipo = 'factura' then
    perform set_config('wp.movimiento_tipo', 'venta', true);
    perform set_config('wp.movimiento_ref', v_numero, true);
    update public.productos p
       set existencia = p.existencia - x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.documentos_lineas
             where id_documento = v_doc and id_producto is not null and controla_inventario
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;

  update public.carritos set estado = 'cerrado', actualizado_en = now() where id = p_carrito;
  return v_doc;
end;
$$;

-- -----------------------------------------------------------------------------
-- 8. Notas de crédito y débito
-- -----------------------------------------------------------------------------

-- Saldo de una factura: total + notas de débito − notas de crédito (emitidas).
create or replace function public.saldo_factura(p_factura uuid)
returns numeric
language sql
stable
set search_path = ''
as $$
  select f.total
         + coalesce((select sum(n.total) from public.documentos n
                      where n.id_factura = f.id and n.tipo = 'nota_debito' and n.estado = 'emitido'), 0)
         - coalesce((select sum(n.total) from public.documentos n
                      where n.id_factura = f.id and n.tipo = 'nota_credito' and n.estado = 'emitido'), 0)
    from public.documentos f
   where f.id = p_factura;
$$;

/*
  Emite una nota sobre una factura emitida. Solo dueño/admin.

  p_tipo         nota_credito | nota_debito
  p_motivo_tipo  crédito: devolucion | descuento | correccion | otro
                 débito:  intereses | gastos | correccion | otro
  p_lineas       devolución: [{ "id_linea": 123, "cantidad": 1 }]  (líneas de la factura)
                 lo demás:   [{ "descripcion": "Rebaja acordada", "monto": 250.00, "exento": false }]
                 (monto sin ISV; el ISV o la exoneración siguen a la factura)
  p_reintegrar   devolución: vuelve a sumar las existencias (kardex «devolucion»).
*/
create or replace function public.emitir_nota(
  p_factura uuid,
  p_tipo text,
  p_motivo_tipo text,
  p_motivo text,
  p_lineas jsonb,
  p_reintegrar boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_factura public.documentos;
  v_empresa public.empresas;
  v_punto public.puntos_emision;
  v_cai public.cai;
  v_numero text;
  v_doc uuid;
  v_item jsonb;
  v_origen public.documentos_lineas;
  v_devuelto numeric;
  v_acreditado numeric;
  v_cantidad numeric;
  v_monto numeric;
  v_neto numeric;
  v_bruto numeric;
  v_exento_linea boolean;
  v_descripcion text;
  v_subtotal numeric := 0;
  v_descuento numeric := 0;
  v_exento numeric := 0;
  v_gravado numeric := 0;
  v_exonerado numeric := 0;
  v_isv numeric;
  v_total numeric;
  v_saldo numeric;
  v_orden integer := 0;
  v_devolucion boolean := p_motivo_tipo = 'devolucion';
  v_motivo text := nullif(regexp_replace(btrim(coalesce(p_motivo, '')), '\s+', ' ', 'g'), '');
begin
  if p_tipo not in ('nota_credito', 'nota_debito') then
    raise exception 'Tipo de nota no válido.';
  end if;
  if (p_tipo = 'nota_credito' and p_motivo_tipo not in ('devolucion', 'descuento', 'correccion', 'otro'))
     or (p_tipo = 'nota_debito' and p_motivo_tipo not in ('intereses', 'gastos', 'correccion', 'otro')) then
    raise exception 'Motivo no válido.';
  end if;
  if v_motivo is null then
    raise exception 'Escribí el motivo de la nota.';
  end if;
  if char_length(v_motivo) > 300 then
    raise exception 'El motivo es muy largo (máximo 300 caracteres).';
  end if;
  if jsonb_typeof(p_lineas) is distinct from 'array' or jsonb_array_length(p_lineas) = 0 then
    raise exception 'La nota no tiene líneas.';
  end if;
  if jsonb_array_length(p_lineas) > 100 then
    raise exception 'Máximo 100 líneas por nota.';
  end if;

  select * into v_factura from public.documentos where id = p_factura for update;
  if not found or not public.es_miembro(v_factura.id_empresa) then
    raise exception 'La factura no existe.';
  end if;
  if not public.tiene_rol(v_factura.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden emitir notas de crédito o débito.';
  end if;
  if v_factura.tipo <> 'factura' then
    raise exception 'Las notas se emiten sobre una factura.';
  end if;
  if v_factura.estado <> 'emitido' then
    raise exception 'La factura está anulada.';
  end if;

  select * into v_empresa from public.empresas where id = v_factura.id_empresa;
  v_punto := public.punto_emision_actual(v_factura.id_empresa);
  v_cai := public.tomar_numero_cai(v_punto, p_tipo);
  v_numero := public.numero_cai(v_cai, v_cai.siguiente);

  insert into public.documentos (
    id_empresa, tipo, numero, correlativo,
    id_cai, cai, cai_rango, cai_fecha_limite, emisor,
    id_punto_emision, establecimiento, punto_emision,
    id_cliente, cliente_nombre, cliente_rtn, cliente_telefono, vehiculo,
    subtotal, descuento, importe_exento, importe_gravado, importe_exonerado, isv, total,
    exoneracion, id_factura, factura_numero, factura_fecha, factura_cai,
    motivo_tipo, motivo, reintegra_inventario
  ) values (
    v_factura.id_empresa, p_tipo, v_numero, v_cai.siguiente,
    v_cai.id, v_cai.cai,
    public.numero_cai(v_cai, v_cai.rango_inicial) || ' al ' || public.numero_cai(v_cai, v_cai.rango_final),
    v_cai.fecha_limite,
    public.emisor_documento(v_empresa, v_punto),
    v_punto.id, v_punto.establecimiento, v_punto.punto_emision,
    v_factura.id_cliente, v_factura.cliente_nombre, v_factura.cliente_rtn, v_factura.cliente_telefono,
    v_factura.vehiculo,
    0, 0, 0, 0, 0, 0, 0,
    v_factura.exoneracion, v_factura.id, v_factura.numero, v_factura.fecha, v_factura.cai,
    p_motivo_tipo, v_motivo, v_devolucion and coalesce(p_reintegrar, false)
  )
  returning id into v_doc;

  for v_item in select * from jsonb_array_elements(p_lineas)
  loop
    v_orden := v_orden + 1;
    if v_devolucion then
      -- Devolución: una línea de la factura y cuántas unidades vuelven.
      if p_tipo <> 'nota_credito' or jsonb_typeof(v_item -> 'id_linea') is distinct from 'number' then
        raise exception 'Línea %: elegí qué producto de la factura se devuelve.', v_orden;
      end if;
      select * into v_origen from public.documentos_lineas
       where id = (v_item ->> 'id_linea')::bigint and id_documento = p_factura;
      if not found then
        raise exception 'Línea %: no es de esta factura.', v_orden;
      end if;
      v_cantidad := round((v_item ->> 'cantidad')::numeric, 2);
      if v_cantidad is null or v_cantidad <= 0 then
        raise exception 'Línea %: la cantidad debe ser mayor que cero.', v_orden;
      end if;
      select coalesce(sum(l.cantidad), 0), coalesce(sum(l.total), 0) into v_devuelto, v_acreditado
        from public.documentos_lineas l
        join public.documentos n on n.id = l.id_documento
       where l.id_linea_origen = v_origen.id and n.tipo = 'nota_credito' and n.estado = 'emitido';
      if v_cantidad > v_origen.cantidad - v_devuelto then
        raise exception '«%»: solo quedan % por devolver.', v_origen.descripcion,
          rtrim(rtrim(to_char(v_origen.cantidad - v_devuelto, 'FM999990.99'), '0'), '.');
      end if;
      -- Lo que queda de la línea si vuelve todo; si no, la parte proporcional.
      v_neto := case when v_cantidad = v_origen.cantidad - v_devuelto then v_origen.total - v_acreditado
                     else round(v_origen.total * v_cantidad / v_origen.cantidad, 2) end;
      v_bruto := round(v_cantidad * v_origen.precio, 2);
      if v_neto > v_bruto then
        v_bruto := v_neto;
      end if;
      v_exento_linea := v_origen.exento;
      insert into public.documentos_lineas (
        id_documento, id_empresa, id_producto, codigo, descripcion, cantidad, precio,
        descuento_pct, descuento, exento, total, costo, controla_inventario, orden, id_linea_origen
      ) values (
        v_doc, v_factura.id_empresa, v_origen.id_producto, v_origen.codigo, v_origen.descripcion,
        v_cantidad, v_origen.precio, v_origen.descuento_pct, v_bruto - v_neto, v_exento_linea, v_neto,
        v_origen.costo, v_origen.controla_inventario, v_orden, v_origen.id
      );
    else
      -- Rebaja, corrección o cargo: un monto sin ISV con su descripción.
      if v_item ? 'id_linea' then
        raise exception 'Línea %: solo una devolución usa productos de la factura.', v_orden;
      end if;
      v_descripcion := nullif(regexp_replace(btrim(coalesce(v_item ->> 'descripcion', '')), '\s+', ' ', 'g'), '');
      v_monto := round((v_item ->> 'monto')::numeric, 2);
      if v_descripcion is null or char_length(v_descripcion) > 240 then
        raise exception 'Línea %: escribí una descripción (máximo 240 caracteres).', v_orden;
      end if;
      if v_monto is null or v_monto <= 0 or v_monto > 99999999 then
        raise exception 'Línea %: el monto debe ser mayor que cero.', v_orden;
      end if;
      v_exento_linea := coalesce((v_item ->> 'exento')::boolean, false);
      v_neto := v_monto;
      v_bruto := v_monto;
      insert into public.documentos_lineas (
        id_documento, id_empresa, descripcion, cantidad, precio, descuento_pct, descuento,
        exento, total, controla_inventario, orden
      ) values (
        v_doc, v_factura.id_empresa, v_descripcion, 1, v_monto, 0, 0, v_exento_linea, v_monto, false, v_orden
      );
    end if;

    v_subtotal := v_subtotal + v_bruto;
    v_descuento := v_descuento + (v_bruto - v_neto);
    if v_exento_linea then
      v_exento := v_exento + v_neto;
    elsif v_factura.exoneracion is not null then
      v_exonerado := v_exonerado + v_neto;
    else
      v_gravado := v_gravado + v_neto;
    end if;
  end loop;

  v_isv := round(v_gravado * 0.15, 2);
  v_total := v_exento + v_exonerado + v_gravado + v_isv;

  if p_tipo = 'nota_credito' then
    -- saldo_factura ya no cuenta esta nota (sus totales siguen en cero).
    v_saldo := public.saldo_factura(p_factura);
    -- Diferencias de redondeo del ISV al devolver todo (un par de centavos).
    if v_total > v_saldo and v_total - v_saldo <= 0.02 and v_isv >= v_total - v_saldo then
      v_isv := v_isv - (v_total - v_saldo);
      v_total := v_saldo;
    end if;
    if v_total > v_saldo then
      raise exception 'La nota (L %) supera lo que queda de la factura (L %).',
        to_char(v_total, 'FM999,999,990.00'), to_char(greatest(v_saldo, 0), 'FM999,999,990.00');
    end if;
  end if;

  update public.documentos
     set subtotal = v_subtotal, descuento = v_descuento, importe_exento = v_exento,
         importe_gravado = v_gravado, importe_exonerado = v_exonerado, isv = v_isv, total = v_total
   where id = v_doc;

  -- Devolución con reintegro: las piezas vuelven al inventario.
  if v_devolucion and coalesce(p_reintegrar, false) then
    perform set_config('wp.movimiento_tipo', 'devolucion', true);
    perform set_config('wp.movimiento_ref', v_numero, true);
    update public.productos p
       set existencia = p.existencia + x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.documentos_lineas
             where id_documento = v_doc and id_producto is not null and controla_inventario
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;

  return v_doc;
end;
$$;

-- -----------------------------------------------------------------------------
-- 9. Anulación y copia a carrito (0005 + notas)
-- -----------------------------------------------------------------------------

create or replace function public.anular_documento(p_documento uuid, p_motivo text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_doc public.documentos;
  v_signo integer;
begin
  select * into v_doc from public.documentos where id = p_documento for update;
  if not found or not public.es_miembro(v_doc.id_empresa) then
    raise exception 'El documento no existe.';
  end if;
  if not public.tiene_rol(v_doc.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden anular documentos.';
  end if;
  if v_doc.estado = 'anulado' then
    raise exception 'El documento ya está anulado.';
  end if;
  if nullif(btrim(p_motivo), '') is null then
    raise exception 'Escribí el motivo de la anulación.';
  end if;
  if v_doc.tipo = 'factura' and exists (
       select 1 from public.documentos n where n.id_factura = v_doc.id and n.estado = 'emitido') then
    raise exception 'Esta factura tiene notas de crédito o débito vigentes: anulalas primero.';
  end if;

  update public.documentos
     set estado = 'anulado', anulado_en = now(), anulado_por = auth.uid(), motivo_anulacion = btrim(p_motivo)
   where id = p_documento;

  -- Factura: las piezas vuelven. Devolución reintegrada: vuelven a salir.
  v_signo := case when v_doc.tipo = 'factura' then 1
                  when v_doc.tipo = 'nota_credito' and v_doc.reintegra_inventario then -1 end;
  if v_signo is not null then
    perform set_config('wp.movimiento_tipo', 'anulacion', true);
    perform set_config('wp.movimiento_ref', v_doc.numero, true);
    update public.productos p
       set existencia = p.existencia + v_signo * x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.documentos_lineas
             where id_documento = p_documento and id_producto is not null and controla_inventario
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;
end;
$$;

create or replace function public.carrito_desde_documento(p_documento uuid)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  v_doc public.documentos;
  v_carrito uuid;
  v_origen public.carritos;
begin
  select * into v_doc from public.documentos where id = p_documento;
  if not found then
    raise exception 'El documento no existe.';
  end if;
  if v_doc.tipo not in ('cotizacion', 'factura') then
    raise exception 'Solo una cotización o una factura se pueden pasar a un carrito.';
  end if;
  select * into v_origen from public.carritos where id = v_doc.id_carrito;
  -- Los descuentos ya se aprobaron al emitir el documento: se copian tal cual.
  perform set_config('wp.copia_documento', 'si', true);

  insert into public.carritos (id_empresa, nombre, id_cliente, cliente_nombre, cliente_rtn, cliente_telefono,
                               id_marca, id_modelo, id_modelo_anio, id_especificacion, notas)
  values (v_doc.id_empresa, v_doc.numero, null,
          nullif(v_doc.cliente_nombre, 'CONSUMIDOR FINAL'), v_doc.cliente_rtn, v_doc.cliente_telefono,
          v_origen.id_marca, v_origen.id_modelo, v_origen.id_modelo_anio, v_origen.id_especificacion, v_doc.notas)
  returning id into v_carrito;

  update public.carritos set id_cliente = v_doc.id_cliente where id = v_carrito and v_doc.id_cliente is not null
    and exists (select 1 from public.clientes c where c.id = v_doc.id_cliente);

  -- La exoneración del documento (la orden de compra exenta es de cada compra: no se copia).
  update public.carritos
     set exonerado = v_doc.exoneracion is not null,
         exo_constancia = v_doc.exoneracion ->> 'constancia',
         exo_registro_sag = v_doc.exoneracion ->> 'registro_sag'
   where id = v_carrito and v_doc.exoneracion is not null;

  insert into public.carritos_lineas (id_carrito, id_producto, codigo, descripcion, cantidad, precio, descuento_pct, exento, orden)
  select v_carrito, l.id_producto, l.codigo, l.descripcion, l.cantidad, l.precio, l.descuento_pct, l.exento, l.orden
    from public.documentos_lineas l
   where l.id_documento = p_documento
   order by l.orden;

  perform set_config('wp.copia_documento', '', true);
  return v_carrito;
end;
$$;

-- -----------------------------------------------------------------------------
-- 10. Permisos y RLS
-- -----------------------------------------------------------------------------

revoke all on public.puntos_emision from anon, authenticated;
grant select, insert, delete on public.puntos_emision to authenticated;
grant update (establecimiento, sucursal, direccion, telefono, punto_emision, nombre, predeterminado, activo)
  on public.puntos_emision to authenticated;

alter table public.puntos_emision enable row level security;

drop policy if exists empresa_lectura on public.puntos_emision;
create policy empresa_lectura on public.puntos_emision
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists empresa_escritura on public.puntos_emision;
create policy empresa_escritura on public.puntos_emision
  for all to authenticated
  using (public.tiene_rol(id_empresa, array['dueno', 'admin']))
  with check (public.tiene_rol(id_empresa, array['dueno', 'admin']));

revoke all on function public.emitir_nota(uuid, text, text, text, jsonb, boolean) from public, anon;
grant execute on function public.emitir_nota(uuid, text, text, text, jsonb, boolean) to authenticated;
revoke all on function public.saldo_factura(uuid) from public, anon;
grant execute on function public.saldo_factura(uuid) to authenticated;

-- Auditoría (0011).
do $$
begin
  if to_regprocedure('public.registrar_cambio()') is not null then
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.puntos_emision '
            'for each row execute function public.registrar_cambio()';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 11. Vistas
-- -----------------------------------------------------------------------------

create or replace view public.v_puntos_emision with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.establecimiento || '-' || p.punto_emision as codigo,
       p.establecimiento,
       p.sucursal,
       p.punto_emision,
       p.nombre,
       p.establecimiento || '-' || p.punto_emision || ' · ' || p.nombre as etiqueta,
       p.direccion,
       p.telefono,
       p.predeterminado,
       p.activo,
       (select count(*) from public.empresas_usuarios eu
         where eu.id_punto_emision = p.id and eu.activo)::integer as usuarios,
       (select count(*) from public.cai c
         where c.id_punto_emision = p.id and c.activo and c.siguiente <= c.rango_final
           and c.fecha_limite >= (now() at time zone 'America/Tegucigalpa')::date)::integer as cai_vigentes,
       p.creado_en
  from public.puntos_emision p;

create or replace view public.v_cai with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.cai,
       c.tipo_documento,
       c.establecimiento,
       c.punto_emision,
       c.rango_inicial,
       c.rango_final,
       c.siguiente,
       greatest(c.rango_final - c.siguiente + 1, 0) as disponibles,
       round((c.siguiente - c.rango_inicial)::numeric / (c.rango_final - c.rango_inicial + 1) * 100, 1) as usado_pct,
       c.fecha_limite,
       (c.fecha_limite - (now() at time zone 'America/Tegucigalpa')::date) as dias_restantes,
       c.activo,
       (c.activo and c.siguiente <= c.rango_final
          and c.fecha_limite >= (now() at time zone 'America/Tegucigalpa')::date) as vigente,
       c.creado_en,
       c.id_punto_emision,
       p.nombre as punto
  from public.cai c
  left join public.puntos_emision p on p.id = c.id_punto_emision;

create or replace view public.v_miembros with (security_invoker = true) as
select eu.id_empresa,
       eu.id_usuario,
       u.nombre,
       u.correo,
       u.telefono,
       u.avatar_url,
       eu.rol,
       eu.activo,
       eu.creado_en,
       eu.id_punto_emision,
       p.establecimiento || '-' || p.punto_emision || ' · ' || p.nombre as punto
  from public.empresas_usuarios eu
  join public.usuarios u on u.id = eu.id_usuario
  left join public.puntos_emision p on p.id = eu.id_punto_emision;

create or replace view public.v_clientes with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.nombre,
       c.rtn,
       c.telefono,
       c.correo,
       c.direccion,
       c.notas,
       c.activo,
       (select count(*) from public.documentos d where d.id_cliente = c.id and d.tipo = 'factura' and d.estado = 'emitido')::integer as facturas,
       (select max(d.fecha) from public.documentos d where d.id_cliente = c.id) as ultima_compra,
       c.creado_en,
       c.exonerado,
       c.exo_constancia,
       c.exo_registro_sag
  from public.clientes c;

create or replace view public.v_carritos with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.nombre,
       c.id_cliente,
       c.cliente_nombre,
       c.cliente_rtn,
       c.cliente_telefono,
       c.id_marca,
       c.id_modelo,
       c.id_modelo_anio,
       c.id_especificacion,
       c.vehiculo,
       c.descuento_pct,
       c.notas,
       c.estado,
       coalesce(t.lineas, 0)::integer as lineas,
       coalesce(t.unidades, 0) as unidades,
       u.nombre as creado_por_nombre,
       c.creado_en,
       c.actualizado_en,
       c.exonerado,
       c.exo_orden_compra,
       c.exo_constancia,
       c.exo_registro_sag
  from public.carritos c
  left join public.usuarios u on u.id = c.creado_por
  left join (
    select id_carrito, count(*) as lineas, sum(cantidad) as unidades
      from public.carritos_lineas group by id_carrito
  ) t on t.id_carrito = c.id;

create or replace view public.v_documentos with (security_invoker = true) as
select d.id,
       d.id_empresa,
       d.tipo,
       d.numero,
       d.fecha,
       d.vence,
       d.cliente_nombre,
       d.cliente_rtn,
       d.vehiculo,
       d.subtotal,
       d.descuento,
       d.isv,
       d.total,
       d.estado,
       d.cai,
       u.nombre as vendedor,
       d.creado_en,
       d.importe_exonerado,
       d.id_factura,
       d.factura_numero,
       d.motivo_tipo,
       d.establecimiento || '-' || d.punto_emision as punto,
       d.exoneracion is not null as exonerada
  from public.documentos d
  left join public.usuarios u on u.id = d.creado_por;

create or replace view public.v_documentos_lineas with (security_invoker = true) as
select l.id, l.id_documento, l.id_empresa, l.id_producto, l.codigo, l.descripcion, l.cantidad,
       l.precio, l.descuento_pct, l.descuento, l.exento, l.total, l.orden, l.id_linea_origen
  from public.documentos_lineas l;

-- Líneas de una factura con lo ya devuelto en notas de crédito emitidas.
create or replace view public.v_lineas_acreditables with (security_invoker = true) as
select l.id,
       l.id_documento,
       l.id_empresa,
       l.id_producto,
       l.codigo,
       l.descripcion,
       l.cantidad,
       l.precio,
       l.descuento_pct,
       l.exento,
       l.total,
       l.controla_inventario,
       l.orden,
       coalesce(n.devuelto, 0) as devuelto,
       coalesce(n.acreditado, 0) as acreditado
  from public.documentos_lineas l
  left join (
    select nl.id_linea_origen, sum(nl.cantidad) as devuelto, sum(nl.total) as acreditado
      from public.documentos_lineas nl
      join public.documentos nd on nd.id = nl.id_documento
     where nd.tipo = 'nota_credito' and nd.estado = 'emitido' and nl.id_linea_origen is not null
     group by nl.id_linea_origen
  ) n on n.id_linea_origen = l.id;

revoke all on public.v_puntos_emision, public.v_lineas_acreditables from anon;
grant select on public.v_puntos_emision, public.v_lineas_acreditables to authenticated;

-- -----------------------------------------------------------------------------
-- 12. Documentación en la base
-- -----------------------------------------------------------------------------

comment on table public.puntos_emision is
  'Establecimientos (sucursales, código de 3 dígitos) y puntos de emisión (cajas). Cada CAI es de un punto; cada persona emite con el suyo o con el predeterminado.';
comment on column public.empresas_usuarios.id_punto_emision is 'Punto de emisión con el que factura esta persona (null = el predeterminado).';
comment on column public.documentos.importe_exonerado is 'Lo gravado vendido a un exonerado: no lleva ISV.';
comment on column public.documentos.exoneracion is '{orden_compra, constancia, registro_sag} si el documento es exonerado.';
comment on column public.documentos.id_factura is 'Notas de crédito/débito: factura que modifican.';
comment on function public.emitir_nota(uuid, text, text, text, jsonb, boolean) is
  'Nota de crédito (devolución, descuento, corrección) o de débito sobre una factura emitida. Solo dueño/admin.';
comment on function public.punto_emision_actual(uuid) is 'Punto de emisión de quien llama: el suyo activo o el predeterminado.';

commit;
