-- =============================================================================
-- 0021 · Compras, proveedores y cuentas por pagar
-- -----------------------------------------------------------------------------
-- ESTADO: PENDIENTE
-- Idempotente y atómica. Requiere 0018 (caja).
--
-- Qué crea o cambia:
--   · proveedores                 Por empresa: nombre, RTN, contacto, plazo de
--                                 crédito. Los administran dueño/admin.
--   · compras, compras_lineas     Factura del proveedor registrada: de
--                                 productos (suben existencias y costo promedio,
--                                 kardex «compra») o de gasto (sin inventario).
--                                 Contado o crédito. Número interno COMP-000001.
--   · pagos_proveedores,          Pagos a proveedores (PAG-000001) repartidos
--     pagos_proveedores_aplicaciones  entre sus compras al crédito.
--   · registrar_compra(), anular_compra(), registrar_pago_proveedor(),
--     anular_pago_proveedor().
--   · resumen_turno(), v_caja_movimientos   Lo pagado en efectivo desde la caja
--                                 (compras de contado y pagos) sale del turno.
--   · Vistas v_proveedores, v_compras, v_cuentas_pagar, v_cuentas_proveedores,
--     v_pagos_proveedores, v_pagos_proveedores_aplicaciones.
--
-- Reglas (docs/negocio.md §3.10):
--   · Montos sin ISV por línea; ISV 15 % sobre lo gravado (se puede corregir al
--     de la factura del proveedor, hasta el 18 %). El ISV de compras es crédito
--     fiscal (lo usa la contabilidad, 0022).
--   · Una misma factura de proveedor (proveedor + número) no se registra dos veces.
--   · Pendiente de una compra al crédito = total − pagos vigentes.
--   · Anular una compra de productos saca las existencias (el costo promedio no
--     se recalcula). No se anula con pagos vigentes.
--   · Solo dueño/admin registran o anulan compras y pagos.
-- =============================================================================

begin;

create or replace function pg_temp.restriccion_0021(tabla regclass, nombre text, definicion text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = tabla and conname = nombre) then
    execute format('alter table %s add constraint %I %s', tabla, nombre, definicion);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Proveedores
-- -----------------------------------------------------------------------------

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  nombre text not null,
  rtn text,
  telefono text,
  correo text,
  direccion text,
  contacto text,
  dias_credito integer not null default 0,
  notas text,
  activo boolean not null default true,
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now()
);

create index if not exists proveedores_id_empresa_idx on public.proveedores (id_empresa, nombre);
create index if not exists proveedores_creado_por_idx on public.proveedores (creado_por);
create unique index if not exists proveedores_rtn_key on public.proveedores (id_empresa, rtn) where rtn is not null;

select pg_temp.restriccion_0021('public.proveedores', 'proveedores_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 160)$$);
select pg_temp.restriccion_0021('public.proveedores', 'proveedores_rtn_check',
  $$check (rtn is null or rtn ~ '^\d{14}$')$$);
select pg_temp.restriccion_0021('public.proveedores', 'proveedores_textos_check',
  $$check ((telefono is null or char_length(telefono) <= 30) and (correo is null or char_length(correo) <= 120)
           and (direccion is null or char_length(direccion) <= 200) and (contacto is null or char_length(contacto) <= 120)
           and (notas is null or char_length(notas) <= 500))$$);
select pg_temp.restriccion_0021('public.proveedores', 'proveedores_dias_check',
  $$check (dias_credito between 0 and 365)$$);

create or replace function public.tg_normalizar_proveedor()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de un proveedor.';
  end if;
  new.nombre := upper(regexp_replace(btrim(new.nombre), '\s+', ' ', 'g'));
  new.rtn := nullif(regexp_replace(coalesce(new.rtn, ''), '\D', '', 'g'), '');
  new.telefono := nullif(btrim(new.telefono), '');
  new.correo := nullif(lower(btrim(new.correo)), '');
  new.direccion := nullif(btrim(new.direccion), '');
  new.contacto := nullif(btrim(new.contacto), '');
  new.notas := nullif(btrim(new.notas), '');
  return new;
end;
$$;

create or replace trigger a_normalizar
  before insert or update on public.proveedores
  for each row execute function public.tg_normalizar_proveedor();

-- -----------------------------------------------------------------------------
-- 2. Compras
-- -----------------------------------------------------------------------------

create table if not exists public.compras (
  id uuid primary key default gen_random_uuid(),
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  numero text not null,
  correlativo integer not null,
  tipo text not null default 'inventario',
  id_proveedor bigint not null references public.proveedores (id),
  proveedor_nombre text not null,
  proveedor_rtn text,
  documento text,
  cai_proveedor text,
  fecha date not null,
  condicion text not null default 'contado',
  vence date,
  forma_pago text,
  referencia_pago text,
  subtotal numeric(14, 2) not null default 0,
  importe_exento numeric(14, 2) not null default 0,
  importe_gravado numeric(14, 2) not null default 0,
  isv numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  notas text,
  estado text not null default 'emitido',
  anulado_en timestamptz,
  anulado_por uuid references public.usuarios (id) on delete set null,
  motivo_anulacion text,
  id_turno uuid references public.cajas_turnos (id),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now(),
  constraint compras_numero_key unique (id_empresa, numero)
);

create index if not exists compras_empresa_fecha_idx on public.compras (id_empresa, fecha desc);
create index if not exists compras_id_proveedor_idx on public.compras (id_proveedor);
create index if not exists compras_id_turno_idx on public.compras (id_turno);
create index if not exists compras_creado_por_idx on public.compras (creado_por);
create index if not exists compras_anulado_por_idx on public.compras (anulado_por);
-- La misma factura de un proveedor no entra dos veces (las anuladas no cuentan).
create unique index if not exists compras_documento_key
  on public.compras (id_empresa, id_proveedor, upper(documento))
  where documento is not null and estado = 'emitido';

select pg_temp.restriccion_0021('public.compras', 'compras_tipo_check', $$check (tipo in ('inventario', 'gasto'))$$);
select pg_temp.restriccion_0021('public.compras', 'compras_condicion_check',
  $$check (condicion in ('contado', 'credito')
           and (condicion = 'credito') = (vence is not null)
           and (condicion = 'contado') = (forma_pago is not null))$$);
select pg_temp.restriccion_0021('public.compras', 'compras_forma_check',
  $$check (forma_pago is null or forma_pago in ('efectivo', 'tarjeta', 'transferencia', 'deposito', 'cheque', 'otro'))$$);
select pg_temp.restriccion_0021('public.compras', 'compras_turno_check',
  $$check (id_turno is null or forma_pago = 'efectivo')$$);
select pg_temp.restriccion_0021('public.compras', 'compras_estado_check', $$check (estado in ('emitido', 'anulado'))$$);
select pg_temp.restriccion_0021('public.compras', 'compras_montos_check',
  $$check (subtotal >= 0 and importe_exento >= 0 and importe_gravado >= 0 and isv >= 0 and total >= 0)$$);
select pg_temp.restriccion_0021('public.compras', 'compras_textos_check',
  $$check ((documento is null or char_length(documento) <= 40) and (cai_proveedor is null or char_length(cai_proveedor) <= 40)
           and (referencia_pago is null or char_length(referencia_pago) <= 80) and (notas is null or char_length(notas) <= 300))$$);

create table if not exists public.compras_lineas (
  id bigint generated by default as identity primary key,
  id_compra uuid not null references public.compras (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_producto bigint references public.productos (id),
  codigo text,
  descripcion text not null,
  cantidad numeric(14, 2) not null,
  costo numeric(14, 2) not null,
  exento boolean not null default false,
  total numeric(14, 2) not null,
  orden integer not null default 0
);

create index if not exists compras_lineas_id_compra_idx on public.compras_lineas (id_compra);
create index if not exists compras_lineas_id_empresa_idx on public.compras_lineas (id_empresa);
create index if not exists compras_lineas_id_producto_idx on public.compras_lineas (id_producto);

select pg_temp.restriccion_0021('public.compras_lineas', 'compras_lineas_montos_check',
  $$check (cantidad > 0 and costo >= 0 and total >= 0 and char_length(descripcion) <= 240)$$);

-- -----------------------------------------------------------------------------
-- 3. Pagos a proveedores
-- -----------------------------------------------------------------------------

create table if not exists public.pagos_proveedores (
  id uuid primary key default gen_random_uuid(),
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  numero text not null,
  correlativo integer not null,
  id_proveedor bigint not null references public.proveedores (id),
  proveedor_nombre text not null,
  fecha timestamptz not null default now(),
  monto numeric(14, 2) not null,
  forma_pago text not null,
  referencia text,
  notas text,
  estado text not null default 'emitido',
  anulado_en timestamptz,
  anulado_por uuid references public.usuarios (id) on delete set null,
  motivo_anulacion text,
  id_turno uuid references public.cajas_turnos (id),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now(),
  constraint pagos_proveedores_numero_key unique (id_empresa, numero)
);

create index if not exists pagos_proveedores_empresa_fecha_idx on public.pagos_proveedores (id_empresa, fecha desc);
create index if not exists pagos_proveedores_id_proveedor_idx on public.pagos_proveedores (id_proveedor);
create index if not exists pagos_proveedores_id_turno_idx on public.pagos_proveedores (id_turno);
create index if not exists pagos_proveedores_creado_por_idx on public.pagos_proveedores (creado_por);
create index if not exists pagos_proveedores_anulado_por_idx on public.pagos_proveedores (anulado_por);

select pg_temp.restriccion_0021('public.pagos_proveedores', 'pagos_proveedores_monto_check', $$check (monto > 0)$$);
select pg_temp.restriccion_0021('public.pagos_proveedores', 'pagos_proveedores_forma_check',
  $$check (forma_pago in ('efectivo', 'tarjeta', 'transferencia', 'deposito', 'cheque', 'otro')
           and (id_turno is null or forma_pago = 'efectivo'))$$);
select pg_temp.restriccion_0021('public.pagos_proveedores', 'pagos_proveedores_estado_check',
  $$check (estado in ('emitido', 'anulado'))$$);
select pg_temp.restriccion_0021('public.pagos_proveedores', 'pagos_proveedores_textos_check',
  $$check ((referencia is null or char_length(referencia) <= 80) and (notas is null or char_length(notas) <= 300))$$);

create table if not exists public.pagos_proveedores_aplicaciones (
  id bigint generated by default as identity primary key,
  id_pago uuid not null references public.pagos_proveedores (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_compra uuid not null references public.compras (id),
  monto numeric(14, 2) not null
);

create index if not exists pagos_proveedores_aplicaciones_id_pago_idx on public.pagos_proveedores_aplicaciones (id_pago);
create index if not exists pagos_proveedores_aplicaciones_id_compra_idx on public.pagos_proveedores_aplicaciones (id_compra);
create index if not exists pagos_proveedores_aplicaciones_id_empresa_idx on public.pagos_proveedores_aplicaciones (id_empresa);

select pg_temp.restriccion_0021('public.pagos_proveedores_aplicaciones', 'pagos_proveedores_aplicaciones_monto_check',
  $$check (monto > 0)$$);

-- -----------------------------------------------------------------------------
-- 4. Cuentas por pagar
-- -----------------------------------------------------------------------------

-- Una fila por compra al crédito vigente, con lo que queda por pagar.
create or replace view public.v_cuentas_pagar with (security_invoker = true) as
with base as (
  select c.id, c.id_empresa, c.numero, c.documento, c.fecha, c.vence, c.id_proveedor, c.proveedor_nombre, c.total,
         coalesce((select sum(a.monto) from public.pagos_proveedores_aplicaciones a
                     join public.pagos_proveedores p on p.id = a.id_pago
                    where a.id_compra = c.id and p.estado = 'emitido'), 0) as pagado,
         (now() at time zone 'America/Tegucigalpa')::date as hoy
    from public.compras c
   where c.condicion = 'credito' and c.estado = 'emitido'
)
select b.id, b.id_empresa, b.numero, b.documento, b.fecha, b.vence, b.id_proveedor, b.proveedor_nombre,
       b.total, b.pagado,
       b.total - b.pagado as pendiente,
       greatest(b.hoy - b.vence, 0) as dias_vencida,
       case when b.total - b.pagado <= 0 then 'pagada'
            when b.hoy > b.vence then 'vencida'
            when b.vence - b.hoy <= 7 then 'por_vencer'
            else 'al_dia' end as estado
  from base b;

-- -----------------------------------------------------------------------------
-- 5. Registrar y anular compras
-- -----------------------------------------------------------------------------

/*
  p_compra: {
    tipo: inventario | gasto, id_proveedor, documento?, cai?, fecha (AAAA-MM-DD),
    condicion: contado | credito, vence? (crédito; si falta: fecha + plazo del proveedor),
    forma_pago? (contado), referencia?, de_caja? (efectivo desde la caja abierta),
    isv? (el de la factura del proveedor; si falta, 15 % de lo gravado), notas?,
    lineas: inventario [{ id_producto, cantidad, costo, exento? }]
            gasto      [{ descripcion, monto, exento? }]
  }
  Costos y montos sin ISV. Devuelve el id de la compra.
*/
create or replace function public.registrar_compra(p_empresa uuid, p_compra jsonb)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_proveedor public.proveedores;
  v_producto public.productos;
  v_tipo text := coalesce(p_compra ->> 'tipo', 'inventario');
  v_condicion text := coalesce(p_compra ->> 'condicion', 'contado');
  v_fecha date := coalesce(nullif(p_compra ->> 'fecha', '')::date, (now() at time zone 'America/Tegucigalpa')::date);
  v_vence date;
  v_forma text := nullif(p_compra ->> 'forma_pago', '');
  v_documento text := nullif(upper(btrim(coalesce(p_compra ->> 'documento', ''))), '');
  v_turno uuid;
  v_correlativo integer;
  v_numero text;
  v_compra uuid;
  v_item jsonb;
  v_orden integer := 0;
  v_cantidad numeric;
  v_costo numeric;
  v_neto numeric;
  v_exento boolean;
  v_descripcion text;
  v_subtotal numeric := 0;
  v_exento_total numeric := 0;
  v_gravado numeric := 0;
  v_isv numeric;
  v_isv_dado numeric := nullif(p_compra ->> 'isv', '')::numeric;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden registrar compras.';
  end if;
  if v_tipo not in ('inventario', 'gasto') then
    raise exception 'Tipo de compra no válido.';
  end if;
  if v_condicion not in ('contado', 'credito') then
    raise exception 'Condición no válida.';
  end if;
  if v_fecha > (now() at time zone 'America/Tegucigalpa')::date + 1 then
    raise exception 'La fecha de la compra no puede ser futura.';
  end if;
  if jsonb_typeof(p_compra -> 'lineas') is distinct from 'array' or jsonb_array_length(p_compra -> 'lineas') = 0 then
    raise exception 'La compra no tiene líneas.';
  end if;
  if jsonb_array_length(p_compra -> 'lineas') > 300 then
    raise exception 'Máximo 300 líneas por compra.';
  end if;

  select * into v_proveedor from public.proveedores
   where id = nullif(p_compra ->> 'id_proveedor', '')::bigint and id_empresa = p_empresa;
  if not found then
    raise exception 'Elegí el proveedor.';
  end if;

  if v_documento is not null and exists (
       select 1 from public.compras c
        where c.id_empresa = p_empresa and c.id_proveedor = v_proveedor.id
          and upper(c.documento) = v_documento and c.estado = 'emitido') then
    raise exception 'La factura % de % ya está registrada.', v_documento, v_proveedor.nombre;
  end if;

  if v_condicion = 'credito' then
    v_forma := null;
    v_vence := coalesce(nullif(p_compra ->> 'vence', '')::date, v_fecha + v_proveedor.dias_credito);
    if v_vence < v_fecha then
      raise exception 'El vencimiento no puede ser antes de la fecha de la compra.';
    end if;
  else
    if v_forma is null or v_forma not in ('efectivo', 'tarjeta', 'transferencia', 'deposito', 'cheque', 'otro') then
      raise exception 'Elegí la forma de pago.';
    end if;
    -- Efectivo desde la caja: sale del turno abierto del punto de quien registra.
    if v_forma = 'efectivo' and coalesce((p_compra ->> 'de_caja')::boolean, false) then
      v_turno := public.turno_abierto((public.punto_emision_actual(p_empresa)).id);
      if v_turno is null then
        raise exception 'No hay caja abierta en tu punto: abrila o desmarcá «Sale de la caja».';
      end if;
    end if;
  end if;

  insert into public.correlativos (id_empresa, tipo) values (p_empresa, 'compra')
  on conflict (id_empresa, tipo) do nothing;
  update public.correlativos set siguiente = siguiente + 1
   where id_empresa = p_empresa and tipo = 'compra'
  returning siguiente - 1 into v_correlativo;
  v_numero := 'COMP-' || lpad(v_correlativo::text, 6, '0');

  insert into public.compras (
    id_empresa, numero, correlativo, tipo, id_proveedor, proveedor_nombre, proveedor_rtn,
    documento, cai_proveedor, fecha, condicion, vence, forma_pago, referencia_pago, notas, id_turno
  ) values (
    p_empresa, v_numero, v_correlativo, v_tipo, v_proveedor.id, v_proveedor.nombre, v_proveedor.rtn,
    v_documento, nullif(upper(btrim(coalesce(p_compra ->> 'cai', ''))), ''), v_fecha, v_condicion, v_vence, v_forma,
    case when v_forma is not null then nullif(btrim(coalesce(p_compra ->> 'referencia', '')), '') end,
    nullif(btrim(coalesce(p_compra ->> 'notas', '')), ''), v_turno
  )
  returning id into v_compra;

  -- El kardex toma el tipo y la referencia de estas variables (solo en esta transacción).
  if v_tipo = 'inventario' then
    perform set_config('wp.movimiento_tipo', 'compra', true);
    perform set_config('wp.movimiento_ref', v_numero || coalesce(' · ' || v_documento, ''), true);
  end if;

  for v_item in select * from jsonb_array_elements(p_compra -> 'lineas')
  loop
    v_orden := v_orden + 1;
    v_exento := coalesce((v_item ->> 'exento')::boolean, false);
    if v_tipo = 'inventario' then
      v_cantidad := round((v_item ->> 'cantidad')::numeric, 2);
      v_costo := round((v_item ->> 'costo')::numeric, 2);
      if v_cantidad is null or v_cantidad <= 0 then
        raise exception 'Línea %: la cantidad debe ser mayor que cero.', v_orden;
      end if;
      if v_costo is null or v_costo < 0 then
        raise exception 'Línea %: escribí el costo unitario sin ISV.', v_orden;
      end if;
      select * into v_producto from public.productos
       where id = nullif(v_item ->> 'id_producto', '')::bigint and id_empresa = p_empresa
         for update;
      if not found then
        raise exception 'Línea %: el producto no existe en tu inventario.', v_orden;
      end if;
      if not v_producto.controla_inventario then
        raise exception '«%» es un servicio: no lleva inventario.', v_producto.nombre;
      end if;
      v_neto := round(v_cantidad * v_costo, 2);
      insert into public.compras_lineas (id_compra, id_empresa, id_producto, codigo, descripcion, cantidad, costo, exento, total, orden)
      values (v_compra, p_empresa, v_producto.id, v_producto.codigo, v_producto.nombre, v_cantidad, v_costo, v_exento, v_neto, v_orden);
      -- Existencias y costo promedio ponderado (si no había existencia, manda el costo nuevo).
      update public.productos
         set existencia = existencia + v_cantidad,
             costo = case when greatest(v_producto.existencia, 0) = 0 then v_costo
                          else round((v_producto.existencia * v_producto.costo + v_cantidad * v_costo)
                                     / (v_producto.existencia + v_cantidad), 2) end
       where id = v_producto.id;
    else
      if v_item ? 'id_producto' then
        raise exception 'Línea %: una compra de gasto no lleva productos.', v_orden;
      end if;
      v_descripcion := nullif(regexp_replace(btrim(coalesce(v_item ->> 'descripcion', '')), '\s+', ' ', 'g'), '');
      v_neto := round((v_item ->> 'monto')::numeric, 2);
      if v_descripcion is null or char_length(v_descripcion) > 240 then
        raise exception 'Línea %: escribí una descripción (máximo 240 caracteres).', v_orden;
      end if;
      if v_neto is null or v_neto <= 0 or v_neto > 99999999 then
        raise exception 'Línea %: el monto debe ser mayor que cero.', v_orden;
      end if;
      insert into public.compras_lineas (id_compra, id_empresa, descripcion, cantidad, costo, exento, total, orden)
      values (v_compra, p_empresa, v_descripcion, 1, v_neto, v_exento, v_neto, v_orden);
    end if;
    v_subtotal := v_subtotal + v_neto;
    if v_exento then
      v_exento_total := v_exento_total + v_neto;
    else
      v_gravado := v_gravado + v_neto;
    end if;
  end loop;

  perform set_config('wp.movimiento_tipo', '', true);
  perform set_config('wp.movimiento_ref', '', true);

  -- ISV: el de la factura del proveedor (entre 0 y el 18 % de lo gravado) o el 15 %.
  v_isv := round(v_gravado * 0.15, 2);
  if v_isv_dado is not null then
    v_isv_dado := round(v_isv_dado, 2);
    if v_isv_dado < 0 or v_isv_dado > round(v_gravado * 0.18, 2) + 0.05 then
      raise exception 'El ISV (L %) no cuadra con lo gravado (L %).',
        to_char(v_isv_dado, 'FM999,999,990.00'), to_char(v_gravado, 'FM999,999,990.00');
    end if;
    v_isv := v_isv_dado;
  end if;

  update public.compras
     set subtotal = v_subtotal, importe_exento = v_exento_total, importe_gravado = v_gravado,
         isv = v_isv, total = v_subtotal + v_isv
   where id = v_compra;

  return v_compra;
end;
$$;

create or replace function public.anular_compra(p_compra uuid, p_motivo text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_compra public.compras;
begin
  select * into v_compra from public.compras where id = p_compra for update;
  if not found or not public.es_miembro(v_compra.id_empresa) then
    raise exception 'La compra no existe.';
  end if;
  if not public.tiene_rol(v_compra.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden anular compras.';
  end if;
  if v_compra.estado = 'anulado' then
    raise exception 'La compra ya está anulada.';
  end if;
  if nullif(btrim(p_motivo), '') is null then
    raise exception 'Escribí el motivo de la anulación.';
  end if;
  if exists (select 1 from public.pagos_proveedores_aplicaciones a
               join public.pagos_proveedores p on p.id = a.id_pago
              where a.id_compra = v_compra.id and p.estado = 'emitido') then
    raise exception 'Esta compra tiene pagos: anulá primero los pagos al proveedor.';
  end if;

  update public.compras
     set estado = 'anulado', anulado_en = now(), anulado_por = auth.uid(), motivo_anulacion = btrim(p_motivo)
   where id = p_compra;

  -- Compra de productos: las piezas vuelven a salir (el costo promedio queda como está).
  if v_compra.tipo = 'inventario' then
    perform set_config('wp.movimiento_tipo', 'anulacion', true);
    perform set_config('wp.movimiento_ref', v_compra.numero, true);
    update public.productos p
       set existencia = p.existencia - x.cantidad
      from (select id_producto, sum(cantidad) as cantidad
              from public.compras_lineas
             where id_compra = p_compra and id_producto is not null
             group by id_producto) x
     where p.id = x.id_producto;
    perform set_config('wp.movimiento_tipo', '', true);
    perform set_config('wp.movimiento_ref', '', true);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Pagos a proveedores
-- -----------------------------------------------------------------------------

/*
  Pago a un proveedor. p_aplicaciones null = a las compras que vencen primero;
  [{ "id_compra": "…", "monto": 500 }] = reparto elegido (debe sumar el monto).
  p_de_caja: en efectivo, sale de la caja abierta del punto de quien paga.
*/
create or replace function public.registrar_pago_proveedor(
  p_proveedor bigint,
  p_monto numeric,
  p_forma_pago text,
  p_referencia text default null,
  p_notas text default null,
  p_aplicaciones jsonb default null,
  p_de_caja boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_proveedor public.proveedores;
  v_monto numeric := round(coalesce(p_monto, 0), 2);
  v_resto numeric;
  v_total_pendiente numeric;
  v_pago uuid;
  v_correlativo integer;
  v_compra record;
  v_item jsonb;
  v_aplicar numeric;
  v_suma numeric := 0;
  v_turno uuid;
begin
  select * into v_proveedor from public.proveedores where id = p_proveedor;
  if not found or not public.es_miembro(v_proveedor.id_empresa) then
    raise exception 'El proveedor no existe.';
  end if;
  if not public.tiene_rol(v_proveedor.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden registrar pagos a proveedores.';
  end if;
  if v_monto <= 0 then
    raise exception 'El monto debe ser mayor que cero.';
  end if;
  if p_forma_pago not in ('efectivo', 'tarjeta', 'transferencia', 'deposito', 'cheque', 'otro') then
    raise exception 'Forma de pago no válida.';
  end if;
  if p_forma_pago = 'efectivo' and coalesce(p_de_caja, false) then
    v_turno := public.turno_abierto((public.punto_emision_actual(v_proveedor.id_empresa)).id);
    if v_turno is null then
      raise exception 'No hay caja abierta en tu punto: abrila o desmarcá «Sale de la caja».';
    end if;
  end if;

  -- Bloquea las compras del proveedor: dos pagos a la vez no pagan lo mismo.
  perform 1 from public.compras c
   where c.id_proveedor = v_proveedor.id and c.condicion = 'credito' and c.estado = 'emitido'
   for update;

  select coalesce(sum(c.pendiente), 0) into v_total_pendiente
    from public.v_cuentas_pagar c where c.id_proveedor = v_proveedor.id and c.pendiente > 0;
  if v_monto > v_total_pendiente then
    raise exception 'El pago supera lo que se le debe al proveedor (L %).', to_char(v_total_pendiente, 'FM999,999,990.00');
  end if;

  insert into public.correlativos (id_empresa, tipo) values (v_proveedor.id_empresa, 'pago_proveedor')
  on conflict (id_empresa, tipo) do nothing;
  update public.correlativos set siguiente = siguiente + 1
   where id_empresa = v_proveedor.id_empresa and tipo = 'pago_proveedor'
  returning siguiente - 1 into v_correlativo;

  insert into public.pagos_proveedores (id_empresa, numero, correlativo, id_proveedor, proveedor_nombre,
                                        monto, forma_pago, referencia, notas, id_turno)
  values (v_proveedor.id_empresa, 'PAG-' || lpad(v_correlativo::text, 6, '0'), v_correlativo,
          v_proveedor.id, v_proveedor.nombre, v_monto, p_forma_pago,
          nullif(btrim(p_referencia), ''), nullif(btrim(p_notas), ''), v_turno)
  returning id into v_pago;

  if p_aplicaciones is not null and jsonb_typeof(p_aplicaciones) = 'array' and jsonb_array_length(p_aplicaciones) > 0 then
    for v_item in select * from jsonb_array_elements(p_aplicaciones)
    loop
      v_aplicar := round((v_item ->> 'monto')::numeric, 2);
      select c.* into v_compra from public.v_cuentas_pagar c
       where c.id = (v_item ->> 'id_compra')::uuid and c.id_proveedor = v_proveedor.id;
      if not found then
        raise exception 'Una de las compras no es de este proveedor o no es al crédito.';
      end if;
      if v_aplicar is null or v_aplicar <= 0 then
        continue;
      end if;
      if v_aplicar > v_compra.pendiente then
        raise exception 'A la compra % le quedan L % por pagar.', v_compra.numero,
          to_char(greatest(v_compra.pendiente, 0), 'FM999,999,990.00');
      end if;
      insert into public.pagos_proveedores_aplicaciones (id_pago, id_empresa, id_compra, monto)
      values (v_pago, v_proveedor.id_empresa, v_compra.id, v_aplicar);
      v_suma := v_suma + v_aplicar;
    end loop;
    if v_suma <> v_monto then
      raise exception 'El reparto (L %) no suma el monto del pago (L %).',
        to_char(v_suma, 'FM999,999,990.00'), to_char(v_monto, 'FM999,999,990.00');
    end if;
  else
    v_resto := v_monto;
    for v_compra in
      select c.* from public.v_cuentas_pagar c
       where c.id_proveedor = v_proveedor.id and c.pendiente > 0
       order by c.vence nulls last, c.fecha, c.numero
    loop
      exit when v_resto <= 0;
      v_aplicar := least(v_resto, v_compra.pendiente);
      insert into public.pagos_proveedores_aplicaciones (id_pago, id_empresa, id_compra, monto)
      values (v_pago, v_proveedor.id_empresa, v_compra.id, v_aplicar);
      v_resto := v_resto - v_aplicar;
    end loop;
  end if;

  return v_pago;
end;
$$;

create or replace function public.anular_pago_proveedor(p_pago uuid, p_motivo text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pago public.pagos_proveedores;
begin
  select * into v_pago from public.pagos_proveedores where id = p_pago for update;
  if not found or not public.es_miembro(v_pago.id_empresa) then
    raise exception 'El pago no existe.';
  end if;
  if not public.tiene_rol(v_pago.id_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden anular pagos.';
  end if;
  if v_pago.estado = 'anulado' then
    raise exception 'El pago ya está anulado.';
  end if;
  if nullif(btrim(p_motivo), '') is null then
    raise exception 'Escribí el motivo de la anulación.';
  end if;
  update public.pagos_proveedores
     set estado = 'anulado', anulado_en = now(), anulado_por = auth.uid(), motivo_anulacion = btrim(p_motivo)
   where id = p_pago;
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Caja: lo pagado en efectivo desde la caja sale del turno
-- -----------------------------------------------------------------------------

/*
  Resumen de un turno (vivo mientras está abierto). Por forma de pago:
  ventas de contado, abonos, devoluciones y cargos (notas), pagos (compras de
  contado y pagos a proveedores hechos desde la caja) y neto.
  Efectivo esperado = fondo + neto en efectivo + entradas − salidas.
*/
create or replace function public.resumen_turno(p_turno uuid)
returns jsonb
language sql
stable
set search_path = ''
as $$
  with t as (
    select * from public.cajas_turnos where id = p_turno
  ),
  formas as (
    select f.forma, f.orden
      from unnest(array['efectivo', 'tarjeta', 'transferencia', 'deposito', 'cheque', 'otro']) with ordinality as f (forma, orden)
  ),
  ventas as (
    select coalesce(d.forma_pago, 'efectivo') as forma, sum(d.total) as monto, count(*) as n
      from public.documentos d join t on d.id_turno = t.id
     where d.tipo = 'factura' and d.condicion = 'contado' and d.estado = 'emitido'
     group by 1
  ),
  notas as (
    select case when f.id is null then n.forma_pago else coalesce(f.forma_pago, 'efectivo') end as forma,
           coalesce(sum(n.total) filter (where n.tipo = 'nota_credito'), 0) as devoluciones,
           coalesce(sum(n.total) filter (where n.tipo = 'nota_debito'), 0) as cargos,
           count(*) as n
      from public.documentos n
      join t on n.id_turno = t.id
      left join public.documentos f on f.id = n.id_factura
     where n.tipo in ('nota_credito', 'nota_debito') and n.estado = 'emitido'
       and ((f.id is not null and f.condicion = 'contado') or (n.id_factura is null and n.forma_pago is not null))
     group by 1
  ),
  abonos as (
    select p.forma_pago as forma, sum(p.monto) as monto, count(*) as n
      from public.pagos p join t on p.id_turno = t.id
     where p.estado = 'emitido'
     group by 1
  ),
  pagos as (
    select x.forma, sum(x.monto) as monto, count(*) as n
      from (select c.forma_pago as forma, c.total as monto
              from public.compras c join t on c.id_turno = t.id
             where c.estado = 'emitido'
            union all
            select p.forma_pago, p.monto
              from public.pagos_proveedores p join t on p.id_turno = t.id
             where p.estado = 'emitido') x
     group by 1
  ),
  por_forma as (
    select fo.forma, fo.orden,
           coalesce(v.monto, 0) as ventas,
           coalesce(a.monto, 0) as abonos,
           coalesce(nn.devoluciones, 0) as devoluciones,
           coalesce(nn.cargos, 0) as cargos,
           coalesce(pg.monto, 0) as pagos,
           coalesce(v.monto, 0) + coalesce(a.monto, 0) + coalesce(nn.cargos, 0) - coalesce(nn.devoluciones, 0)
             - coalesce(pg.monto, 0) as neto
      from formas fo
      left join ventas v on v.forma = fo.forma
      left join abonos a on a.forma = fo.forma
      left join notas nn on nn.forma = fo.forma
      left join pagos pg on pg.forma = fo.forma
  ),
  mov as (
    select coalesce(sum(m.monto) filter (where m.tipo = 'entrada'), 0) as entradas,
           coalesce(sum(m.monto) filter (where m.tipo = 'salida'), 0) as salidas,
           count(m.id) as n
      from t left join public.cajas_movimientos m on m.id_turno = t.id
  )
  select jsonb_build_object(
    'fondo', t.fondo_inicial,
    'formas', (select jsonb_agg(jsonb_build_object(
                 'forma', pf.forma, 'ventas', pf.ventas, 'abonos', pf.abonos,
                 'devoluciones', pf.devoluciones, 'cargos', pf.cargos, 'pagos', pf.pagos, 'neto', pf.neto)
                 order by pf.orden)
                 from por_forma pf),
    'entradas', mov.entradas,
    'salidas', mov.salidas,
    'esperado_efectivo', t.fondo_inicial + (select pf.neto from por_forma pf where pf.forma = 'efectivo')
                         + mov.entradas - mov.salidas,
    'total_cobrado', (select sum(pf.neto) from por_forma pf),
    'facturas', (select coalesce(sum(v.n), 0) from ventas v),
    'abonos', (select coalesce(sum(a.n), 0) from abonos a),
    'notas', (select coalesce(sum(nn.n), 0) from notas nn),
    'pagos', (select coalesce(sum(pg.n), 0) from pagos pg),
    'movimientos', mov.n,
    'credito', (select coalesce(sum(d.total), 0) from public.documentos d
                 where d.id_turno = t.id and d.tipo = 'factura' and d.condicion = 'credito' and d.estado = 'emitido'),
    'anuladas', (select count(*) from public.documentos d where d.id_turno = t.id and d.estado = 'anulado')
  )
  from t, mov;
$$;

-- Todo lo que pasó en un turno, en orden: ventas, notas, abonos, pagos y movimientos.
-- `monto` con signo para la caja; `en_caja` = mueve dinero (las ventas al crédito no).
create or replace view public.v_caja_movimientos with (security_invoker = true) as
select d.id::text as id,
       d.id_turno,
       d.id_empresa,
       d.fecha,
       case d.tipo when 'factura' then case when d.condicion = 'credito' then 'venta_credito' else 'venta' end
                   when 'nota_credito' then 'devolucion' else 'cargo' end as tipo,
       d.numero as referencia,
       d.cliente_nombre as detalle,
       coalesce(d.forma_pago, f.forma_pago) as forma_pago,
       case when d.tipo = 'nota_credito' then -d.total else d.total end as monto,
       (d.tipo = 'factura' and d.condicion = 'contado')
         or (d.tipo in ('nota_credito', 'nota_debito')
             and (coalesce(f.condicion = 'contado', false) or (d.id_factura is null and d.forma_pago is not null))) as en_caja,
       d.estado,
       u.nombre as usuario
  from public.documentos d
  left join public.documentos f on f.id = d.id_factura
  left join public.usuarios u on u.id = d.creado_por
 where d.id_turno is not null and d.tipo <> 'cotizacion'
union all
select p.id::text, p.id_turno, p.id_empresa, p.fecha, 'abono', p.numero, p.cliente_nombre, p.forma_pago,
       p.monto, true, p.estado, u.nombre
  from public.pagos p
  left join public.usuarios u on u.id = p.creado_por
 where p.id_turno is not null
union all
select c.id::text, c.id_turno, c.id_empresa, c.creado_en, 'compra', c.numero, c.proveedor_nombre, c.forma_pago,
       -c.total, true, c.estado, u.nombre
  from public.compras c
  left join public.usuarios u on u.id = c.creado_por
 where c.id_turno is not null
union all
select p.id::text, p.id_turno, p.id_empresa, p.fecha, 'pago_proveedor', p.numero, p.proveedor_nombre, p.forma_pago,
       -p.monto, true, p.estado, u.nombre
  from public.pagos_proveedores p
  left join public.usuarios u on u.id = p.creado_por
 where p.id_turno is not null
union all
select m.id::text, m.id_turno, m.id_empresa, m.creado_en, m.tipo, null, m.concepto, 'efectivo',
       case when m.tipo = 'salida' then -m.monto else m.monto end, true, 'emitido', u.nombre
  from public.cajas_movimientos m
  left join public.usuarios u on u.id = m.creado_por;

-- -----------------------------------------------------------------------------
-- 8. Vistas
-- -----------------------------------------------------------------------------

create or replace view public.v_proveedores with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.nombre,
       p.rtn,
       p.telefono,
       p.correo,
       p.direccion,
       p.contacto,
       p.dias_credito,
       p.notas,
       p.activo,
       (select count(*) from public.compras c where c.id_proveedor = p.id and c.estado = 'emitido')::integer as compras,
       (select max(c.fecha) from public.compras c where c.id_proveedor = p.id and c.estado = 'emitido') as ultima_compra,
       coalesce((select sum(cp.pendiente) from public.v_cuentas_pagar cp where cp.id_proveedor = p.id), 0) as saldo,
       p.creado_en
  from public.proveedores p;

-- Una fila por proveedor con algo pendiente.
create or replace view public.v_cuentas_proveedores with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.nombre,
       p.rtn,
       p.telefono,
       p.dias_credito,
       t.pendiente,
       coalesce(t.vencido, 0) as vencido,
       t.compras::integer as compras,
       coalesce(t.dias_mora, 0)::integer as dias_mora,
       t.proximo_vence,
       (select max(pp.fecha) from public.pagos_proveedores pp where pp.id_proveedor = p.id and pp.estado = 'emitido') as ultimo_pago,
       case when coalesce(t.vencido, 0) > 0 then 'vencida' else 'al_dia' end as estado,
       coalesce(t.vencido, 0) > 0 as en_mora
  from public.proveedores p
  join (
    select cp.id_proveedor,
           sum(cp.pendiente) as pendiente,
           sum(cp.pendiente) filter (where cp.estado = 'vencida') as vencido,
           count(*) as compras,
           max(cp.dias_vencida) as dias_mora,
           min(cp.vence) as proximo_vence
      from public.v_cuentas_pagar cp
     where cp.pendiente > 0
     group by cp.id_proveedor
  ) t on t.id_proveedor = p.id;

create or replace view public.v_compras with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.numero,
       c.tipo,
       c.fecha,
       c.id_proveedor,
       c.proveedor_nombre,
       c.proveedor_rtn,
       c.documento,
       c.condicion,
       c.vence,
       c.forma_pago,
       c.subtotal,
       c.isv,
       c.total,
       c.estado,
       cp.pendiente,
       (select count(*) from public.compras_lineas l where l.id_compra = c.id)::integer as lineas,
       u.nombre as registro,
       c.creado_en
  from public.compras c
  left join public.v_cuentas_pagar cp on cp.id = c.id
  left join public.usuarios u on u.id = c.creado_por;

create or replace view public.v_pagos_proveedores with (security_invoker = true) as
select p.id,
       p.id_empresa,
       p.numero,
       p.fecha,
       p.id_proveedor,
       p.proveedor_nombre,
       p.monto,
       p.forma_pago,
       p.referencia,
       p.notas,
       p.estado,
       p.motivo_anulacion,
       p.id_turno is not null as de_caja,
       (select string_agg(c.numero || coalesce(' (' || c.documento || ')', ''), ', ' order by c.numero)
          from public.pagos_proveedores_aplicaciones a join public.compras c on c.id = a.id_compra
         where a.id_pago = p.id) as compras,
       u.nombre as pago,
       p.creado_en
  from public.pagos_proveedores p
  left join public.usuarios u on u.id = p.creado_por;

create or replace view public.v_pagos_proveedores_aplicaciones with (security_invoker = true) as
select a.id, a.id_pago, a.id_empresa, a.id_compra, c.numero, c.documento, c.fecha as fecha_compra, c.total, a.monto
  from public.pagos_proveedores_aplicaciones a
  join public.compras c on c.id = a.id_compra;

-- -----------------------------------------------------------------------------
-- 9. Permisos y RLS
-- -----------------------------------------------------------------------------

revoke all on public.proveedores, public.compras, public.compras_lineas,
              public.pagos_proveedores, public.pagos_proveedores_aplicaciones
  from anon, authenticated;

grant select, insert, delete on public.proveedores to authenticated;
grant update (nombre, rtn, telefono, correo, direccion, contacto, dias_credito, notas, activo)
  on public.proveedores to authenticated;
grant select on public.compras, public.compras_lineas, public.pagos_proveedores, public.pagos_proveedores_aplicaciones
  to authenticated;

alter table public.proveedores enable row level security;
alter table public.compras enable row level security;
alter table public.compras_lineas enable row level security;
alter table public.pagos_proveedores enable row level security;
alter table public.pagos_proveedores_aplicaciones enable row level security;

-- Proveedores: los ven los miembros (para saber de quién es una compra); los administran dueño/admin.
drop policy if exists empresa_lectura on public.proveedores;
create policy empresa_lectura on public.proveedores
  for select to authenticated using (public.es_miembro(id_empresa));
drop policy if exists admin_escritura on public.proveedores;
create policy admin_escritura on public.proveedores
  for all to authenticated
  using (public.tiene_rol(id_empresa, array['dueno', 'admin']))
  with check (public.tiene_rol(id_empresa, array['dueno', 'admin']));

-- Compras y pagos: solo lectura; se escriben con las funciones (dueño/admin).
drop policy if exists admin_lectura on public.compras;
create policy admin_lectura on public.compras
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.compras_lineas;
create policy admin_lectura on public.compras_lineas
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.pagos_proveedores;
create policy admin_lectura on public.pagos_proveedores
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.pagos_proveedores_aplicaciones;
create policy admin_lectura on public.pagos_proveedores_aplicaciones
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));

-- La caja la ve quien la atiende (puede ser vendedor): lo que salió de su turno
-- por compras y pagos se lee por v_caja_movimientos/resumen_turno, que corren con
-- los permisos del que llama. Para que el cajero vea esas salidas, le damos
-- lectura de las compras y pagos de su propio turno.
drop policy if exists turno_lectura on public.compras;
create policy turno_lectura on public.compras
  for select to authenticated
  using (id_turno is not null and public.es_miembro(id_empresa));
drop policy if exists turno_lectura on public.pagos_proveedores;
create policy turno_lectura on public.pagos_proveedores
  for select to authenticated
  using (id_turno is not null and public.es_miembro(id_empresa));

revoke all on function public.registrar_compra(uuid, jsonb) from public, anon;
revoke all on function public.anular_compra(uuid, text) from public, anon;
revoke all on function public.registrar_pago_proveedor(bigint, numeric, text, text, text, jsonb, boolean) from public, anon;
revoke all on function public.anular_pago_proveedor(uuid, text) from public, anon;
grant execute on function public.registrar_compra(uuid, jsonb) to authenticated;
grant execute on function public.anular_compra(uuid, text) to authenticated;
grant execute on function public.registrar_pago_proveedor(bigint, numeric, text, text, text, jsonb, boolean) to authenticated;
grant execute on function public.anular_pago_proveedor(uuid, text) to authenticated;

revoke all on public.v_proveedores, public.v_compras, public.v_cuentas_pagar, public.v_cuentas_proveedores,
              public.v_pagos_proveedores, public.v_pagos_proveedores_aplicaciones, public.v_caja_movimientos
  from anon;
grant select on public.v_proveedores, public.v_compras, public.v_cuentas_pagar, public.v_cuentas_proveedores,
               public.v_pagos_proveedores, public.v_pagos_proveedores_aplicaciones, public.v_caja_movimientos
  to authenticated;

-- Auditoría (0011).
do $$
begin
  if to_regprocedure('public.registrar_cambio()') is not null then
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.proveedores '
            'for each row execute function public.registrar_cambio()';
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.compras '
            'for each row execute function public.registrar_cambio()';
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.pagos_proveedores '
            'for each row execute function public.registrar_cambio()';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 10. Documentación en la base
-- -----------------------------------------------------------------------------

comment on table public.proveedores is 'Proveedores de la empresa. dias_credito = plazo por defecto de sus compras al crédito.';
comment on table public.compras is
  'Facturas de proveedores registradas (COMP-000001): de productos (suben existencias y costo promedio) o de gasto. Inmutables: se anulan.';
comment on column public.compras.id_turno is 'Pagada en efectivo desde la caja: salió de este turno.';
comment on table public.pagos_proveedores is 'Pagos a proveedores (PAG-000001) repartidos en pagos_proveedores_aplicaciones.';
comment on view public.v_cuentas_pagar is 'Compras al crédito vigentes: pendiente = total − pagos vigentes.';
comment on function public.registrar_compra(uuid, jsonb) is
  'Registra una compra (dueño/admin): inventario con costo promedio o gasto; contado (opcional desde la caja) o crédito.';

commit;
