-- =============================================================================
-- 0022 · Contabilidad: catálogo de cuentas, asientos y cierre de mes
-- -----------------------------------------------------------------------------
-- ESTADO: PENDIENTE
-- Idempotente y atómica. Requiere 0021 (compras).
--
-- Qué crea o cambia:
--   · cuentas_contables     Catálogo por empresa (árbol por id_padre). Cada
--                           cuenta que usa el sistema lleva una `clave`
--                           (caja, bancos, clientes, ventas…); el contador puede
--                           pasar la clave a otra cuenta. Se precarga uno
--                           estándar para comercio (NIIF para PYMES).
--   · asientos, asientos_lineas   Partida doble: cada asiento cuadra (debe =
--                           haber), lo revisa un trigger diferido. Inmutables:
--                           se corrigen con un asiento de reversa.
--   · periodos_cerrados     Meses cerrados: no aceptan asientos.
--   · Asientos automáticos (triggers diferidos, al confirmar la transacción):
--       factura, nota de crédito/débito, abono, compra, pago a proveedor,
--       entrada/salida de caja y diferencia del cierre de caja. Al anular el
--       documento se genera su reversa.
--   · crear_asiento(), revertir_asiento(), cerrar_periodo(), reabrir_periodo(),
--     contabilizar_pendientes() (lo anterior a esta migración),
--     asiento_apertura_inventario(), balanza(), mayor().
--
-- Reglas (docs/negocio.md §3.11). A VERIFICAR con el contador: el catálogo, qué
-- cuenta usa cada asiento automático (tarjeta/transferencia → Bancos; entradas
-- de caja contra Bancos; salidas de caja a Gastos generales) y el costo de
-- ventas perpetuo (costo promedio guardado en cada línea vendida).
-- =============================================================================

begin;

create or replace function pg_temp.restriccion_0022(tabla regclass, nombre text, definicion text)
returns void
language plpgsql
as $$
begin
  if not exists (select 1 from pg_constraint where conrelid = tabla and conname = nombre) then
    execute format('alter table %s add constraint %I %s', tabla, nombre, definicion);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 1. Catálogo de cuentas
-- -----------------------------------------------------------------------------

create table if not exists public.cuentas_contables (
  id bigint generated by default as identity primary key,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  codigo text not null,
  nombre text not null,
  tipo text not null,
  naturaleza text not null,
  id_padre bigint references public.cuentas_contables (id),
  clave text,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint cuentas_contables_codigo_key unique (id_empresa, codigo)
);

create index if not exists cuentas_contables_id_padre_idx on public.cuentas_contables (id_padre);
create unique index if not exists cuentas_contables_clave_key
  on public.cuentas_contables (id_empresa, clave) where clave is not null;

select pg_temp.restriccion_0022('public.cuentas_contables', 'cuentas_contables_codigo_check',
  $$check (codigo ~ '^\d{1,12}$')$$);
select pg_temp.restriccion_0022('public.cuentas_contables', 'cuentas_contables_nombre_check',
  $$check (btrim(nombre) <> '' and char_length(nombre) <= 120)$$);
select pg_temp.restriccion_0022('public.cuentas_contables', 'cuentas_contables_tipo_check',
  $$check (tipo in ('activo', 'pasivo', 'patrimonio', 'ingreso', 'costo', 'gasto'))$$);
select pg_temp.restriccion_0022('public.cuentas_contables', 'cuentas_contables_naturaleza_check',
  $$check (naturaleza in ('deudora', 'acreedora'))$$);
select pg_temp.restriccion_0022('public.cuentas_contables', 'cuentas_contables_clave_check',
  $$check (clave is null or clave in ('caja', 'bancos', 'clientes', 'inventario', 'isv_credito', 'proveedores',
                                      'isv_debito', 'capital', 'ventas', 'devoluciones_ventas', 'otros_ingresos',
                                      'sobrantes_caja', 'costo_ventas', 'gastos_generales', 'faltantes_caja'))$$);

create or replace function public.tg_normalizar_cuenta()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.id_empresa <> old.id_empresa then
    raise exception 'No se puede cambiar la empresa de una cuenta.';
  end if;
  new.codigo := regexp_replace(coalesce(new.codigo, ''), '\D', '', 'g');
  new.nombre := regexp_replace(btrim(new.nombre), '\s+', ' ', 'g');
  new.clave := nullif(btrim(new.clave), '');
  -- Naturaleza por defecto según el tipo (se puede cambiar: depreciación acumulada, devoluciones).
  if new.naturaleza is null or btrim(new.naturaleza) = '' then
    new.naturaleza := case when new.tipo in ('activo', 'costo', 'gasto') then 'deudora' else 'acreedora' end;
  end if;
  if new.id_padre is not null then
    if new.id_padre = new.id then
      raise exception 'Una cuenta no puede ser su propia madre.';
    end if;
    if not exists (select 1 from public.cuentas_contables p where p.id = new.id_padre and p.id_empresa = new.id_empresa) then
      raise exception 'La cuenta madre no es de esta empresa.';
    end if;
    -- Sin ciclos: la madre no puede descender de esta cuenta.
    if tg_op = 'UPDATE' and exists (
         with recursive arriba as (
           select p.id, p.id_padre from public.cuentas_contables p where p.id = new.id_padre
           union all
           select c.id, c.id_padre from public.cuentas_contables c join arriba a on c.id = a.id_padre
         )
         select 1 from arriba where id = new.id) then
      raise exception 'Esa madre crearía un ciclo en el catálogo.';
    end if;
  end if;
  return new;
end;
$$;

-- La columna naturaleza se completa en el trigger: se acepta vacía al insertar.
alter table public.cuentas_contables alter column naturaleza set default '';

create or replace trigger a_normalizar
  before insert or update on public.cuentas_contables
  for each row execute function public.tg_normalizar_cuenta();

/*
  Catálogo estándar para un comercio en Honduras (NIIF para PYMES, simplificado).
  Agrega lo que falte por código (no toca lo que la empresa ya cambió) y pone
  cada clave del sistema en su cuenta si ninguna otra la tiene.
*/
create or replace function public.crear_catalogo_base(p_empresa uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_n integer;
begin
  create temporary table if not exists catalogo_base (
    codigo text, nombre text, tipo text, naturaleza text, padre text, clave text
  ) on commit drop;
  truncate catalogo_base;
  insert into catalogo_base values
    ('1', 'ACTIVO', 'activo', 'deudora', null, null),
    ('11', 'Activo corriente', 'activo', 'deudora', '1', null),
    ('1101', 'Efectivo y equivalentes', 'activo', 'deudora', '11', null),
    ('110101', 'Caja general', 'activo', 'deudora', '1101', 'caja'),
    ('110102', 'Caja chica', 'activo', 'deudora', '1101', null),
    ('110103', 'Bancos', 'activo', 'deudora', '1101', 'bancos'),
    ('1102', 'Cuentas por cobrar', 'activo', 'deudora', '11', null),
    ('110201', 'Clientes', 'activo', 'deudora', '1102', 'clientes'),
    ('110202', 'Otras cuentas por cobrar', 'activo', 'deudora', '1102', null),
    ('1103', 'Inventarios', 'activo', 'deudora', '11', null),
    ('110301', 'Inventario de mercadería', 'activo', 'deudora', '1103', 'inventario'),
    ('1104', 'Impuestos por recuperar', 'activo', 'deudora', '11', null),
    ('110401', 'ISV crédito fiscal (compras)', 'activo', 'deudora', '1104', 'isv_credito'),
    ('12', 'Activo no corriente', 'activo', 'deudora', '1', null),
    ('1201', 'Propiedad, planta y equipo', 'activo', 'deudora', '12', null),
    ('120101', 'Mobiliario y equipo', 'activo', 'deudora', '1201', null),
    ('120102', 'Vehículos', 'activo', 'deudora', '1201', null),
    ('120103', 'Equipo de cómputo', 'activo', 'deudora', '1201', null),
    ('120104', 'Depreciación acumulada', 'activo', 'acreedora', '1201', null),
    ('2', 'PASIVO', 'pasivo', 'acreedora', null, null),
    ('21', 'Pasivo corriente', 'pasivo', 'acreedora', '2', null),
    ('2101', 'Proveedores', 'pasivo', 'acreedora', '21', 'proveedores'),
    ('2102', 'Impuestos por pagar', 'pasivo', 'acreedora', '21', null),
    ('210201', 'ISV por pagar (ventas)', 'pasivo', 'acreedora', '2102', 'isv_debito'),
    ('210202', 'Retenciones por pagar', 'pasivo', 'acreedora', '2102', null),
    ('2103', 'Sueldos y prestaciones por pagar', 'pasivo', 'acreedora', '21', null),
    ('2104', 'Préstamos a corto plazo', 'pasivo', 'acreedora', '21', null),
    ('22', 'Pasivo no corriente', 'pasivo', 'acreedora', '2', null),
    ('2201', 'Préstamos a largo plazo', 'pasivo', 'acreedora', '22', null),
    ('3', 'PATRIMONIO', 'patrimonio', 'acreedora', null, null),
    ('3101', 'Capital', 'patrimonio', 'acreedora', '3', 'capital'),
    ('3102', 'Utilidades acumuladas', 'patrimonio', 'acreedora', '3', null),
    ('3103', 'Utilidad o pérdida del ejercicio', 'patrimonio', 'acreedora', '3', null),
    ('4', 'INGRESOS', 'ingreso', 'acreedora', null, null),
    ('4101', 'Ventas de mercadería', 'ingreso', 'acreedora', '4', 'ventas'),
    ('4102', 'Devoluciones y rebajas sobre ventas', 'ingreso', 'deudora', '4', 'devoluciones_ventas'),
    ('4201', 'Otros ingresos', 'ingreso', 'acreedora', '4', 'otros_ingresos'),
    ('4202', 'Sobrantes de caja', 'ingreso', 'acreedora', '4', 'sobrantes_caja'),
    ('5', 'COSTOS', 'costo', 'deudora', null, null),
    ('5101', 'Costo de ventas', 'costo', 'deudora', '5', 'costo_ventas'),
    ('6', 'GASTOS', 'gasto', 'deudora', null, null),
    ('6101', 'Sueldos y salarios', 'gasto', 'deudora', '6', null),
    ('6102', 'Alquiler', 'gasto', 'deudora', '6', null),
    ('6103', 'Energía eléctrica, agua y teléfono', 'gasto', 'deudora', '6', null),
    ('6104', 'Combustible y transporte', 'gasto', 'deudora', '6', null),
    ('6105', 'Gastos generales', 'gasto', 'deudora', '6', 'gastos_generales'),
    ('6106', 'Faltantes de caja', 'gasto', 'deudora', '6', 'faltantes_caja'),
    ('6107', 'Depreciación', 'gasto', 'deudora', '6', null),
    ('6108', 'Gastos bancarios', 'gasto', 'deudora', '6', null);

  insert into public.cuentas_contables (id_empresa, codigo, nombre, tipo, naturaleza)
  select p_empresa, b.codigo, b.nombre, b.tipo, b.naturaleza from catalogo_base b
  on conflict (id_empresa, codigo) do nothing;
  get diagnostics v_n = row_count;

  update public.cuentas_contables c
     set id_padre = p.id
    from catalogo_base b
    join public.cuentas_contables p on p.id_empresa = p_empresa and p.codigo = b.padre
   where c.id_empresa = p_empresa and c.codigo = b.codigo and c.id_padre is null and b.padre is not null;

  update public.cuentas_contables c
     set clave = b.clave
    from catalogo_base b
   where c.id_empresa = p_empresa and c.codigo = b.codigo and c.clave is null and b.clave is not null
     and not exists (select 1 from public.cuentas_contables o where o.id_empresa = p_empresa and o.clave = b.clave);

  return v_n;
end;
$$;

-- Cuenta que usa el sistema para una clave (precarga el catálogo si falta).
create or replace function public.cuenta_por_clave(p_empresa uuid, p_clave text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  select id into v_id from public.cuentas_contables where id_empresa = p_empresa and clave = p_clave;
  if v_id is null then
    perform public.crear_catalogo_base(p_empresa);
    select id into v_id from public.cuentas_contables where id_empresa = p_empresa and clave = p_clave;
  end if;
  if v_id is null then
    raise exception 'Falta la cuenta contable «%» en el catálogo (Contabilidad › Catálogo).', p_clave;
  end if;
  return v_id;
end;
$$;

-- -----------------------------------------------------------------------------
-- 2. Asientos
-- -----------------------------------------------------------------------------

create table if not exists public.asientos (
  id uuid primary key default gen_random_uuid(),
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  numero integer not null,
  fecha date not null,
  concepto text not null,
  origen text not null default 'manual',
  id_origen text,
  referencia text,
  id_revierte uuid references public.asientos (id),
  revertido_por uuid references public.asientos (id),
  creado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  creado_en timestamptz not null default now(),
  constraint asientos_numero_key unique (id_empresa, numero)
);

create index if not exists asientos_empresa_fecha_idx on public.asientos (id_empresa, fecha);
create index if not exists asientos_id_revierte_idx on public.asientos (id_revierte);
create index if not exists asientos_revertido_por_idx on public.asientos (revertido_por);
create index if not exists asientos_creado_por_idx on public.asientos (creado_por);
-- Un documento se contabiliza una sola vez (las reversas no cuentan).
create unique index if not exists asientos_origen_key
  on public.asientos (id_empresa, origen, id_origen) where id_origen is not null and id_revierte is null;

select pg_temp.restriccion_0022('public.asientos', 'asientos_origen_check',
  $$check (origen in ('manual', 'factura', 'nota_credito', 'nota_debito', 'abono', 'compra', 'pago_proveedor',
                      'caja_entrada', 'caja_salida', 'cierre_caja', 'apertura_inventario'))$$);
select pg_temp.restriccion_0022('public.asientos', 'asientos_textos_check',
  $$check (btrim(concepto) <> '' and char_length(concepto) <= 300 and (referencia is null or char_length(referencia) <= 80))$$);

create table if not exists public.asientos_lineas (
  id bigint generated by default as identity primary key,
  id_asiento uuid not null references public.asientos (id) on delete cascade,
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  id_cuenta bigint not null references public.cuentas_contables (id),
  debe numeric(14, 2) not null default 0,
  haber numeric(14, 2) not null default 0,
  descripcion text,
  orden integer not null default 0
);

create index if not exists asientos_lineas_id_asiento_idx on public.asientos_lineas (id_asiento);
create index if not exists asientos_lineas_id_cuenta_idx on public.asientos_lineas (id_cuenta);
create index if not exists asientos_lineas_id_empresa_idx on public.asientos_lineas (id_empresa);

select pg_temp.restriccion_0022('public.asientos_lineas', 'asientos_lineas_montos_check',
  $$check (debe >= 0 and haber >= 0 and (debe = 0) <> (haber = 0)
           and (descripcion is null or char_length(descripcion) <= 200))$$);

create table if not exists public.periodos_cerrados (
  id_empresa uuid not null references public.empresas (id) on delete cascade,
  mes date not null,
  cerrado_por uuid references public.usuarios (id) on delete set null default auth.uid(),
  cerrado_en timestamptz not null default now(),
  constraint periodos_cerrados_pkey primary key (id_empresa, mes)
);

select pg_temp.restriccion_0022('public.periodos_cerrados', 'periodos_cerrados_mes_check',
  $$check (mes = date_trunc('month', mes)::date)$$);

-- Cada asiento cuadra: se revisa al confirmar la transacción (las líneas entran una por una).
create or replace function public.verificar_cuadre(p_asiento uuid)
returns void
language plpgsql
set search_path = ''
as $$
declare
  v_debe numeric;
  v_haber numeric;
  v_n integer;
begin
  if not exists (select 1 from public.asientos where id = p_asiento) then
    return;
  end if;
  select coalesce(sum(debe), 0), coalesce(sum(haber), 0), count(*) into v_debe, v_haber, v_n
    from public.asientos_lineas where id_asiento = p_asiento;
  if v_n < 2 then
    raise exception 'Un asiento lleva al menos dos líneas.';
  end if;
  if v_debe <> v_haber then
    raise exception 'El asiento no cuadra: debe L % y haber L %.',
      to_char(v_debe, 'FM999,999,990.00'), to_char(v_haber, 'FM999,999,990.00');
  end if;
end;
$$;

create or replace function public.tg_cuadre_asiento()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  perform public.verificar_cuadre(new.id);
  return null;
end;
$$;

create or replace function public.tg_cuadre_linea()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.verificar_cuadre(old.id_asiento);
  else
    perform public.verificar_cuadre(new.id_asiento);
  end if;
  return null;
end;
$$;

drop trigger if exists zz_cuadre on public.asientos_lineas;
create constraint trigger zz_cuadre
  after insert or update or delete on public.asientos_lineas
  deferrable initially deferred
  for each row execute function public.tg_cuadre_linea();

drop trigger if exists zz_cuadre on public.asientos;
create constraint trigger zz_cuadre
  after insert on public.asientos
  deferrable initially deferred
  for each row execute function public.tg_cuadre_asiento();

-- Un mes cerrado no acepta asientos.
create or replace function public.tg_periodo_abierto()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (select 1 from public.periodos_cerrados p
              where p.id_empresa = new.id_empresa and p.mes = date_trunc('month', new.fecha)::date) then
    raise exception 'El mes de % está cerrado en la contabilidad: no admite asientos.',
      to_char(new.fecha, 'MM/YYYY');
  end if;
  return new;
end;
$$;

create or replace trigger a_periodo_abierto
  before insert on public.asientos
  for each row execute function public.tg_periodo_abierto();

/*
  Inserta un asiento con sus líneas (uso interno: los automáticos y crear_asiento).
  p_lineas: [{ cuenta: <clave> | <id>, debe, haber, descripcion? }]; las de
  monto cero se omiten. Devuelve el id (null si no quedó ninguna línea).
*/
create or replace function public.asentar(
  p_empresa uuid,
  p_fecha date,
  p_concepto text,
  p_origen text,
  p_id_origen text,
  p_referencia text,
  p_lineas jsonb,
  p_revierte uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_asiento uuid;
  v_numero integer;
  v_item jsonb;
  v_cuenta bigint;
  v_debe numeric;
  v_haber numeric;
  v_orden integer := 0;
begin
  if not exists (select 1 from jsonb_array_elements(p_lineas) x
                  where round(coalesce((x ->> 'debe')::numeric, 0), 2) > 0
                     or round(coalesce((x ->> 'haber')::numeric, 0), 2) > 0) then
    return null;
  end if;

  insert into public.correlativos (id_empresa, tipo) values (p_empresa, 'asiento')
  on conflict (id_empresa, tipo) do nothing;
  update public.correlativos set siguiente = siguiente + 1
   where id_empresa = p_empresa and tipo = 'asiento'
  returning siguiente - 1 into v_numero;

  insert into public.asientos (id_empresa, numero, fecha, concepto, origen, id_origen, referencia, id_revierte)
  values (p_empresa, v_numero, p_fecha, left(btrim(p_concepto), 300), p_origen, p_id_origen, left(p_referencia, 80), p_revierte)
  returning id into v_asiento;

  for v_item in select * from jsonb_array_elements(p_lineas)
  loop
    v_debe := round(coalesce((v_item ->> 'debe')::numeric, 0), 2);
    v_haber := round(coalesce((v_item ->> 'haber')::numeric, 0), 2);
    continue when v_debe = 0 and v_haber = 0;
    -- Un monto negativo pasa al otro lado (p. ej. un costo negativo por redondeo).
    if v_debe < 0 then v_haber := v_haber - v_debe; v_debe := 0; end if;
    if v_haber < 0 then v_debe := v_debe - v_haber; v_haber := 0; end if;
    if v_debe > 0 and v_haber > 0 then
      if v_debe >= v_haber then v_debe := v_debe - v_haber; v_haber := 0;
      else v_haber := v_haber - v_debe; v_debe := 0; end if;
      continue when v_debe = 0 and v_haber = 0;
    end if;
    if jsonb_typeof(v_item -> 'cuenta') = 'number' then
      v_cuenta := (v_item ->> 'cuenta')::bigint;
    else
      v_cuenta := public.cuenta_por_clave(p_empresa, v_item ->> 'cuenta');
    end if;
    v_orden := v_orden + 1;
    insert into public.asientos_lineas (id_asiento, id_empresa, id_cuenta, debe, haber, descripcion, orden)
    values (v_asiento, p_empresa, v_cuenta, v_debe, v_haber, nullif(left(btrim(v_item ->> 'descripcion'), 200), ''), v_orden);
  end loop;

  if p_revierte is not null then
    update public.asientos set revertido_por = v_asiento where id = p_revierte;
  end if;
  return v_asiento;
end;
$$;

-- Reversa del asiento vigente de un documento (al anularlo). Fecha: hoy.
create or replace function public.revertir_origen(p_empresa uuid, p_origen text, p_id_origen text, p_concepto text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_original public.asientos;
begin
  select * into v_original from public.asientos
   where id_empresa = p_empresa and origen = p_origen and id_origen = p_id_origen
     and id_revierte is null and revertido_por is null;
  if not found then
    return null;
  end if;
  return public.asentar(
    p_empresa, (now() at time zone 'America/Tegucigalpa')::date, p_concepto, p_origen, p_id_origen,
    v_original.referencia,
    (select jsonb_agg(jsonb_build_object('cuenta', l.id_cuenta, 'debe', l.haber, 'haber', l.debe, 'descripcion', l.descripcion)
                      order by l.orden)
       from public.asientos_lineas l where l.id_asiento = v_original.id),
    v_original.id);
end;
$$;

-- Cuenta de cobro o pago según la forma: efectivo a Caja; lo demás a Bancos.
create or replace function public.clave_forma_pago(p_forma text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case when coalesce(p_forma, 'efectivo') = 'efectivo' then 'caja' else 'bancos' end;
$$;

-- -----------------------------------------------------------------------------
-- 3. Asientos automáticos
-- -----------------------------------------------------------------------------

create or replace function public.contabilizar_documento(p_doc uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_d public.documentos;
  v_f public.documentos;
  v_cobro text;
  v_neto numeric;
  v_costo numeric;
  v_fecha date;
  v_nombre text;
begin
  select * into v_d from public.documentos where id = p_doc;
  if not found or v_d.tipo not in ('factura', 'nota_credito', 'nota_debito') then
    return null;
  end if;
  if exists (select 1 from public.asientos a
              where a.id_empresa = v_d.id_empresa and a.origen = v_d.tipo and a.id_origen = v_d.id::text
                and a.id_revierte is null) then
    return null;
  end if;

  v_fecha := (v_d.fecha at time zone 'America/Tegucigalpa')::date;
  v_neto := v_d.total - v_d.isv;
  select coalesce(sum(round(l.cantidad * coalesce(l.costo, 0), 2)), 0) into v_costo
    from public.documentos_lineas l
   where l.id_documento = v_d.id and l.controla_inventario and l.id_producto is not null and l.costo is not null;

  if v_d.tipo = 'factura' then
    v_cobro := case when v_d.condicion = 'credito' then 'clientes' else public.clave_forma_pago(v_d.forma_pago) end;
  elsif v_d.id_factura is not null then
    select * into v_f from public.documentos where id = v_d.id_factura;
    v_cobro := case when v_f.condicion = 'credito' then 'clientes' else public.clave_forma_pago(v_f.forma_pago) end;
  else
    -- Nota sin factura (0019): su forma de pago; sin dinero, queda contra el cliente.
    v_cobro := case when v_d.forma_pago is null then 'clientes' else public.clave_forma_pago(v_d.forma_pago) end;
  end if;

  v_nombre := case v_d.tipo when 'factura' then 'Venta' when 'nota_credito' then 'Nota de crédito' else 'Nota de débito' end;

  return public.asentar(
    v_d.id_empresa, v_fecha,
    v_nombre || ' ' || v_d.numero || ' · ' || v_d.cliente_nombre,
    v_d.tipo, v_d.id::text, v_d.numero,
    case v_d.tipo
      when 'factura' then jsonb_build_array(
        jsonb_build_object('cuenta', v_cobro, 'debe', v_d.total),
        jsonb_build_object('cuenta', 'ventas', 'haber', v_neto),
        jsonb_build_object('cuenta', 'isv_debito', 'haber', v_d.isv),
        jsonb_build_object('cuenta', 'costo_ventas', 'debe', v_costo, 'descripcion', 'Costo de lo vendido'),
        jsonb_build_object('cuenta', 'inventario', 'haber', v_costo, 'descripcion', 'Salida de inventario'))
      when 'nota_credito' then jsonb_build_array(
        jsonb_build_object('cuenta', 'devoluciones_ventas', 'debe', v_neto),
        jsonb_build_object('cuenta', 'isv_debito', 'debe', v_d.isv),
        jsonb_build_object('cuenta', v_cobro, 'haber', v_d.total),
        jsonb_build_object('cuenta', 'inventario', 'debe', case when v_d.reintegra_inventario then v_costo else 0 end,
                           'descripcion', 'Piezas que regresan'),
        jsonb_build_object('cuenta', 'costo_ventas', 'haber', case when v_d.reintegra_inventario then v_costo else 0 end,
                           'descripcion', 'Costo de lo devuelto'))
      else jsonb_build_array(
        jsonb_build_object('cuenta', v_cobro, 'debe', v_d.total),
        jsonb_build_object('cuenta', 'otros_ingresos', 'haber', v_neto),
        jsonb_build_object('cuenta', 'isv_debito', 'haber', v_d.isv))
    end);
end;
$$;

create or replace function public.contabilizar_abono(p_pago uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_p public.pagos;
begin
  select * into v_p from public.pagos where id = p_pago;
  if not found or exists (select 1 from public.asientos a where a.id_empresa = v_p.id_empresa and a.origen = 'abono'
                             and a.id_origen = v_p.id::text and a.id_revierte is null) then
    return null;
  end if;
  return public.asentar(
    v_p.id_empresa, (v_p.fecha at time zone 'America/Tegucigalpa')::date,
    'Abono ' || v_p.numero || ' · ' || v_p.cliente_nombre, 'abono', v_p.id::text, v_p.numero,
    jsonb_build_array(
      jsonb_build_object('cuenta', public.clave_forma_pago(v_p.forma_pago), 'debe', v_p.monto),
      jsonb_build_object('cuenta', 'clientes', 'haber', v_p.monto)));
end;
$$;

create or replace function public.contabilizar_compra(p_compra uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_c public.compras;
begin
  select * into v_c from public.compras where id = p_compra;
  if not found or exists (select 1 from public.asientos a where a.id_empresa = v_c.id_empresa and a.origen = 'compra'
                             and a.id_origen = v_c.id::text and a.id_revierte is null) then
    return null;
  end if;
  return public.asentar(
    v_c.id_empresa, v_c.fecha,
    'Compra ' || v_c.numero || coalesce(' (' || v_c.documento || ')', '') || ' · ' || v_c.proveedor_nombre,
    'compra', v_c.id::text, coalesce(v_c.documento, v_c.numero),
    jsonb_build_array(
      jsonb_build_object('cuenta', case when v_c.tipo = 'inventario' then 'inventario' else 'gastos_generales' end,
                         'debe', v_c.subtotal),
      jsonb_build_object('cuenta', 'isv_credito', 'debe', v_c.isv),
      jsonb_build_object('cuenta', case when v_c.condicion = 'credito' then 'proveedores'
                                        else public.clave_forma_pago(v_c.forma_pago) end,
                         'haber', v_c.total)));
end;
$$;

create or replace function public.contabilizar_pago_proveedor(p_pago uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_p public.pagos_proveedores;
begin
  select * into v_p from public.pagos_proveedores where id = p_pago;
  if not found or exists (select 1 from public.asientos a where a.id_empresa = v_p.id_empresa and a.origen = 'pago_proveedor'
                             and a.id_origen = v_p.id::text and a.id_revierte is null) then
    return null;
  end if;
  return public.asentar(
    v_p.id_empresa, (v_p.fecha at time zone 'America/Tegucigalpa')::date,
    'Pago ' || v_p.numero || ' · ' || v_p.proveedor_nombre, 'pago_proveedor', v_p.id::text, v_p.numero,
    jsonb_build_array(
      jsonb_build_object('cuenta', 'proveedores', 'debe', v_p.monto),
      jsonb_build_object('cuenta', public.clave_forma_pago(v_p.forma_pago), 'haber', v_p.monto)));
end;
$$;

create or replace function public.contabilizar_movimiento_caja(p_movimiento bigint)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_m public.cajas_movimientos;
  v_origen text;
begin
  select * into v_m from public.cajas_movimientos where id = p_movimiento;
  if not found then
    return null;
  end if;
  v_origen := case when v_m.tipo = 'entrada' then 'caja_entrada' else 'caja_salida' end;
  if exists (select 1 from public.asientos a where a.id_empresa = v_m.id_empresa and a.origen = v_origen
                and a.id_origen = v_m.id::text and a.id_revierte is null) then
    return null;
  end if;
  return public.asentar(
    v_m.id_empresa, (v_m.creado_en at time zone 'America/Tegucigalpa')::date,
    case when v_m.tipo = 'entrada' then 'Entrada de caja · ' else 'Salida de caja · ' end || v_m.concepto,
    v_origen, v_m.id::text, null,
    case when v_m.tipo = 'entrada' then jsonb_build_array(
      jsonb_build_object('cuenta', 'caja', 'debe', v_m.monto),
      jsonb_build_object('cuenta', 'bancos', 'haber', v_m.monto))
    else jsonb_build_array(
      jsonb_build_object('cuenta', 'gastos_generales', 'debe', v_m.monto),
      jsonb_build_object('cuenta', 'caja', 'haber', v_m.monto)) end);
end;
$$;

create or replace function public.contabilizar_cierre_caja(p_turno uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_t public.cajas_turnos;
begin
  select * into v_t from public.cajas_turnos where id = p_turno;
  if not found or v_t.estado <> 'cerrada' or coalesce(v_t.diferencia, 0) = 0
     or exists (select 1 from public.asientos a where a.id_empresa = v_t.id_empresa and a.origen = 'cierre_caja'
                   and a.id_origen = v_t.id::text and a.id_revierte is null) then
    return null;
  end if;
  return public.asentar(
    v_t.id_empresa, (v_t.cerrada_en at time zone 'America/Tegucigalpa')::date,
    case when v_t.diferencia < 0 then 'Faltante' else 'Sobrante' end || ' en el cierre del turno ' || v_t.numero,
    'cierre_caja', v_t.id::text, 'Turno ' || v_t.numero,
    case when v_t.diferencia < 0 then jsonb_build_array(
      jsonb_build_object('cuenta', 'faltantes_caja', 'debe', -v_t.diferencia),
      jsonb_build_object('cuenta', 'caja', 'haber', -v_t.diferencia))
    else jsonb_build_array(
      jsonb_build_object('cuenta', 'caja', 'debe', v_t.diferencia),
      jsonb_build_object('cuenta', 'sobrantes_caja', 'haber', v_t.diferencia)) end);
end;
$$;

-- Triggers: al confirmar la transacción (los documentos se insertan y luego se les ponen los totales).
create or replace function public.tg_contabilizar()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_name = 'documentos' then
    if new.tipo not in ('factura', 'nota_credito', 'nota_debito') then
      return null;
    end if;
    if tg_op = 'INSERT' then
      perform public.contabilizar_documento(new.id);
    elsif new.estado = 'anulado' and old.estado = 'emitido' then
      perform public.revertir_origen(new.id_empresa, new.tipo, new.id::text, 'Anulación de ' || new.numero);
    end if;
  elsif tg_table_name = 'pagos' then
    if tg_op = 'INSERT' then
      perform public.contabilizar_abono(new.id);
    elsif new.estado = 'anulado' and old.estado = 'emitido' then
      perform public.revertir_origen(new.id_empresa, 'abono', new.id::text, 'Anulación del recibo ' || new.numero);
    end if;
  elsif tg_table_name = 'compras' then
    if tg_op = 'INSERT' then
      perform public.contabilizar_compra(new.id);
    elsif new.estado = 'anulado' and old.estado = 'emitido' then
      perform public.revertir_origen(new.id_empresa, 'compra', new.id::text, 'Anulación de la compra ' || new.numero);
    end if;
  elsif tg_table_name = 'pagos_proveedores' then
    if tg_op = 'INSERT' then
      perform public.contabilizar_pago_proveedor(new.id);
    elsif new.estado = 'anulado' and old.estado = 'emitido' then
      perform public.revertir_origen(new.id_empresa, 'pago_proveedor', new.id::text, 'Anulación del pago ' || new.numero);
    end if;
  elsif tg_table_name = 'cajas_movimientos' then
    perform public.contabilizar_movimiento_caja(new.id);
  elsif tg_table_name = 'cajas_turnos' then
    if new.estado = 'cerrada' and old.estado = 'abierta' then
      perform public.contabilizar_cierre_caja(new.id);
    end if;
  end if;
  return null;
end;
$$;

do $$
declare
  v_tabla text;
begin
  foreach v_tabla in array array['documentos', 'pagos', 'compras', 'pagos_proveedores'] loop
    execute format('drop trigger if exists zz_contabilizar on public.%I', v_tabla);
    execute format('create constraint trigger zz_contabilizar after insert or update of estado on public.%I '
                   'deferrable initially deferred for each row execute function public.tg_contabilizar()', v_tabla);
  end loop;
  execute 'drop trigger if exists zz_contabilizar on public.cajas_movimientos';
  execute 'create constraint trigger zz_contabilizar after insert on public.cajas_movimientos '
          'deferrable initially deferred for each row execute function public.tg_contabilizar()';
  execute 'drop trigger if exists zz_contabilizar on public.cajas_turnos';
  execute 'create constraint trigger zz_contabilizar after update of estado on public.cajas_turnos '
          'deferrable initially deferred for each row execute function public.tg_contabilizar()';
end $$;

-- -----------------------------------------------------------------------------
-- 4. Funciones para la interfaz
-- -----------------------------------------------------------------------------

/*
  Asiento manual (dueño/admin). p_lineas: [{ id_cuenta, debe, haber, descripcion? }].
  Cuentas de detalle (sin subcuentas), activas y de la empresa. Debe cuadrar.
*/
create or replace function public.crear_asiento(p_empresa uuid, p_fecha date, p_concepto text, p_lineas jsonb)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_cuenta public.cuentas_contables;
  v_debe numeric := 0;
  v_haber numeric := 0;
  v_n integer := 0;
  v_lineas jsonb := '[]'::jsonb;
  v_d numeric;
  v_h numeric;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden registrar asientos.';
  end if;
  if nullif(btrim(p_concepto), '') is null then
    raise exception 'Escribí el concepto del asiento.';
  end if;
  if p_fecha is null or p_fecha > (now() at time zone 'America/Tegucigalpa')::date + 31 then
    raise exception 'Revisá la fecha del asiento.';
  end if;
  if jsonb_typeof(p_lineas) is distinct from 'array' or jsonb_array_length(p_lineas) > 200 then
    raise exception 'Revisá las líneas del asiento.';
  end if;
  for v_item in select * from jsonb_array_elements(p_lineas)
  loop
    v_d := round(coalesce(nullif(v_item ->> 'debe', '')::numeric, 0), 2);
    v_h := round(coalesce(nullif(v_item ->> 'haber', '')::numeric, 0), 2);
    continue when v_d = 0 and v_h = 0;
    v_n := v_n + 1;
    if v_d < 0 or v_h < 0 or (v_d > 0 and v_h > 0) then
      raise exception 'Línea %: va en el debe o en el haber, con monto positivo.', v_n;
    end if;
    select * into v_cuenta from public.cuentas_contables
     where id = nullif(v_item ->> 'id_cuenta', '')::bigint and id_empresa = p_empresa;
    if not found then
      raise exception 'Línea %: elegí la cuenta.', v_n;
    end if;
    if not v_cuenta.activo then
      raise exception 'La cuenta % % está inactiva.', v_cuenta.codigo, v_cuenta.nombre;
    end if;
    if exists (select 1 from public.cuentas_contables h where h.id_padre = v_cuenta.id) then
      raise exception '% % es una cuenta de grupo: usá una de sus subcuentas.', v_cuenta.codigo, v_cuenta.nombre;
    end if;
    v_debe := v_debe + v_d;
    v_haber := v_haber + v_h;
    v_lineas := v_lineas || jsonb_build_array(jsonb_build_object(
      'cuenta', v_cuenta.id, 'debe', v_d, 'haber', v_h, 'descripcion', v_item ->> 'descripcion'));
  end loop;
  if v_n < 2 then
    raise exception 'Un asiento lleva al menos dos líneas.';
  end if;
  if v_debe <> v_haber then
    raise exception 'No cuadra: debe L % y haber L %.', to_char(v_debe, 'FM999,999,990.00'), to_char(v_haber, 'FM999,999,990.00');
  end if;
  return public.asentar(p_empresa, p_fecha, p_concepto, 'manual', null, null, v_lineas);
end;
$$;

-- Reversa de un asiento manual (los automáticos se revierten anulando su documento).
create or replace function public.revertir_asiento(p_asiento uuid, p_motivo text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_a public.asientos;
begin
  select * into v_a from public.asientos where id = p_asiento for update;
  if not found or not public.tiene_rol(v_a.id_empresa, array['dueno', 'admin']) then
    raise exception 'El asiento no existe.';
  end if;
  if v_a.origen not in ('manual', 'apertura_inventario') then
    raise exception 'Este asiento lo generó un documento: anulá el documento y su reversa sale sola.';
  end if;
  if v_a.id_revierte is not null then
    raise exception 'Este asiento ya es una reversa.';
  end if;
  if v_a.revertido_por is not null then
    raise exception 'Este asiento ya fue revertido.';
  end if;
  if nullif(btrim(p_motivo), '') is null then
    raise exception 'Escribí el motivo de la reversa.';
  end if;
  return public.asentar(
    v_a.id_empresa, (now() at time zone 'America/Tegucigalpa')::date,
    'Reversa del asiento ' || v_a.numero || ': ' || btrim(p_motivo), v_a.origen, null, v_a.referencia,
    (select jsonb_agg(jsonb_build_object('cuenta', l.id_cuenta, 'debe', l.haber, 'haber', l.debe, 'descripcion', l.descripcion)
                      order by l.orden)
       from public.asientos_lineas l where l.id_asiento = v_a.id),
    v_a.id);
end;
$$;

create or replace function public.cerrar_periodo(p_empresa uuid, p_mes date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_mes date := date_trunc('month', p_mes)::date;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden cerrar meses.';
  end if;
  if v_mes >= date_trunc('month', (now() at time zone 'America/Tegucigalpa'))::date then
    raise exception 'Solo se cierran meses que ya terminaron.';
  end if;
  insert into public.periodos_cerrados (id_empresa, mes) values (p_empresa, v_mes)
  on conflict (id_empresa, mes) do nothing;
end;
$$;

create or replace function public.reabrir_periodo(p_empresa uuid, p_mes date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.tiene_rol(p_empresa, array['dueno']) then
    raise exception 'Solo el dueño puede reabrir un mes cerrado.';
  end if;
  delete from public.periodos_cerrados where id_empresa = p_empresa and mes = date_trunc('month', p_mes)::date;
end;
$$;

-- Contabiliza lo emitido antes de esta migración (solo lo vigente). Devuelve cuántos asientos creó.
create or replace function public.contabilizar_pendientes(p_empresa uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_n integer := 0;
  v_r record;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden contabilizar.';
  end if;
  perform public.crear_catalogo_base(p_empresa);
  for v_r in select d.id from public.documentos d
              where d.id_empresa = p_empresa and d.tipo in ('factura', 'nota_credito', 'nota_debito') and d.estado = 'emitido'
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = d.tipo
                                   and a.id_origen = d.id::text)
              order by d.fecha
  loop
    if public.contabilizar_documento(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  for v_r in select p.id from public.pagos p
              where p.id_empresa = p_empresa and p.estado = 'emitido'
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = 'abono'
                                   and a.id_origen = p.id::text)
  loop
    if public.contabilizar_abono(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  for v_r in select c.id from public.compras c
              where c.id_empresa = p_empresa and c.estado = 'emitido'
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = 'compra'
                                   and a.id_origen = c.id::text)
  loop
    if public.contabilizar_compra(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  for v_r in select p.id from public.pagos_proveedores p
              where p.id_empresa = p_empresa and p.estado = 'emitido'
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = 'pago_proveedor'
                                   and a.id_origen = p.id::text)
  loop
    if public.contabilizar_pago_proveedor(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  for v_r in select m.id from public.cajas_movimientos m
              where m.id_empresa = p_empresa
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa
                                   and a.origen in ('caja_entrada', 'caja_salida') and a.id_origen = m.id::text)
  loop
    if public.contabilizar_movimiento_caja(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  for v_r in select t.id from public.cajas_turnos t
              where t.id_empresa = p_empresa and t.estado = 'cerrada' and coalesce(t.diferencia, 0) <> 0
                and not exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = 'cierre_caja'
                                   and a.id_origen = t.id::text)
  loop
    if public.contabilizar_cierre_caja(v_r.id) is not null then v_n := v_n + 1; end if;
  end loop;
  return v_n;
end;
$$;

-- Asiento de apertura: el inventario que ya había (existencia × costo) contra Capital. Una sola vez.
create or replace function public.asiento_apertura_inventario(p_empresa uuid, p_fecha date)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_valor numeric;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador pueden registrar la apertura.';
  end if;
  if exists (select 1 from public.asientos a where a.id_empresa = p_empresa and a.origen = 'apertura_inventario'
                and a.id_revierte is null and a.revertido_por is null) then
    raise exception 'La apertura del inventario ya está registrada (revertila para hacerla de nuevo).';
  end if;
  select coalesce(sum(round(p.existencia * p.costo, 2)), 0) into v_valor
    from public.productos p
   where p.id_empresa = p_empresa and p.controla_inventario and p.existencia > 0 and p.costo > 0;
  if v_valor <= 0 then
    raise exception 'No hay inventario con costo para abrir.';
  end if;
  return public.asentar(
    p_empresa, coalesce(p_fecha, (now() at time zone 'America/Tegucigalpa')::date),
    'Apertura: inventario inicial a costo', 'apertura_inventario', null, null,
    jsonb_build_array(
      jsonb_build_object('cuenta', 'inventario', 'debe', v_valor),
      jsonb_build_object('cuenta', 'capital', 'haber', v_valor)));
end;
$$;

/*
  Balanza de comprobación: por cuenta, saldo antes del período, debe, haber y
  saldo final (según su naturaleza). Incluye todas las cuentas (las de grupo
  con lo propio en cero: la suma por árbol la hace la pantalla).
*/
create or replace function public.balanza(p_empresa uuid, p_desde date, p_hasta date)
returns table (
  id bigint, codigo text, nombre text, tipo text, naturaleza text, id_padre bigint, activo boolean,
  saldo_inicial numeric, debe numeric, haber numeric, saldo_final numeric
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador ven la contabilidad.';
  end if;
  return query
  with mov as (
    select l.id_cuenta,
           coalesce(sum(l.debe) filter (where a.fecha < p_desde), 0) as debe_antes,
           coalesce(sum(l.haber) filter (where a.fecha < p_desde), 0) as haber_antes,
           coalesce(sum(l.debe) filter (where a.fecha between p_desde and p_hasta), 0) as debe,
           coalesce(sum(l.haber) filter (where a.fecha between p_desde and p_hasta), 0) as haber
      from public.asientos_lineas l
      join public.asientos a on a.id = l.id_asiento
     where l.id_empresa = p_empresa and a.fecha <= p_hasta
     group by l.id_cuenta
  )
  select c.id, c.codigo, c.nombre, c.tipo, c.naturaleza, c.id_padre, c.activo,
         case when c.naturaleza = 'deudora' then coalesce(m.debe_antes - m.haber_antes, 0)
              else coalesce(m.haber_antes - m.debe_antes, 0) end,
         coalesce(m.debe, 0),
         coalesce(m.haber, 0),
         case when c.naturaleza = 'deudora'
              then coalesce(m.debe_antes - m.haber_antes + m.debe - m.haber, 0)
              else coalesce(m.haber_antes - m.debe_antes + m.haber - m.debe, 0) end
    from public.cuentas_contables c
    left join mov m on m.id_cuenta = c.id
   where c.id_empresa = p_empresa
   order by c.codigo;
end;
$$;

-- Libro mayor de una cuenta: saldo inicial y cada movimiento con su saldo corrido.
create or replace function public.mayor(p_empresa uuid, p_cuenta bigint, p_desde date, p_hasta date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_c public.cuentas_contables;
  v_inicial numeric;
  v_signo integer;
begin
  if not public.tiene_rol(p_empresa, array['dueno', 'admin']) then
    raise exception 'Solo el dueño o un administrador ven la contabilidad.';
  end if;
  select * into v_c from public.cuentas_contables where id = p_cuenta and id_empresa = p_empresa;
  if not found then
    raise exception 'La cuenta no existe.';
  end if;
  v_signo := case when v_c.naturaleza = 'deudora' then 1 else -1 end;
  select coalesce(sum(l.debe - l.haber), 0) * v_signo into v_inicial
    from public.asientos_lineas l join public.asientos a on a.id = l.id_asiento
   where l.id_cuenta = p_cuenta and a.fecha < p_desde;
  return jsonb_build_object(
    'saldo_inicial', v_inicial,
    'movimientos', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id_asiento', x.id, 'numero', x.numero, 'fecha', x.fecha, 'concepto', x.concepto,
               'referencia', x.referencia, 'descripcion', x.descripcion, 'debe', x.debe, 'haber', x.haber,
               'saldo', v_inicial + x.corrido) order by x.fecha, x.numero, x.orden)
        from (select a.id, a.numero, a.fecha, a.concepto, a.referencia, l.descripcion, l.debe, l.haber, l.orden,
                     sum((l.debe - l.haber) * v_signo) over (order by a.fecha, a.numero, l.orden) as corrido
                from public.asientos_lineas l join public.asientos a on a.id = l.id_asiento
               where l.id_cuenta = p_cuenta and a.fecha between p_desde and p_hasta) x), '[]'::jsonb));
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Vistas
-- -----------------------------------------------------------------------------

create or replace view public.v_cuentas_contables with (security_invoker = true) as
select c.id,
       c.id_empresa,
       c.codigo,
       c.nombre,
       c.tipo,
       c.naturaleza,
       c.id_padre,
       p.codigo || ' · ' || p.nombre as padre,
       c.clave,
       c.activo,
       exists (select 1 from public.cuentas_contables h where h.id_padre = c.id) as es_grupo,
       length(c.codigo) as nivel,
       c.codigo || ' · ' || c.nombre as etiqueta,
       coalesce((select sum(case when c.naturaleza = 'deudora' then l.debe - l.haber else l.haber - l.debe end)
                   from public.asientos_lineas l where l.id_cuenta = c.id), 0) as saldo,
       c.creado_en
  from public.cuentas_contables c
  left join public.cuentas_contables p on p.id = c.id_padre;

create or replace view public.v_asientos with (security_invoker = true) as
select a.id,
       a.id_empresa,
       a.numero,
       a.fecha,
       a.concepto,
       a.origen,
       a.id_origen,
       a.referencia,
       coalesce(t.debe, 0) as total,
       coalesce(t.lineas, 0)::integer as lineas,
       a.id_revierte is not null as es_reversa,
       a.revertido_por is not null as revertido,
       u.nombre as registro,
       a.creado_en
  from public.asientos a
  left join (select id_asiento, sum(debe) as debe, count(*) as lineas from public.asientos_lineas group by id_asiento) t
    on t.id_asiento = a.id
  left join public.usuarios u on u.id = a.creado_por;

create or replace view public.v_asientos_lineas with (security_invoker = true) as
select l.id, l.id_asiento, l.id_empresa, l.id_cuenta, c.codigo, c.nombre as cuenta, l.debe, l.haber, l.descripcion, l.orden
  from public.asientos_lineas l
  join public.cuentas_contables c on c.id = l.id_cuenta;

-- -----------------------------------------------------------------------------
-- 6. Permisos y RLS (la contabilidad la ven dueño/admin)
-- -----------------------------------------------------------------------------

revoke all on public.cuentas_contables, public.asientos, public.asientos_lineas, public.periodos_cerrados
  from anon, authenticated;
grant select, insert, delete on public.cuentas_contables to authenticated;
grant update (codigo, nombre, tipo, naturaleza, id_padre, clave, activo) on public.cuentas_contables to authenticated;
grant select on public.asientos, public.asientos_lineas, public.periodos_cerrados to authenticated;

alter table public.cuentas_contables enable row level security;
alter table public.asientos enable row level security;
alter table public.asientos_lineas enable row level security;
alter table public.periodos_cerrados enable row level security;

drop policy if exists admin_todo on public.cuentas_contables;
create policy admin_todo on public.cuentas_contables
  for all to authenticated
  using (public.tiene_rol(id_empresa, array['dueno', 'admin']))
  with check (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.asientos;
create policy admin_lectura on public.asientos
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.asientos_lineas;
create policy admin_lectura on public.asientos_lineas
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));
drop policy if exists admin_lectura on public.periodos_cerrados;
create policy admin_lectura on public.periodos_cerrados
  for select to authenticated using (public.tiene_rol(id_empresa, array['dueno', 'admin']));

-- Internas: solo las usan otras funciones.
revoke all on function public.asentar(uuid, date, text, text, text, text, jsonb, uuid) from public, anon, authenticated;
revoke all on function public.revertir_origen(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.cuenta_por_clave(uuid, text) from public, anon, authenticated;
revoke all on function public.crear_catalogo_base(uuid) from public, anon, authenticated;
revoke all on function public.contabilizar_documento(uuid) from public, anon, authenticated;
revoke all on function public.contabilizar_abono(uuid) from public, anon, authenticated;
revoke all on function public.contabilizar_compra(uuid) from public, anon, authenticated;
revoke all on function public.contabilizar_pago_proveedor(uuid) from public, anon, authenticated;
revoke all on function public.contabilizar_movimiento_caja(bigint) from public, anon, authenticated;
revoke all on function public.contabilizar_cierre_caja(uuid) from public, anon, authenticated;

revoke all on function public.crear_asiento(uuid, date, text, jsonb) from public, anon;
revoke all on function public.revertir_asiento(uuid, text) from public, anon;
revoke all on function public.cerrar_periodo(uuid, date) from public, anon;
revoke all on function public.reabrir_periodo(uuid, date) from public, anon;
revoke all on function public.contabilizar_pendientes(uuid) from public, anon;
revoke all on function public.asiento_apertura_inventario(uuid, date) from public, anon;
revoke all on function public.balanza(uuid, date, date) from public, anon;
revoke all on function public.mayor(uuid, bigint, date, date) from public, anon;
grant execute on function public.crear_asiento(uuid, date, text, jsonb) to authenticated;
grant execute on function public.revertir_asiento(uuid, text) to authenticated;
grant execute on function public.cerrar_periodo(uuid, date) to authenticated;
grant execute on function public.reabrir_periodo(uuid, date) to authenticated;
grant execute on function public.contabilizar_pendientes(uuid) to authenticated;
grant execute on function public.asiento_apertura_inventario(uuid, date) to authenticated;
grant execute on function public.balanza(uuid, date, date) to authenticated;
grant execute on function public.mayor(uuid, bigint, date, date) to authenticated;

revoke all on public.v_cuentas_contables, public.v_asientos, public.v_asientos_lineas from anon;
grant select on public.v_cuentas_contables, public.v_asientos, public.v_asientos_lineas to authenticated;

-- Auditoría (0011): el catálogo (los asientos ya son su propio registro).
do $$
begin
  if to_regprocedure('public.registrar_cambio()') is not null then
    execute 'create or replace trigger zz_registrar_cambio after insert or update or delete on public.cuentas_contables '
            'for each row execute function public.registrar_cambio()';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 7. Catálogo para las empresas que ya existen
-- -----------------------------------------------------------------------------

select public.crear_catalogo_base(e.id) from public.empresas e;

-- Y para cada empresa nueva, al registrarse.
create or replace function public.tg_catalogo_empresa()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.crear_catalogo_base(new.id);
  return null;
end;
$$;

revoke all on function public.tg_catalogo_empresa() from public, anon, authenticated;

create or replace trigger zz_catalogo_contable
  after insert on public.empresas
  for each row execute function public.tg_catalogo_empresa();

comment on table public.cuentas_contables is
  'Catálogo de cuentas por empresa (árbol). clave = la cuenta que usa el sistema en los asientos automáticos.';
comment on table public.asientos is
  'Asientos contables (partida doble). Automáticos por documento (origen + id_origen) o manuales. Se corrigen con reversa.';
comment on table public.periodos_cerrados is 'Meses cerrados: no aceptan asientos (reabre solo el dueño).';

commit;
